### ISSUE TITLE
Repostitory structure for v2.0.0 is not compliant

### ISSUE THREAD

**Issue by eyal-h** [nielsfaber/scheduler-component#10]
when i try to add "https://github.com/nielsfaber/scheduler-component" to HACS i am getting this error
"Repostitory structure for v2.0.0 is not compliant"

**Comment by KTibow** [comment]
Odd, I don't get it. Can you try again and take a screenshot?

**Comment by nielsfaber** [comment]
Assuming this is fixed in the mean time. 
If not, it can be re-opened.
