### ISSUE TITLE
Add Trigger State "next_event"

### ISSUE THREAD

**Issue by derwolff** [nielsfaber/scheduler-component#103]
Hi,

It would be very useful if there were a "next_event" status in addition to the "next_trigger" state. This would report whether it is then switched on or off.
In my automation, for example, I am only interested in which time period something is switched on. Maybe you can implement that in the near future.
Thanks.

**Comment by nielsfaber** [comment]
Currently scheduler entities have `next_slot` and `actions` attributes.
You could combine them to extract the next action.
I could add a `next_action` attribute, but it would introduce dedundant info.
What do you have in mind specifically?
It should be generic, e.g. setting a temperature involves service_data, so is more complexe than a switch on/off job.

![image](https://user-images.githubusercontent.com/16861605/117496432-552e5180-af77-11eb-9154-77e8d9dcc9b6.png)

**Comment by derwolff** [comment]
Ok now I understand the parameter next_slot. I have created now a template sensor to check the slot and next trigger time.
And you are right, it's more complex than on/off .
In my case I want to switch on my mower 2.5 hours before start to ensure that the accu is fully charged.
