### ISSUE TITLE
[feature request] Actions on turning on/off schedule

### ISSUE THREAD

**Issue by eode** [nielsfaber/scheduler-component#105]
The basic idea is to have schedules that, when turned off, revert to whatever state they should be in if unscheduled.

As an example, I have a water pump on a schedule.  When the schedule isn't needed, the pump should be off.  The schedule may be in a time slot where the pump is on at the time the schedule is disabled.  The pump then must also be disabled via a separate switch.

Current behavior, if I understand correctly:

 * Turning a schedule on checks the conditions for the current time slot and, if valid, performs the actions.  If invalid, it waits until the conditions are valid, then performs the actions.
  * Turning a schedule off does nothing.

Desired Feature:
 * Turning off a schedule may trigger some actions

Examples of what that might look like:

* timeslot-based example
  * time slots have an 'abort_actions' list
    * if a schedule is turned off, the 'abort_actions' of the current timeslot are performed
* schedule-based example
  * Each schedule has a 'start_actions' and a 'stop_actions'.
    * these are in the *schedule*, not the time slot.
    * these actions are performed when enabling or disabling that schedule.
    * default start actions are to check conditions of the current time slot and run that time slot's actions (same as current behavior)
    * default stop actions are empty (same as current behavior)

Either of these solutions would allow returning a device to a default state when the schedule is turned off.

It should be noted that, as with coding, there may be more than one way to the same goal in a complex home automaton system like HA.  As such, the same effect I'm looking for can be achieved by creating an automation that watches for the schedule to go from 'on' to 'off'.  The options above would simply be more centralized and, IMO, clean, from a home configuration standpoint.

In any case - thank you for your time and for evaluating this, as well as your great work on this plugin overall.

**Comment by eode** [comment]
Note:  I think I prefer the timeslot-based approach more.  I imagine that would be easier to work into the front-end, but also because it's more fine-grained.  

Specifically, I can make an automation that turns off the pump when the schedule turns off, but what if the schedule is being turned off because someone started the pump manually ahead of time, and plans to handle it themselves?  A timeslot-based approach largely guarantees that it was the scheduler that turned the pump on in the first place.

Also, I don't know if I can even access timeslots with an automation in a reasonably straightforward way.

**Comment by nielsfaber** [comment]
The general idea behind scheduler is to create a tool to plan actions that should trigger on a certain time of the day.
Your proposal to have actions assigned to the enabling/disabling of a schedule deviates from this idea.
I also think it is _very_ use-case specific, and think only a few people will use such function (such request was never asked before, which kind of comfirms it for me).

Therefore I think it is best to implement such intelligence by means of external automations, which gives the user all kinds of flexibility to add custom  behaviour.
The schedule entities are deliberately set up as switches, such that they can easily be used/extended with automations.

I do understand your point of keeping your config clean (and I hope scheduler helps you with that), but I have to keep the scope of scheduler as compact as possible to keep the UI intuitive for all users and for being able to maintain the code.

If you see a need for any change in scheduler to facilitate the usage with external automations, please let me know.
Sorry for not pursuing your request.

**Comment by H3buss** [comment]
I concur with the request.

My use case is with my heating scheduling. I want to implement "away" and "heating idle" modes that set the heating to a specific target temperature. Upon existing those special modes, I would like all my heating setup to resume to the scheduled temperature of the current time slot.

If I understand correctly, I can get this behavior with a call to scheduler.run_action?

**Comment by eode** [comment]
@H3buss I am not the author, and I am uncertain of this advice.

It sounds like you want mutually-exclusive schedules.  That *should* be doable by:

* set up each schedule, let's say "home", "away", and "idle".
* set up an automation - one large one that then uses 'choice', or one for each schedule.
* when any of the three schedules is turned on, turn off the other two.

That *should* do what you want, if I understand you correctly.

**Comment by H3buss** [comment]
I tested calling  scheduler.run_action when I enable the scheduler, and it works.

**Comment by eode** [comment]
@nielsfaber thanks for the reply.
