### ISSUE TITLE
FR: Read schedules from other devices.

### ISSUE THREAD

**Issue by foxsam21** [nielsfaber/scheduler-component#109]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I would like to be able to read/write from existing schemes using the HA api/service calls. The idea is to be able to use a device flashed with ESPhome to get and set schedules. similar to a "7-day programmable thermostat". The basic schedule would be set using the UI and the times of "wake" or "return" etc would be adjusted remotely and the equivalent action can also be set i.e. set temp to 23 etc...

**Comment by nielsfaber** [comment]
I have no idea how this can work.
There is no such thing as a HA API, so all integrations may communicate in a different way.
It will not be easy to be compatible with all.
What is the benefit of storing the schedule in your device, rather than sending commands from HA?

**Comment by foxsam21** [comment]
I'm not sure if I make sense or am being clear. I don't want to store the schedule but I want to be able to know the schedule and edit only one part. So my goal would be to have a device ESPHome for example that uses HA service calls to get the current state of the schedule component. So it would "know" for example from 6:00AM until 8:00AM call for cooling at 19C, from 8:00AM until 3:00PM set target temp to 24. Then pressing buttons we can change the target for the second time slot, or the start/end time of a time slot. Same as what we do from the UI but using a wireless device as a remote.
