### ISSUE TITLE
Add sunrise and sunset to planner

### ISSUE THREAD

**Issue by fernandeusto** [nielsfaber/scheduler-component#115]
### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [ X] My request is generic, other users may benefit from it too.

### Proposal
[add the option to add sunrise and sunset to planner]

### Additional info
[So you could make a single timer to turn on the light when it gets dark and turn it off x minutes before sunrise]

**Comment by nielsfaber** [comment]
Not related to scheduler-component + duplicate request.
