### ISSUE TITLE
Last timeslot not recognized if schedule is enabled after time slot has started and if schedule won't repeat on the following day

### ISSUE THREAD

**Issue by TobiasKneidl** [nielsfaber/scheduler-component#119]
Hopefully I can describe this comprehensible.

### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
If I disable and enable a schedule, the actual time slot is recognized and performed as described in doc:

> If you enable a disabled time scheme: the schedule will determine which timeslot is active, and trigger this action immediately.

### Actual behavior
If it's the last time slot of the day and the schedule is not repeated on the following day, the action will not be triggered if the schedule is activated after the time slot has started.

### Steps to Reproduce
- Create a schedule and choose only the current day.
- Set the start of the last time slot a few minutes in the past.
(Its 08:30 so i set the last timeslot to 08:00)
- Save and enable the Schedule -> Action will not be triggered

 
![schedule](https://user-images.githubusercontent.com/26301707/131453867-1e575890-cd81-4bae-883c-524a07b11ddd.png)

**Comment by nielsfaber** [comment]
Curious bug, I will look into this somewhere in the next days and let you know what comes out of it.
Sorry for the delay.

**Comment by nielsfaber** [comment]
I just gave it a try but for me all seems OK.

My schedule config:
![image](https://user-images.githubusercontent.com/16861605/134369638-fc55b0ab-32fe-4ce3-9da1-ac2ddece0341.png)
(on the options tab I didnt set anything, I assume you didn't assign a date range?)

Debug logging from scheduler:
```
2021-09-22 17:05:20 DEBUG (MainThread) [custom_components.scheduler.switch] Schedule a2d18e is starting in a timeslot, proceed with actions,
2021-09-22 17:05:20 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of a2d18e set for 2021-09-22 23:59:59+02:00,
2021-09-22 17:05:20 DEBUG (MainThread) [custom_components.scheduler.actions] [a2d18e]: Executing service input_boolean.turn_on on entity input_boolean.my_switch
```

History:
![image](https://user-images.githubusercontent.com/16861605/134369856-0c6069ec-7647-4d80-9a47-7036e3983184.png)


Could you show some similar data for your case, to illustrate the problem you're facing?

If you want to have the debug logging for scheduler visible, you can add something like this to configuration.yaml (+reboot HA):
``` 
logger:
  default: warning
  logs:
    custom_components.scheduler: debug
```

**Comment by TobiasKneidl** [comment]
@nielsfaber 
First I thought it's OK for you because you've set the schedule to run daily. If it repeats on the following day everything was fine.

But if it won't repeat on the following day, the bug appeared to me. 

In your example you would have to choose to run only on Wednesday or Monday-Wednesday.


Nevermind, I just tried it again with my example and I can't reproduce the bug.

Maybe it was a side effect of the update?
Initially I've noticed the misbehaviour in version 3.1.3

So I think the bug can be closed. Sorry for that.

**Comment by nielsfaber** [comment]
Sorry, I overlooked what you said about choosing a specific day.
In the code the weekday repetition behaviour is handled in a completely different place to where the timeslot actions are determined, so for me such relation is very unlikely.
Looking in the [file history ](https://github.com/nielsfaber/scheduler-component/blame/main/custom_components/scheduler/switch.py#L224
)I cannot find any relevant change since 5 months ago, I also don't remember any issues related to this.
The 3.1.x->3.2.0 update involved mostly changes for handling start+stop dates (you can now assign a date period to a schedule). 
Anyway, let's assume it's fixed, you can always re-open if it occurs again.
