### ISSUE TITLE
Schedule runs if off when HA is restarted

### ISSUE THREAD

**Issue by browetd** [nielsfaber/scheduler-component#121]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
The schedule is not executed if off when HA starts

### Actual behavior
The schedule is kept off but is executed...

### Steps to Reproduce
I created an additional entry in the scheduler turning on a boolean entity at a specific time (during the day).  Before restarting HA, the boolean is off and the schedule entry is disabled but after HA started, the boolean is on but the schedule entry is still off... I have other entities turning on as well when HA starts even if schedule are off.  
The behaviour exists since the last update to V3.2.0.

**Comment by browetd** [comment]
Same issue than #120 ... Encoded at the same time.  I close this one

**Comment by lmagyar** [comment]
And #120 is already fixed!
