### ISSUE TITLE
Copy schedule

### ISSUE THREAD

**Issue by mariusGitSann** [nielsfaber/scheduler-component#122]
I haven't dug into the code, but if it is simple to grab the schedule data, it would have been really nice to be able to copy schedules to new schedule. Let's say you put some effort into making a weekday schedule, and want a similar schedule for the weekend, you will have to do it twice. With a copy function you will be able to deploy the configured schedule, and do minor modifications to the new schedule

### Proposal
Add service and/or function on scheduler card top copy a schedule.

**Comment by nielsfaber** [comment]
Sounds doable 👍 
For now, let's keep it to a scheduler.copy service.
Since no one requested such functionality in over a year, i doubt if it should be added to the card.

**Comment by nielsfaber** [comment]
This is added in the v3.2.2 release.

**Comment by mariusGitSann** [comment]
> This is added in the v3.2.2 release.

Thanks alot! Adding it as as service was a good idea, I agree that it doesn't have to be in the card.

Thanks for a great integration!
