### ISSUE TITLE
New temperature settings isn't applied if thermostat is in off state

### ISSUE THREAD

**Issue by simbatl** [nielsfaber/scheduler-component#129]
Scenrario:
Last temperature setting: 20
Current state of thermostat: off
Next setting in scheduler: 21

When scheduler kicks in, the thermostat is switched on and set to 20 degrees. It does not update to the new temperature setting which is 21 degrees.

Problem occur on Fibaro heat controller (FGT-001)

**Comment by nielsfaber** [comment]
If you select the “heat” action in the card, scheduler executes `climate.set_hvac_mode` service followed by `climate.set_temperature`, with a short delay in between.

If that doesn’t work for your fibaro thermostat, I don’t know how to help.
