### ISSUE TITLE
Feature Request: Re-evaluate conditions when any of the entities involved in the conditions change.

### ISSUE THREAD

**Issue by daelsc** [nielsfaber/scheduler-component#135]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior

It would be great if conditions are re-evaluated when any of the entities involved change.  My particular use case is to switch my thermostats between a "home" schedule and an "away" schedule.  If I arrive at home in the middle of a time slot I want the thermostats to be set to the value of the current time slot and not wait until the next time slot starts.

### Actual behavior
[What actually happened]

### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by nicolas-joubert** [comment]
I agree it was a great feature. Because you already have code behavior "If HA is restarted: the schedule will determine which timeslot is active, and trigger this action immediately" maybe it's easier to allow trigger it asa service. So call service when entity changes can be set using automation.
Have a great day and many thanks for your job on this plugin.

**Comment by nielsfaber** [comment]
@daelsc 
Your requested feature has been added in the latest updates of scheduler-component + scheduler-card.
After updating, you will be able to apply this setting to achieve the behaviour you are looking for:
![image](https://user-images.githubusercontent.com/16861605/145554211-b5eaf974-71a1-436f-b62f-31821bda06a3.png)

Note that the feature is only available for time schemes (so when timeslots are defined) and if conditions are assigned.
Please test it out and close the request if you're happy with the result.

**Comment by moskyow** [comment]
@nielsfaber I not find the option for re-evalutate 
Where is it ?

**Comment by KTibow** [comment]
@moskyow
1. Update scheduler-component
2. Update scheduler-card
3. Refresh with clearing cache (ctrl/command+shift+r)

**Comment by moskyow** [comment]
@KTibow 
1. Done
2. Done
3. Done

I use schema for clima and when I set the condition I not find the checkbox

**Comment by daelsc** [comment]
AMAZING!  This is incredible, thanks for adding the features.  I've played
with it quite a bit and it is close....but I found a few issues:

(For context: I use scheduler to control thermostats to a scheme that
varies based on the "house mode" (an input select) of "home" "away"
"vacation".  By having it continually re-evaluate if conditions change I am
able to change the "house mode" and switch between different schemes.  )

1.  It seems to enforce the scheme, regardless of if the condition
changes.  So I am unable to manually over-ride the set temperature.  I
think it should only re-evaluate if the specific condition changes, in my
case "house mode".

2.  Turning off the schedule doesn't always seem to work, it often
continues to run the schedule even when the schedule has been disabled.

3.  If the schedule is edited from a card that has limited "included
entities" it also filters the entities included for conditions, it seems
like all entities should be shown here.  (For example, I have a card that
only shows my thermostat schedules but I am unable to select an "input
select" as a condition for that schedule if I edit it from the thermostat
card)

**Comment by nielsfaber** [comment]
@daelsc  Thanks for your feedback!
My response below.

> 1.  It seems to enforce the scheme, regardless of if the condition
changes.  So I am unable to manually over-ride the set temperature.  I
think it should only re-evaluate if the specific condition changes, in my
case "house mode".

There was initially a bug (see https://github.com/nielsfaber/scheduler-component/issues/156) which caused the schedule to be executed again if the targeted entity (e.g. thermostat) was changed. This has been resolved in the last update, so it seems you're not running latest-greatest.

> 2.  Turning off the schedule doesn't always seem to work, it often
continues to run the schedule even when the schedule has been disabled.

This shouldn't happen, I will look into this!

> 3.  If the schedule is edited from a card that has limited "included
entities" it also filters the entities included for conditions, it seems
like all entities should be shown here.  (For example, I have a card that
only shows my thermostat schedules but I am unable to select an "input
select" as a condition for that schedule if I edit it from the thermostat
card)

Included entities list is used for choosing both target entities and condition entities for your schedules.
I wouldn't like to have all my binary_sensors show up in the card, I have like 100. I guess it's a matter of taste.
Let's not discuss this further here, it is off-topic.

**Comment by nielsfaber** [comment]
@daelsc 
> Turning off the schedule doesn't always seem to work, it often
continues to run the schedule even when the schedule has been disabled.

I saw this behaviour as well, I have overlooked the case while testing. There is a new release v3.2.6 which should solve it.

Could you please update and confirm your issues 1+2 have been resolved now? If so, you can close this issue.
Further improvements in the card regarding condition entities can be discussed in a new issue (in the scheduler-card repository).

**Comment by daelsc** [comment]
Amazingly quick response!  With v3.2.6 items 1+2 have been resolved, thank you!!!

(As for item 3 it is completely usable as is.  I respect your design decision, there's no one right answer!)
