### ISSUE TITLE
No connection to component

### ISSUE THREAD

**Issue by DirkMu** [nielsfaber/scheduler-component#137]
Hello. I just switched from UI controlled lovelace configuration (storage) to YAML controlled lovelace configuration. 

Before, the scheduler card worked fine. Since I switched to YAML I get the message that the card cannot connect to the component. 

![image](https://user-images.githubusercontent.com/53949754/138658289-8532fa0a-902a-45c9-98ff-e7d3b9642608.png)

### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
Card can connect to component

### Actual behavior
Card cannot connect to component

### Steps to Reproduce
I assume you need to switch to YAML controlled lovelace.

**Comment by rr-pb** [comment]
Hello hello I also have this problem appeared after installing the latest update (v.3.2.7)  HA core version 2022.2.6 . I tried to uninstall and reinstall but it no longer works comes out just the message indicated by the friend. how can I fix
![image](https://user-images.githubusercontent.com/84244283/153957114-1c8e3591-ed52-4f4d-8b8a-f27c0579950e.png)

**Comment by bjrnptrsn** [comment]
> Hello hello I also have this problem appeared after installing the latest update (v.3.2.7) HA core version 2022.2.6 . I tried to uninstall and reinstall but it no longer works comes out just the message indicated by the friend. how can I fix

you might forgot to install the integration.
go to: Configuration -> Devices & Services -> Integration -> (+ Add Integration): Scheduler component

**Comment by bjrnptrsn** [comment]
I use that component since yesterday, also had that problem first when until I added like mentioned.
you should try to remove and re-add that component.
