### ISSUE TITLE
Offset time for triggering action

### ISSUE THREAD

**Issue by lunjoa** [nielsfaber/scheduler-component#138]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Ability to offset time for triggering actions with value template.

### Additional info
When I schedule an action at a certain time I would like to actually trigger the action earlier with a calculated offset.
Use case is for example a car heater:
The heater takes some time to warm up the cabin. The time needed depends on the temperature difference of the actual temperature and the wanted temperature. The scheduler is set to departure time. The scheduler calls the action x minutes earlier to get the car warmed up in time for the user's set departure time.

**Comment by nielsfaber** [comment]
I think this will over complicate this scheduler. I don’t feel like adding this functionality.
