### ISSUE TITLE
Update installed

### ISSUE THREAD

**Issue by cfgroenewald** [nielsfaber/scheduler-component#139]
### Checklist
- [yes ] I checked for similar existing issues (both open and closed) before posting.
- [ Yes] I am running the latest version.

### Expected behavior
[Normal schedular operation]

### Actual behavior
[I Updated to the newest version, now the card does not seem to exist any longer?]

### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by nielsfaber** [comment]
How can I help you?
From which version did you update?
Is anything displayed in the logs of HA or your [browser](https://zapier.com/help/troubleshoot/behavior/view-and-save-your-browser-console-logs)?
