### ISSUE TITLE
Existing schedule does not accept new time

### ISSUE THREAD

**Issue by juan11perez** [nielsfaber/scheduler-component#14]
want to share what may be a bug, unless i’m overlooking something.
Once you create a schedule, if you go back later and change the time, it doesn’t change.
It will only respect the originally created time input.

**Comment by nielsfaber** [comment]
Can you reproduce this problem?
If so, could you share the steps that lead to this behaviour.
I have never seen or heard anything like this.

**Comment by juan11perez** [comment]
Sure, thank you.
So you create a schedule/switch. 
In this example i didnt change the time. So it was set at 12:00
I then went back and change the time to 13:20
![Screenshot_2020-09-07_13-13-16](https://user-images.githubusercontent.com/30061229/92371006-1e641b00-f10c-11ea-9fe0-03ecc062f84a.png)

but whist the card does show 13:20. The entity stays at 12:00

![Screenshot_2020-09-07_13-12-36](https://user-images.githubusercontent.com/30061229/92371082-389df900-f10c-11ea-8f8e-dc86f8de96fd.png)

So this example will only trigger at 12 as initially selected.

**Comment by nielsfaber** [comment]
You’re absolutely right.
The ‘next trigger’ looks out of sync, it keeps the old value.
I’m fairly sure that the actions will also fire at 12:00 still, I’m surprised no one else (including me) ever noticed this.
I will have to dive into this, might take some time to figure it out.

**Comment by juan11perez** [comment]
Yes, it triggers at the originally selected time.  In this case 12:00
Thank you for your response.

**Comment by jostie123** [comment]
same issue here,

just to add to the above if you turn the schedule off and back on the new time will be picked up from the card.

**Comment by nielsfaber** [comment]
Sorry about the delay. I found the cause of this issue.
I fixed it in [v2.0.1](https://github.com/nielsfaber/scheduler-component/releases/tag/v2.0.1)

**Comment by juan11perez** [comment]
Thank you very much for the fix and consideration
