### ISSUE TITLE
Wait until entities are available

### ISSUE THREAD

**Issue by alexyao2015** [nielsfaber/scheduler-component#140]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Sometimes when a scheduled time is reached, the entity may be unavailable and the scheduler will fail to produce an action. It would be great if there was a setting to simply have it wait until the entity is available with a max wait timeout before performing the scheduled action.

### Additional info
[some example of how the new functionality should look like]

**Comment by nielsfaber** [comment]
This is already the case.

**Comment by alexyao2015** [comment]
How does that currently work? Mentioning this issue because I noticed it failed to trigger because an entity was unavailable.

**Comment by nielsfaber** [comment]
Did you configure the schedule as a time scheme or a single task?

**Comment by alexyao2015** [comment]
I'm using this with the lovelace scheduler card so I'm using whatever that does.

**Comment by nielsfaber** [comment]
Please enable debug logging and share some log of a case where the entity is unavailable but the action is not postponed.

There should be literally a log line mentioning of the entity being unavailable causing the action to be postponed until it becomes available.
