### ISSUE TITLE
support for "calendar" sensor as condition

### ISSUE THREAD

**Issue by martinhoess** [nielsfaber/scheduler-component#141]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Support for the home assistant [calendar sensor ](https://www.home-assistant.io/integrations/calendar/) as a condition for a schedule entry

with a calendar integration like [google calendar](https://www.home-assistant.io/integrations/google/) you can add calendar entries to home assistant. the scheduler component currently doesn't support these. currently I have to make a binary sensor template for every calendar.

### Additional info
For example I've a calendar with entries if I have a day off, now I want to have a condition in my schedule to do something like: turn on XY at 06:00 but not if its my day off.

**Comment by nielsfaber** [comment]
How does the calendar entity look like in HA?
Documentation is kind of limited (non-existent), I wouldn't know how to change scheduler to make it compatible.
I don't use this myself, so there is no easy way for me to test such feature.

Are you able/willing to implement this improvement yourself and submit this via PR?

**Comment by martinhoess** [comment]
in HA they look more or less like switches 
![image](https://user-images.githubusercontent.com/47973549/139913767-c2d98687-84c6-4f45-9e6e-c34fa3dc8104.png)

Currently I only use the all day events, so I don't know how the events with time slots behave. But I think they switch to "on" for the specific time slot. 

I think the easiest way would be the ical component https://github.com/tybritten/ical-sensor-homeassistant (should work with any publicly available ical url) since this also creates a calendar entity like the HA google calendar component.

Had a look at the code, but I think this is beyond my non-existent python skills. But I am happy to test any changes.

**Comment by nielsfaber** [comment]
In this case I believe it's a matter of telling the card which states are valid for a calendar entity.
```
customize:
  calendar:
    states: ['on','off']
```
This should be added in the card configuration through YAML mode.

See also: https://github.com/nielsfaber/scheduler-card#conditions

I believe this will make your 'urlaub' calendar automatically show up as selectable for conditions.

**Comment by martinhoess** [comment]
Does this work even if the calendar entities are not displayed in this list at all?
![image](https://user-images.githubusercontent.com/47973549/139917160-5ae1adcd-8388-4576-9184-7725b7561abb.png)
