### ISSUE TITLE
Time selector/slider shows off by 1 hour

### ISSUE THREAD

**Issue by JOHLC** [nielsfaber/scheduler-component#144]
### Checklist
- [x] I am running the latest version.
- [x] I checked for similar existing issues (both open and closed) before posting.

### Expected behavior
When dragging the slider for a time schedule, the popup time display shows the correct time you select

### Actual behavior
Time is off by one hour when dragging the slider

### Steps to Reproduce
Create a new schedule with a time selector and click/hold the selector, drag it to show 5:00AM
![image](https://user-images.githubusercontent.com/63735432/140656995-f49bd54e-0290-4103-8d20-a2e4824e0512.png)

Release the selector and notice the time shows 1 hour different
![image](https://user-images.githubusercontent.com/63735432/140657041-3762cf9d-4110-4e08-aa22-e40c00d033ac.png)

I have confirmed the time on Home Assistant, host, and my PC match. 
This happens with both new and old schedules

**Comment by JOHLC** [comment]
Possibly related to #94 and https://github.com/nielsfaber/scheduler-card/issues/354

**Comment by JOHLC** [comment]
This issue seems to disappear the following day.

**Comment by nielsfaber** [comment]
I wouldn’t know how to reproduce this.
I have never seen it myself.
If you have any ideas how I could test it, I would like to hear it, otherwise I wouldn’t know how to help.

**Comment by gmcaesar** [comment]
I have noticed mine off by two hours, is this about using local time? I'm in Vancouver
