### ISSUE TITLE
scheduler.edit : to not supply all parameters, only those that change

### ISSUE THREAD

**Issue by PasDeBol** [nielsfaber/scheduler-component#149]
### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [X ] My request is generic, other users may benefit from it too.

### Proposal
scheduler.edit need all required parameters (as scheduler.add) but if scheduler.edit accept and modify only parameters to be change (the others keep sames values) it could be more easy to make modifications on scheduler.

### Additional info
I need to change only weekdays but i must send the timeslots (not easy to get current values). Ok, it's easy to do it from card but several calendars must be modified. It's a problem of workday or not, but module workday can't be change easy too.

**Comment by nielsfaber** [comment]
I will see what I can do.

**Comment by nielsfaber** [comment]
This is added in v3.2.4 which is just released. Hope you like it.
Please test if it fits your needs, and close this request if so (otherwise please let me know).

**Comment by PasDeBol** [comment]
sorry,

 i haven't tested yet but thank you because i will need it
