### ISSUE TITLE
Include other domain types.

### ISSUE THREAD

**Issue by kineticscreen** [nielsfaber/scheduler-component#15]
Helpers, specifically input_boolean to show up as switches.

Would also be good to have automations and scripts available to be scheduled.

**Comment by nielsfaber** [comment]
I think this is very user depending.
In my config i have some input_booleans, but these don’t trigger actual devices, so I wouldn’t want to schedule them.
You know that you can already add the input_boolean, script and automation entities (or domain) in the card configuration right?

**Comment by kineticscreen** [comment]
Ohhh I didn't realise. I might be an idiot, or it's not clear in the documentation. I was trying to add them to the 'switch' domain. It's not super clear that any domain in HA is available, outside of the 4 default ones.
