### ISSUE TITLE
Thermostat behaviour based on temp not working properly

### ISSUE THREAD

**Issue by mafelipe16** [nielsfaber/scheduler-component#150]
### Checklist
DOne

### Expected behavior

I expect to start heating whenever the current temp is below the set temp.

### Actual behavior

In many thermostats, is still idle, even the current temp is 0,3 degrees below set temp:

<img width="553" alt="image" src="https://user-images.githubusercontent.com/64302014/142882724-c08937da-2c8e-4b14-9bd1-be296ee30f69.png">

No error logs associated.

### Steps to Reproduce

Create a simple thermostat based on a sensor and a switch.

Create a Heating Set Temperature schedule with the Scheduler component, wait till current temp raises above set temp or wait till current temp goes below the set temp.

**Comment by nielsfaber** [comment]
This is behaviour of your thermostat, not scheduler

**Comment by mafelipe16** [comment]
Sorry for opening the issue, my error was not setting the generic_thermostat values correctly.
