### ISSUE TITLE
Skip next occurence

### ISSUE THREAD

**Issue by earion68** [nielsfaber/scheduler-component#152]
First, thanks a lot for this incredibly-powerful custom component, that definitely deserves to be integrated in core someday!

### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I am using the scheduler component to schedule alarm clocks. I would love a feature that would be able to "skip the next occurence", without disabling the schedule, for the days I am too lazy to wake up :-)

I believe this feature could be used in other use cases as well.

### Additional info
It's important that the scheduler entity does not get disabled, but only skips the action for the next occurence.
Skipping next occurence should be cancellable, and we should know in scheduler entity's attributes that the next occurence is skipped.

**Comment by nielsfaber** [comment]
For me it is quite doable to add this feature to the component.
However I don't know how to integrate it in the card.
Are you just looking for a service to be able to do this, or a button you can click in the card?

**Comment by earion68** [comment]
Thanks for your reply!

Just a service would be fine already very useful for my purpose - need to find a way to get the very next scheduled item as I have multiple schedules as alarm clocks anyway.

Of course a button on the card would be amazing but I see your point, it's not easy to find the right place for it... I'd say ideally next to the on/off button. 

![image](https://user-images.githubusercontent.com/54678154/144714989-e63ca73c-f43d-4f81-9ae0-503cfaea5805.png)

**Comment by earion68** [comment]
Ho no, please bot, reopen it

**Comment by wacsy** [comment]
May I ask if this feature been added, please? I didn't manage to find it in the Actions with version 3.3.8. Thank you very much. I wonding if I can do this:
1. create a template sensor the monitoring the number settings for a heater
2. if the number changed then check if the next scheduler of the heater temperature change is within 1 hour (or any given time duration)
3. If the next occurence is too soon (within the given duration) then skip it.
