### ISSUE TITLE
Condition enhancement

### ISSUE THREAD

**Issue by tane64** [nielsfaber/scheduler-component#155]
### Proposal
[set the temperature in a room to: Night 18, day 14, evening 16. When PS4 consumption > 40 watt in a selected time frame set heating to 20.  When PS4 consumption <10 watt set heating back to the previous setting.]

**Comment by nielsfaber** [comment]
I don't think this should be added.
What you are describing seems more like a standard automation, and goes too far to integrate with scheduler (the behaviour is not time-based but more sensor based).
If you really want to accomplish this behaviour, you could create 2 schedules, one with condition `consumption > 40` and the other for `consumption < 40`.
There should be always one active and one inactive.
There is a `scheduler.copy` service which can be used for duplication.
