### ISSUE TITLE
"Re-evaluate conditions when conditions change" reevaluates all the time

### ISSUE THREAD

**Issue by haseat** [nielsfaber/scheduler-component#156]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.0

### Component Version

v3.2.4

### Bug description

"Re-evaluate conditions when conditions change" reevaluates the conditions all the time, which makes it impossible to manually adjust the temperature on my thermostats anymore.

You can find a screencast of the behavior here:
https://watch.screencastify.com/v/gni96so73yBJo3kqZANA

IMO the correct behavior would be to only reevaluate all the schedules when the conditions actually change.

### Steps to reproduce

see video above :-)

**Comment by nielsfaber** [comment]
> IMO the correct behavior would be to only reevaluate all the schedules when the conditions actually change.

Agreed! Apparently I made scheduler became a bit stubborn, that was not my intention.
I must have overlooked this scenario in my own tests, will work a fix in the mean time.

I guess its better to leave that checkbox unticked for now 😅 

BTW: Thanks for the video! I wish all bug reports came with this, makes life much easier.

**Comment by haseat** [comment]
If you need help testing (in general, not only for this bug) let me know, I'd be happy to help.

**Comment by wormiedk** [comment]
Where do I find the re-evaluate option?

**Comment by nielsfaber** [comment]
This should be fixed by updating to v3.2.5.
Could you please test it and close the issue if it is indeed fixed (let me know if otherwise)?

**Comment by haseat** [comment]
Tested and works for me 👍. Thanks!

**Comment by sven337** [comment]
@nielsfaber for what it's worth, I see this bug at the moment on 3.2.15. Might it have regressed?
Thanks
