### ISSUE TITLE
Naming a schedule

### ISSUE THREAD

**Issue by xyzo** [nielsfaber/scheduler-component#159]
It would be neat if you could name a schedule in its settings. That way you could more easy find a specific set schedule on the lovelace dashboard instead of opening each one up.

**Comment by nielsfaber** [comment]
This is already the case

**Comment by xyzo** [comment]
Seems that I'm too stupid or it's not quite obvious how to achieve it. I again checked into it and I can't find a way how I could name a specific schedule somehow.

**Comment by xyzo** [comment]
<img width="414" alt="Bildschirmfoto 2021-12-17 um 14 43 25" src="https://user-images.githubusercontent.com/2518490/146553426-a5810938-2330-4f4a-a821-35676c511d48.png">

Just to make sure... instead having something like that it would be good to see instead something like "Regular schedule" or "Extra warm schedule" instead of what I just have.

**Comment by xyzo** [comment]
It wasn't obvious enough for me... I now found it. Sorry!
