### ISSUE TITLE
Install via HACS fails to create services

### ISSUE THREAD

**Issue by kineticscreen** [nielsfaber/scheduler-component#16]
Having installed both the integration and lovelace card via HACS, the following error is reported when trying to add an item:

![image](https://user-images.githubusercontent.com/39250334/92687018-1ca18e00-f37e-11ea-8d5b-514a83beef8f.png)

Checking in developer tools and none of the "scheduler.*" services are present on the system.

Using Hassio 0.144.4 on a Raspberry Pi 3B+

**Comment by nielsfaber** [comment]
It means you don’t have the scheduler-component installed.
After placing the files in custom_components a reboot is needed.
Then it should be added to the HA “integrations”.

**Comment by kineticscreen** [comment]
No, it was installed. And I just tried reinstalling it via the Integrations pane and restarting, but it still hasn't generated those services.

![image](https://user-images.githubusercontent.com/39250334/92688640-0a751f00-f381-11ea-8cf8-35d775cd7d2b.png)

**Comment by nielsfaber** [comment]
HACS only installs the files.
You still need to set up the integration in HA itself.
It’s in configuration -> integrations.
If you have zwave/zigbee/mqtt or something, you probably know this view already.

**Comment by kineticscreen** [comment]
Damnit. Thanks.

**Comment by anarro** [comment]
Hi,

I have the same problem, but I haven't the sheduler-component in the configuration -> integrations.


This pictures are after restart HA.
![image](https://user-images.githubusercontent.com/8436433/92720039-5cf41280-f364-11ea-8792-cd343c48c057.png)


![image](https://user-images.githubusercontent.com/8436433/92720001-48b01580-f364-11ea-875c-34d74e5cc72b.png)

**Comment by GianCann** [comment]
I haved install the integration with HACS (the file of custom components are present on the custom_components folder) when I go into Integration > Add, I don't find Scheduler service.
I haved restart HA.
Sun integration is running.
What else I have to do?

(HA version is 115.3, on Raspberry with Rasbian Buster OS)

**Comment by nielsfaber** [comment]
@GianCann  It sounds silly, but many users have fixed this problem by refreshing their browser cache or opening HA in a private mode browser tab.
I would try that.

**Comment by GianCann** [comment]
Ok, thank you. Browsing with "private mode" show the integration...

Thank you very much for the fast reply ;)
