### ISSUE TITLE
Add scheduler.get service to batch edit schedules

### ISSUE THREAD

**Issue by 3v1n0** [nielsfaber/scheduler-component#161]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal

`schedule.edit` allows to programmatically edit schedules, however it's not possible to get the current schedule data model in the same structure that schedule.edit support.

**Comment by nielsfaber** [comment]
Your request is completely unclear to me. Please elaborate.

**Comment by 3v1n0** [comment]
So.... I want to be able to edit a previously set schedule by fetching the schedule current configuration (in the same yaml format I need to setup), modifying few bits, and send it back with `schedule.edit`

**Comment by nielsfaber** [comment]
As far as I know, the services can only be used to send data to HA, not for getting data.
I think what you are hinting at is a limitation of HA, so I wouldn’t know how to help you.

**Comment by 3v1n0** [comment]
Maybe can be emitted a specific event as reply containing such data?

**Comment by nielsfaber** [comment]
I don't see this feasible.
