### ISSUE TITLE
Different schedules for workdays and weekends

### ISSUE THREAD

**Issue by Kaibob2** [nielsfaber/scheduler-component#162]
### Checklist
- X I checked for similar existing requests (both open and closed) before posting.
- X My request is generic, other users may benefit from it too.

### Proposal
It would be great, if it would be possible to have different schedules for weekdays and weekends. 
I use the integration for 7 climate and 7 cover entities. Both groups require a workday and a weekend schedule which differ in the timeslots for on and off, temperatures or closing state.
Currently i work around this problem by having one scheduler card for workdays and one for weekends. This is very chaotic as each card has 7 entities in it. 
Solution:
Additional option "week" beside daily, workday, weekend and select.
When week is selected there are two timeslot bars, one for weekdays, one for weekends.

### Additional info
I think this is kinda standard scenario and many users might be in the same situation.
Beside that: Absolutely great integartion! I love it and have no idea why this or something similar isn't integrated into Core.
Keep up the good work and all the best for 2022.

**Comment by nielsfaber** [comment]
Are you aware that you can create a single schedule for controlling multiple devices?
There is no need for having 2x7 schedules for 7 covers, you can reduce it to 1 for weekdays and 1 for weekends.

I’m not planning to add support for combining multiple schedules in a single schedule. 
I think this would make the card more complex than it already is.
What is so bad about having a schedule for workdays and a schedule for weekends?

**Comment by Kaibob2** [comment]
Thanks for the fast reply. I already expected, that there are no plans for doing that. :)
I'm aware that multiple entities can be combined in one schedule, but all covers open (and close) at different times. The heaters as well. This makes it necessary to have 7 heater schedules for weekdays and 7 for weekends. If, like right now, it's holiday time I would in fact need a third schedule with all heaters which is set to "daily". I circumvent this by changing the weekend schedule to "daily" which is fine, as it happens not that often that the whole family has holidays together.
Anyway, I just wanted to let you know that there might be a need for something like this.
All the best.
