### ISSUE TITLE
Do not trigger timeslot action if it's like the previous one

### ISSUE THREAD

**Issue by julienlarivee** [nielsfaber/scheduler-component#163]
### Checklist
- [ x] I checked for similar existing requests (both open and closed) before posting.
- [ x] My request is generic, other users may benefit from it too.

### Proposal
I would like to propose to add a check to see if the last triggered timeslot is the same (entities, action, action variable) as the one currently triggered. If so, do not trigger the current timeslot action.

### Additional info
The reason I propose this feature is that I have some schemes for thermostats that span on two days.
One of them is that I would like to reduce the heating for the night at 1h30 in the morning.
To do this, I set three timeslots:
   - 0h to 1h30 at 22C
   - 1h30 to 7h30 at 18C
   - 7h30 to 24h at 22C
![image](https://user-images.githubusercontent.com/55027006/147880214-af1a5c61-89ae-4f09-9294-34af50b0f810.png)

The problem comes when I manually change the temperature during that period.

Exemple: Lets say it's 22h, the temperature is 22C and we start to get cold. I manually change the temperature to 23C. At midnight, since we are changing of timeslot, the temp will be set again at 22C, wich is not what we want. But if the scheme would have remembered that the last timeslot was like the new one and not triggered, it would had caused no harm.

By the way I would like to thank you for your amazing component and card. It's exactly what home assistant was missing! :)

**Comment by nielsfaber** [comment]
Are you specifically referring to the crossing of midnight (00:00)?
Or are you proposing that scheduler should _always_ skip the second slot in case two adjacent timeslots have the same action?

BTW: there is a request for a 'skip next' feature, see https://github.com/nielsfaber/scheduler-component/issues/152. It might be a solution for you as well.

**Comment by julienlarivee** [comment]
I think it should always skip.

I got another use case to illustrate this.
I have a guest mode for the thermostat too. It's setting the temperature to 22C all the time. I still use a scheme for this, because when the input boolean guest is switched to on, the scheme is immediatly triggered. I don't have to wait for a certain hour before it is triggered. That being said, a scheme can't have only one timeslot, so I created two with the same temperature. This bring us to the same problem as before that is if the guests are changing the temperature, they wouldn't want it to be changed by the timeslot during the day.
![image](https://user-images.githubusercontent.com/55027006/147991920-e7571ce3-2cd8-4516-9e3e-8abc27d3cf3c.png)

I know this automation can be simply created in yaml, but it was to demonstrate that I think it should always skip.

**Comment by nielsfaber** [comment]
I will try to implement something to prevent the repeating of the action at '00:00'.

> I think it should always skip.

I don't agree with you on this. There is no need for creating multiple timeslots with the same action, so if it is configured like this, it is done by choice.

> It's setting the temperature to 22C all the time. I still use a scheme for this, because when the input boolean guest is switched to on, the scheme is immediatly triggered. I don't have to wait for a certain hour before it is triggered.

Your example doesn't seem valid to me. A schedule which has always the same action has no use. If it's not supposed to act on certain time(s), it is not a schedule but a regular automation. You are abusing the re-evaluation of changing conditions.

> That being said, a scheme can't have only one timeslot

If you leave timeslots empty (no action assigned), they will not be stored. A schedule with a single timeslot is allowed (but yes, it cannot stretch to later than '00:00').

**Comment by julienlarivee** [comment]
@nielsfaber I agree. Thank you
