### ISSUE TITLE
Feature request: Fire Event on entity creation

### ISSUE THREAD

**Issue by mrschweizer** [nielsfaber/scheduler-component#169]
If there was an event on the creation of an entity, you could use that to spawn further events with relative times.

E.g.: Once the alarm for the next morning is set, create a schedule to dimm the lights 8 hours before that.

Of course, a direct implementation of relative triggers would also work.

**Comment by calisro** [comment]
You could just create an automation to listen to the event bus for entity_registry_updated for whatever you wanted and fire a schedule based on it.  

{
    "event_type": "entity_registry_updated",
    "data": {
        "action": "create",
        "entity_id": "switch.schedule_673f9e"
    },
    "origin": "LOCAL",
    "time_fired": "2022-02-08T16:42:09.888017+00:00",
    "context": {
        "id": "7423832767e13146b95e00c2436659c5",
        "parent_id": null,
        "user_id": null
    }
}
