### ISSUE TITLE
Using other entities for time and day

### ISSUE THREAD

**Issue by fuatakgun** [nielsfaber/scheduler-component#173]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
First of all, thanks a lot for this great integration, i have replaced many of my automations with this.

I would like to have 2 feature request;
- using sensor or input helper for time fields, similar to automations (fixed time or variable)
- using binary sensor (workday/vacation day) to decide which days should be executed

### Additional info
Please let me know if you need more information

**Comment by nielsfaber** [comment]
> using sensor or input helper for time fields, similar to automations (fixed time or variable)

I'm not sure what you mean by this.

> using binary sensor (workday/vacation day) to decide which days should be executed

This is already in place. Scheduler works with the [workday integration](https://www.home-assistant.io/integrations/workday/) to distinguish between workday and weekend day (holidays count as weekend).
Also you can assign conditions based on binary sensor states

**Comment by fuatakgun** [comment]
ops, I missed to reply this, sorry.
I have an additional calendar setup to fetch school vacations and set up a binary sensor on it.
So, I would like to execute the events if the day is workday and school vacation. (using binary sensor to decide on the days)

Moreover, I have some events to be triggered by 07:30 or 08:00 depending on school vacation. (using sensors or input helpers for event time)
