### ISSUE TITLE
Sun Times

### ISSUE THREAD

**Issue by PierreScerri** [nielsfaber/scheduler-component#18]
Hi
I can make lights go off at sunrise.
How can I make lights go on at sunset?

**Comment by nielsfaber** [comment]
Currently the only way is by setting the time you like (if you know your local sunset time, set it to this time) and then set the checkbox ‘adjust to sunrise/sunset’.
The scheduler will automatically calculate the offset from your local sunset/sunrise time (whichever is closest to the time you set) and make sure the time will remain relative to this.
In a future update you will be able to set the offset from sunrise/sunset yourself.

**Comment by PierreScerri** [comment]
Actually I cannot even set it for Sunrise.

Setting:
![Screenshot 2020-09-12 at 15 58 58](https://user-images.githubusercontent.com/34303331/92997124-2f000100-f511-11ea-8bee-0198e6cfb5ed.png)

and

![Screenshot 2020-09-12 at 16 00 23](https://user-images.githubusercontent.com/34303331/92997126-31625b00-f511-11ea-8d66-2d78ad6fe846.png)

gives

![Screenshot 2020-09-12 at 16 00 34](https://user-images.githubusercontent.com/34303331/92997130-345d4b80-f511-11ea-90ef-ba893853e71b.png)

Sunrise/Sunset change every day.
The sunset one is setting UTC time.

This is all wrong.

Or I have not understood how it is working.

**Comment by nielsfaber** [comment]
Well, from what I can see sunrise is at about 6:40 and sunset around 19:15 in your location.
This is info is taken from your HA config.
The idea is that when you check in a week or so, the times will be slightly different.
If the times are totally off from the actual sunrise/sunset times, then you should check the location data in HA.
All seems to be as it should be from what I can see

**Comment by PierreScerri** [comment]
Ok I’ll see how it goes.

**Comment by nielsfaber** [comment]
There is a new update of the scheduler-card that gives you better control of choosing time with sunset and sunrise.
Please read about it [here](https://github.com/nielsfaber/scheduler-card#choosing-the-time).
I'm closing this issue, assuming you will be able to work with it 😉
