### ISSUE TITLE
Scheduler Copy Doesn't duplicate tag

### ISSUE THREAD

**Issue by calisro** [nielsfaber/scheduler-component#180]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
When we execute the scheduler.copy, i'd expect everything but the name to be duplicated. Can the tags also be copied please?  We can go and manually update the tags but since I have filters in the lovelace for specific tags, I won't see the new copied schedule in the right place and need to remove the lovelace filter tags, adjust the tag for the schedule, and then re-apply the lovelace tag filtering.

### Actual behavior
All seems duplicated except the tags

### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by calisro** [comment]
Not stale

**Comment by nielsfaber** [comment]
This should be fixed in v3.2.8.
