### ISSUE TITLE
Conditions only work once

### ISSUE THREAD

**Issue by redlegoman** [nielsfaber/scheduler-component#186]
I'm not sure if this a "bug" or whether the scheduler just doesn't work the way I expect it to.
I have a schedule setup to turn on a light in the morning and turn it off in the evening as a "scheme".
I added a condition so that the light doesn't turn on when a certain window is open (binary_sensor).  I have "re-evaluate" checked.

If the window is open when the schedule "on" period starts the light doesn't turn on. Which is good. As expected.
If I close the window during the "on" period, the light turns on. Also good. As expected.

Here's where it doesn't do what I expect:
If I now open the window _again_ during the "on" period the light stays on. I would have expected the light to turn off. From this point on, opening and closing the window makes no difference to the light. 

Is that how it is supposed to work?

**Comment by nielsfaber** [comment]
> If I now open the window again during the "on" period the light stays on. I would have expected the light to turn off. 

I don’t quite follow your expectation here.
If the timeslot has action ”turn on”, the schedule will never decide to do a “turn off” on its own.

I do agree that a change conditions should be able to repeat the scheduled action, i.e. if you would manually turn the light off after the schedule turned it on, closing the window would cause the light to be turned on once again.
I’m not sure if this currently is the case. The ‘re-evaluate’ check mark is quite a new addition.

**Comment by redlegoman** [comment]
> I do agree that a change conditions should be able to repeat the scheduled action, i.e. if you would manually turn the light off after the schedule turned it on, closing the window would cause the light to be turned on once again. I’m not sure if this currently is the case. The ‘re-evaluate’ check mark is quite a new addition.

Ok, fair enough about the turn off thing. I haven't tried manually turning off the light and seeing if it comes back on. I will try it and see what happens.
