### ISSUE TITLE
Workday Integration doesn't detect days off from Country and/or Manually Added Days

### ISSUE THREAD

**Issue by pcampan** [nielsfaber/scheduler-component#187]
### Checklist
Running 2022.2 at the time of reporting

### Expected behavior
[What you expected to happen]
The integration with workday doesn't seem to be functioning properly.

For holidays manually added or determined by location, the non-weekday schedule should be triggered.

### Actual behavior
[What actually happened]

For holidays manually added or determined by location, the weekday schedule is being triggered.

### Steps to Reproduce
See https://community.home-assistant.io/t/scheduler-card-custom-component/217458/1594

**Comment by nielsfaber** [comment]
I created some test scenario to reproduce this bug.
This schedule turns on an input boolean 'scheduler test', from 08:00 AM to 16:00 PM, but only on the weekend.

<img src="https://user-images.githubusercontent.com/16861605/156913020-bd16c881-3e2d-4d11-ab1c-35a7f8136579.png" width="75%" height="75%">

I disabled the workday sensor, instead I made a template entity which I can control through an input boolean (toggle switch on  -> workday sensor on, and vice versa):
<img src="https://user-images.githubusercontent.com/16861605/156913071-8f6f3d0a-2052-4fb4-aed9-4790d50624d1.png" width="75%" height="75%">

What I am observing is that:
* In case 'workday sensor' is OFF (i.e. its weekend or holiday) and I turn on the schedule, the 'scheduler test' input boolean is turned on.
* In case 'workday sensor' is ON  (i.e. its a working day) and I turn on the schedule, the 'scheduler test' input boolean is NOT turned on.

Similarly, if I edit the schedule to trigger on workdays, the result is the opposite.

This behaviour looks exactly as I would expect it, so I'm unable to reproduce your bug.

As a second test I will configure the 'real' workday sensor with tomorrow as holiday and see if the schedule triggers, I will share the results when I can.

**Comment by nielsfaber** [comment]
For completeness, here's my workday sensor configuration:
```yaml
binary_sensor:
  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - "2022-03-06" # tomorrow
```

The schedule currently is set for next saturday:
![image](https://user-images.githubusercontent.com/16861605/156913368-cab89a41-0f84-472f-8797-e8435cac6981.png)
I am expecting this to change to tomorrow morning (the workday sensor changes state around midnight).

The 'scheduler test' input boolean is now OFF, it should turn ON at 08:00 AM tomorrow.

**Comment by pcampan** [comment]
Appreciate your effort into looking into this!

Regarding you configuring Sunday (22/3/6) manually as a holiday, Saturday
and Sunday always work for me as non-weekday.

A suggestion is to manually set Monday as a non-workday.

**Comment by nielsfaber** [comment]
Yes I agree, I intended to set it for tomorrow, changed it now to 22/3/7.

**Comment by nielsfaber** [comment]
My schedule did not trigger this morning, it is still scheduled for next saturday.
The reason is that the scheduler is watching for updates in the workday sensor and reschedules when it changes.
Since yesterday the workday sensor was OFF (sunday=weekend) and today the workday sensor is still OFF (today=holiday) there was no state change, hence nothing rescheduled.
I didn't see this before, I think I have to make modifications to check the sensor at the start of every day, also in case the state didn't change.
This problem seems to affect only situations where a weekend is followed by a holiday.
Does this match with the problems you are experiencing?
From:
> For holidays manually added or determined by location, the weekday schedule is being triggered.

It seems you are seeing different behaviour, which I didn't see with my test, but also not likely fix by adding a daily workday sensor 'refresh'.

**Comment by pcampan** [comment]
I believe so, many of the holidays that I added followed weekends.  The
original scenario  "2022-02-21" that I called out, was a Monday.

**Comment by pcampan** [comment]
I believe that 2022-02-21 was a holiday as defined where I live, but I
didn't test this scenario because I also added it manually.

**Comment by pcampan** [comment]
Let me make sure there is no ambiguity with my case that I was testing.

I had scheduled a workday schedule.  I had expected 2022-02-21 as both a holiday and explicitly stated as an "add_holiday" to not trigger a workday schedule, but it did.

Possibly the schedule isn't noticing that the workday was set to off for a workday on (22/02/21), so the daily check of whether the workday sensor was off will fix the issue?

**Comment by nielsfaber** [comment]
I will add a second test where I make Wednesday being ‘weekend’ and Thursday a holiday, with a schedule which is supposed to trigger on workdays only.

**Comment by nielsfaber** [comment]
I can hereby confirm it triggered on Thursday. 
I will add the daily refresh function when I find the time for it, and run the same tests to verify the fix. I will report when this is done.

**Comment by pcampan** [comment]
Thanks for your efforts!

**Comment by nielsfaber** [comment]
In the meantime I made the following changes:
- Every day at 00:05 AM a timer will trigger the re-evaluation of all schedules which are configured for workdays/weekends
- The timer is postponed to the next day in case the workday sensor changes state (this changes at 00:00 - 00:01 AM), this also triggers re-evaluation (was already in place)

To test the changes, I am modifying the workday sensor such that:
- Today March 22 + tomorrow March 23 is weekend
- Thursday March 24 is a holiday
Let's see what happens..

**Comment by nielsfaber** [comment]
The test was succesful, the schedule from https://github.com/nielsfaber/scheduler-component/issues/187#issuecomment-1059910220 did trigger this morning, which was configured as holiday, coming from a weekend.
From the logs I can see that the schedule initially was set for next saturday (weekend), and at 00:05 it was re-scheduled to this morning. The daily timer has the desired effect, and should overcome the issue you reported.
I will let you know when this change is released.

**Comment by pcampan** [comment]
Thanks very much for your hard work on this solution and on the component.
It is very well done!

**Comment by nielsfaber** [comment]
This is added in the v3.2.8 release.
I assume all will work well for you from now on, if this is not the case please let me know.

**Comment by pcampan** [comment]
Appreciate your help!

**Comment by pcampan** [comment]
Home Assistant 2022.3.8
scheduler-component 3.2.8

I setup today as a **holiday** and was expecting my **weekday** schedules not to trigger however they **did trigger**.

- platform: workday
  name: workday
  country: CA
  province: "ON"
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  add_holidays:
    - "2022-03-30"

<img width="734" alt="2022-03-30_7-22-04" src="https://user-images.githubusercontent.com/47342107/160823659-ffbb620f-ef35-442f-8eaa-fe6294959038.png">

**Comment by nielsfaber** [comment]
What a sadness!
I thought all was OK now, apparently I judged it too quickly.
I will set up a local test similar to yours (for next tuesday), so I can take look as well.
If possible, could you check the history of the binary_sensor.workday entity and see at which time the on->off transitions occur?
For me they occurred at  12:00 AM, therefore I programmed the daily check to occur at 12:05 AM. Maybe this timing is region dependent (I couldn't find any documentation on this though).

**Comment by pcampan** [comment]
I am in information technology as well and understand totally that these things happen!

I have more examples if you need but here are some examples 

<img width="1714" alt="2022-04-01_7-06-48" src="https://user-images.githubusercontent.com/47342107/161252571-2565665a-e15c-40c1-9a20-efed2cceba2d.png">
<img width="1713" alt="2022-04-01_7-09-46" src="https://user-images.githubusercontent.com/47342107/161252574-35646d8c-733d-479c-a8d1-86c21c2dc85c.png">
<img width="1709" alt="2022-04-01_7-09-19" src="https://user-images.githubusercontent.com/47342107/161252576-40285868-29f0-423d-bb62-e438728199b3.png">
<img width="1702" alt="2022-04-01_7-08-50" src="https://user-images.githubusercontent.com/47342107/161252577-e2442ae6-7630-4765-8351-69d1107fb9fb.png">
<img width="1711" alt="2022-04-01_7-07-31" src="https://user-images.githubusercontent.com/47342107/161252578-e87c7d9b-3e05-4afc-923f-b55c87b0b25f.png">

**Comment by pcampan** [comment]
FYI - I setup March 4, 2022 as a holiday and all of my Workday automations triggered on Monday March 4 ...

- platform: workday
  name: workday
  country: CA
  province: "ON"
  workdays: [mon, tue, wed, thu, fri]
  excludes: [sat, sun, holiday]
  add_holidays:
    - "2022-04-04"

![image](https://user-images.githubusercontent.com/47342107/161644388-8ff2076b-6064-4fe0-8820-0bd05473f97f.png)

**Comment by nielsfaber** [comment]
My own test passed this morning.
The schedule was configured to trigger on working days. Today (April 5th) was configured as a holiday.

The relevant logs:
> 2022-04-04 23:59:59 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7de92c set for 2022-04-05 08:00:00+02:00,
2022-04-05 00:00:08 DEBUG (MainThread) [custom_components.scheduler] Workday sensor has updated,
2022-04-05 00:00:08 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 7de92c set for 2022-04-06 08:00:00+02:00

So the item was initially scheduled for today April 5th, but on 00:00:08 the workday sensor updated (to OFF) and the item was postponed to April 6th.

Workday sensor configuration:
```
binary_sensor:
  - platform: workday
    country: NL
    workdays: [mon, tue, wed, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - "2022-04-05"
```

At this point i'm a bit clueless what the differences are between our tests.
In this particular scenario there was an ON->OFF transition for the workday sensor, which should have worked even before the changes I added.

**Comment by pcampan** [comment]
I thought perhaps it was due to my schedules being created many months ago and yours maybe being created adhoc for testing that might be contributing to the difference in our testing results.  I tried it today on one schedule but it still triggered, unfortunately.

**Comment by pcampan** [comment]
I really appreciate your help and effort!
