### ISSUE TITLE
Failed to call service scheduler/add

### ISSUE THREAD

**Issue by Hynack** [nielsfaber/scheduler-component#19]
After installing everything as per the guide (HACS > Reboot > Add to Integrations > Add card) the card displays correctly, I can select my entities, pick an action, a time, ... but when clicking on the final save, I get the error 'Faciled to call service scheduler/add. Service does not exists!'

I have already tried to reinstall everything with no luck.

**Comment by nielsfaber** [comment]
Sad to hear you run into problems.
I must say a lot of people have similar issues so I think i should make efforts to improve things.
What is clear to me is that the card is installed fine, but you still need to install the scheduler-component (which keeps track of the timers).

If HACS did it’s job fine you should see a folder `scheduler` inside `custom_components`.
If this is not the case then there is a problem with HACS, maybe it’s best to download the files directly through GitHub.

If the files are in place, you should do a reboot of HA. After this, go to ‘configuration’ and then ‘integrations’. Click the big + at the bottom and look for ‘scheduler integration’. Select it and confirm. 

After this step the integration should be installed, on the integrations page you should see an icon with ‘1 device’ and ‘0 entities’. If so, you are good to go.

Please let me know in which step things are failing for you.

**Comment by Hynack** [comment]
I have confirmed I have the right folders, and the integration is shiowing in the list and allows me to install, but it doesn't say '1 device and 0 entities'. Its just blank

**Comment by nielsfaber** [comment]
Can you tell me which version of HA you are using?

**Comment by Hynack** [comment]
Ok I fixed the issue, here is how to help others:

You MUST have the sun: integration running!

**Comment by nielsfaber** [comment]
Ah wow! 
Nice that you found that out.
It makes sense now, with your problem description. I guess you saw it in the HA log.
Case may be closed for you, but I will make work of this.
- For now I will add a note in the readme 
- for later I will either make sun.sun optional (hiding sunset option) Or include a check in the card
Thanks for your input!

**Comment by frozendevl** [comment]
For anyone else just installing the scheduler-component and Lovelace card through HACS and running into this issue, make sure to go to Integrations and setup the Scheduler there as well. That immediately fixed me issue (thanks nielsfaber!).

**Comment by gajewsky** [comment]
I am experiencing the same issue, I made sure I have sun integration, I installed both `scheduler-component` and `scheduler-card` and each time I am trying to add schedule I am getting:

```
Failed to call service scheduler/add. Service not found.
```

I also dont see any of scheduler services in developers tools

**Comment by nielsfaber** [comment]
@gajewsky Please go to configuration -> integrations in HA and tell us if ‘Scheduler integration’ is there. It should show 1 device / 0 entities under it.

**Comment by gajewsky** [comment]
@nielsfaber thank you for lightning fast response :) the integration was there at the first place. The problem occurred to be outdated version of HA. I updated it to `0.114.4` reinstalled both `scheduler-component` and `scheduler-card` same way I did first time and everything worked this time :)

**Comment by nielsfaber** [comment]
@gajewsky good to hear that you fixed it! I had no idea that you had to run latest HA version.
Looking back in the HA changelog i see that the integrations page was added in 0.109 so would assume any version above that _should_ work. 
Curious where it went wrong exactly, but I am too busy to really dive itno it.
Thanks for the feedback, i will take it into account when someone else has troubles.
