### ISSUE TITLE
Random Start / End Offsets for schedules

### ISSUE THREAD

**Issue by c-scoot** [nielsfaber/scheduler-component#190]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
It would be great if we could set a random Start or End offset for schedules - this would help using scheduler for security i.e - turning lights on and off whilst away. Would it be possible to have an offset in minutes. So that the start time is x, plus a random offset up to the value you specify. For example: Turn the light on at 8pm with a random offset of 30 minutes. The light would therefore turn on anywhere between 20:00 and 20:30

### Additional info
Add a check box enabling the offset with a minutes picker.

**Comment by nielsfaber** [comment]
This has been requested many times before.
I think this will overcomplicate the scheduler and very user-specific feature, I don't think it is a good addition.
You may be able to achieve this goal by triggering a script from scheduler, which implements a random waiting time and then executes a service.
