### ISSUE TITLE
Version 3.2.7 is broken in HA 2022.4, but 3.2.8 is not tagged as a release

### ISSUE THREAD

**Issue by bdr99** [nielsfaber/scheduler-component#192]
Version 3.2.7 of scheduler-component is broken in HA 2022.4, and I cannot update to 3.2.8 through HACS because it is not tagged as a release. Please tag version 3.2.8 as a release in GitHub so that users who installed scheduler-component through HACS can update to 3.2.8.

![image](https://user-images.githubusercontent.com/2292715/162029544-40327dfa-f201-4802-b173-3e4d2f6e0af5.png)

### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [ ] I am running the latest version.

### Expected behavior
HACS should show the latest version of scheduler-component

### Actual behavior
HACS shows that the latest version is 3.2.7 because 3.2.8 has not been tagged as a release.

### Steps to Reproduce
Install scheduler-component through HACS. Notice that version 3.2.8 is unavailable to be installed.

**Comment by nielsfaber** [comment]
Could you try again?

**Comment by bdr99** [comment]
It's fixed now. Thanks!

![image](https://user-images.githubusercontent.com/2292715/162031178-ae6d86b7-b71d-402f-8099-1df87b15223e.png)

**Comment by nielsfaber** [comment]
Great, thanks for reporting this! Sorry about the problem.

**Comment by jmcollin78** [comment]
Same problem for me but I don't see the update in HACS

**Comment by jmcollin78** [comment]
It is ok now. You should to HACS and not in system update to see the update.
