### ISSUE TITLE
public holiday

### ISSUE THREAD

**Issue by Micha-Btz** [nielsfaber/scheduler-component#196]
In Germany the 18.4.2022 is Easter Monday a public holiday day. 
I have created schedules for heating on Weekend and one for Mo-We. So the scheduled action in use should be Mo-We,
but even the Weekend is triggered. Maybe because of the workday sensor is off.

maybe related to https://github.com/nielsfaber/scheduler-component/issues/187

### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
only on Weekend

### Actual behavior
on weekend and public holiday.

### Steps to Reproduce
Use the Weekend possibility in the config dialog.

One Thing to note:
I'm not sure if it is a bug. As test, if I chose directly Sa/So for the days, it worked correct. 
The problem is, that both schedules are triggered. 

![2022-04-18-183018_3440x1440_scrot](https://user-images.githubusercontent.com/4420944/163840344-009ee01c-946a-4afc-b829-5c82ee3a6dda.png)

**Comment by nielsfaber** [comment]
Do you have the workday sensor running?
What is its current state?

**Comment by Micha-Btz** [comment]
Sorry, was not finished jet. Yes, workday sensor is running and off (today).

**Comment by nielsfaber** [comment]
Can you please check if you're running version 3.2.8?
You could see it in Configuration -> Devices (clicking on the scheduler device)

<img src="https://user-images.githubusercontent.com/16861605/163921193-4e515bd0-ae33-4906-8f72-10baa28c73f2.png" width="75%" height="75%">

The reason I'm asking is that the last release contains changes which should tackle a potential issue with the workday sensor (in case of a holiday right after a weekend, which seemed to be the case here).

**Comment by Micha-Btz** [comment]
yes, I'm on 3.2.8
