### ISSUE TITLE
Scheduled task to restart HA Core from automation is triggered twice whenever scheduled

### ISSUE THREAD

**Issue by lychee128** [nielsfaber/scheduler-component#202]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

2.3.4

### Component Version

3.2.9

### Bug description

I have a scheduled task to restart Home Assistant core at 5:00am each morning.  However, whenever Scheduler triggers the task, it runs twice (one repeat after the first restart).  When I disable the task, nothing runs (as expected).  I looked in the scheduler.storage file and the automation is only listed once.

However, if I delete the task from the Scheduler Card and set the automation to run at 5:00am directly from settings, it runs once as expected.

Not sure if I’m making an error but can’t find any configuration settings set incorrectly that would cause this.

### Steps to reproduce

Add task to restart Home Assistant in Scheduler Card and task is duplicated (HA restarts twice in a row).

**Comment by nielsfaber** [comment]
The only thing I could think of which could cause this, is that restarting HA takes less than a minute so scheduler is restarted at 5:00am. 
There is no (persistent) memory in scheduler regarding whether a task is already executed, so it would execute the task right away.

However, judging from this code:
https://github.com/nielsfaber/scheduler-component/blob/b683d535bed4fb49993c9adf628b66170cbcc0b0/custom_components/scheduler/timer.py#L334-L336

I would say a task should only be executed at 05:00:00, so including seconds. So when restarting HA at 05:00:40 (or similar), the next occurence would be on the next day.

Ofcourse things are completely different in case you created a time scheme, but I am assuming this is not the case.

You might want to enable debug logging for the scheduler component.
You could so by adding to `configuration.yaml`:
```
logger:
  default: warning
  logs:
    custom_components.scheduler: debug
```
And restart HA to make the change effective.

**Comment by lychee128** [comment]
Thanks for your response.  I added the logger settings as your suggested, and it does say:

2022-06-11 09:46:30 DEBUG (MainThread) [custom_components.scheduler.timer] Timer of 5b6fd5 set for 2022-06-12 09:45:00-07:00

So the automation should only run at 09:45:00.

However, my automation is definitely running twice.  In the logbook, the trace from the automation shows it's being run at 9:45:53 AM (second time):

Executed: June 11, 2022, 9:45:53 AM

I'm running HA on a Mac in a virtual machine and it restarts extremely fast (less than 60 seconds).  Could it be that the scheduler is somehow only considering 09:45 and and 09:45:00 as the trigger time?


Thanks.
