### ISSUE TITLE
Action for current timeslot is not executed on switch.turn_on

### ISSUE THREAD

**Issue by clau-bucur** [nielsfaber/scheduler-component#203]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]
When a schedule is enabled (switch entity turned on) the action for the timeslot that is currently active should be executed, in order to ensure the schedule is operating correctly.
 
### Actual behavior
[What actually happened]
Right after the schedule is triggered, if the schedule is turned off, then is turned on again, the action of the current timeslot is executed correctly.
However, if some minutes pass, turning off and then turning on the schedule switch, will not execute the action. Even though that timeslot is active.

### Steps to Reproduce
[Explain how to see the behaviour]
![HAScheduler](https://user-images.githubusercontent.com/47672949/172580690-51e9428a-a771-41b3-87ff-5ecd03418a1a.gif)

**Comment by clau-bucur** [comment]
Not stale.

**Comment by clau-bucur** [comment]
Not fixed.

**Comment by nielsfaber** [comment]
Sorry for not responding to this issue before. I haven't been very active with this project lately.

I don't really understand the issue you are pointing out.
There are no timeslots in a singular schedule, it only has one timepoint at which it is configured to act.
I would say your schedule should only do something at 11:53.
At 11:54 the action would be postponed to the next day.

**Comment by clau-bucur** [comment]
Sorry the replying late too.

I understand what you mean, and therefore my expectation was incorrect.

- When you create a singular schedule, the action will execute every day at the specified time, and that's it. My expectation was that if it's a singular scheme, it will enforce the entity state everytime. I see now that this is not how it goes and makes sense.

- When you create a schedule with a scheme, it will keep the entity in the specified state within the defined scheme interval.
