### ISSUE TITLE
Scheduler card disappears after creating schedule with scheme

### ISSUE THREAD

**Issue by cjramseyer** [nielsfaber/scheduler-component#205]
Add custom component and the scheduler card via HACS
Add scheduler card to lovelace interface configured to provide schedule for a switch for a sprinkler

### Checklist
- [X ] I checked for similar existing issues (both open and closed) before posting.
- [ ] I am running the latest version.
- [X ] I am running HA version 2022.6.7

### Expected behavior
Ability to pick multiple days and/or times to turn on/off switch for a sprinkler using create scheme option

### Actual behavior
Successfully add the lovelace card, attempted to set a schedule of Mon, Wed, Fri from 8:00 to 8:30 AM eastern using create scheme.
Once created the card disappearrs from the view, though the integration show that a schedule was created

No error displayed in the log

### Steps to Reproduce
Install custom component (integration) via HACS
Install custom component (frontend) via HACS
Add scheduler card with default options and multiple switches to via in lovelace
create schedule for 1 switch using the scheme option
choose Mon, Wes, Fri, from 8 am to 8:30am then click save

**Comment by leinelissen** [comment]
I've had this happen as well, but for me restarting Home Assistant fixed the issue for some reason...

**Comment by cjramseyer** [comment]
I can try that.  Thank you
