### ISSUE TITLE
[feature request] more complex logic in condition sets needed

### ISSUE THREAD

**Issue by bsafh** [nielsfaber/scheduler-component#209]
### Checklist
- [x ] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal
I need to configure condition sets in "options" like
a AND (NOT b) AND c AND (e OR f OR (NOT g) OR k OR r) AND NOT (h OR (NOT j))

### Additional info
real world example:

thanks a lot for this awesome scheduler component + card. I'm using it to control 16 TRV in 14 room, so it get's quite big: each room having several schedules depending on things like "I'm in homeoffice, but my wife is not", "we are both at home", it's weekend or "it's workdays" and some more (there a 4 people living here). and of course I need conditions for: don't heat when any of the windows in that room is open, and depending of the day of week and which time it is.

The scheduling itself works fine, but ...

For all these different "states" there are boolean helpers, sometimes (person.* bring there own variables) there are build-in variable.

Now the big problem: the "options" editor (and the yaml config as well, as far as I can see) only allows for combining all given option with "alle" (AND) or "one of" (OR), and you can set NOT for any condition individually.

There are no brackets ...

So, a typical condition would look like:
this schedule should be active when
- helper "vacation" is off (vacation: on means: we are all away on that day)
AND
- helper windows.room is "closed"
AND (
   - person A is at home (person.xxx = present from geolocation)
   OR
   - helper variable personBhome is true
   OR helper personAhome is true (in case geolocation fails)
)
AND 
- helper personB-homeoffice is false

So I would need both AND and OR, with ordering brackets.

Another example
(
  - person A is "home"
  OR
  - person B is home
  OR
  - helper for personAhome is true
  OR 
  - helper for personBhome is true
  OR 
  - helper for personChome is true
  OR 
  - helper for personDhome is true
)
AND 
  windows is closed
AND
  vacation is false
AND
  personBhomeoffice is false

Both the config file and the Scheduler-Card in Lovelace can use only expressions 
either like
A AND (not B) AND C AND D and (NOT E) 
or like
A OR (NOT B) OR C OR D OR (NOT E)

I can't find a way to transform the needed set of conditions to this (oversimplified?) form.

Any idea how to do that?

**Comment by bsafh** [comment]
related to [https://github.com/nielsfaber/scheduler-card/issues/604](https://github.com/nielsfaber/scheduler-card/issues/604)

**Comment by nielsfaber** [comment]
no need for requesting a feature twice.
