### ISSUE TITLE
no action triggered

### ISSUE THREAD

**Issue by mf42** [nielsfaber/scheduler-component#21]
Hi,
thanks for sharing this great project !
I just installed the Scheduler with hacs and everything seems to work fine. I defined a rule to switch a light on at 22:00 every day and saved it via Add Item. So far so good. But nothing happens at 22:00. I had a look on the nexttrigger attribut and was confused as this doesn‘t corresponds to 22:00 this day (21:30 next day??)
Any Ideas? Any chance to debug? Would love to integrate the scheduler..
Best(en Gruß),
Michael

**Comment by nielsfaber** [comment]
The `next_trigger` attribute is leading here.
In the code, it is set as soon as the timer is set, and based on the same time information.
It is safe to assume that if the `next_trigger` shows a wrong value, your timer will also fire at the wrong moment.

Please share a screenshot of the entity registry. I would like to take a look at the attributes to see if all adds up.

**Comment by mf42** [comment]
Hi
thank you for your quick reply and sorry for my delay.
The Scheduler works fine now. Strange, but I I think it had to do with HA restarts: after 2 restarts I could use the scheduler but without having it in the integration list (??). Third restart and I could find it on the list and it works pretty well now.
Thank you.

**Comment by KTibow** [comment]
Probably it was due to caching.
