### ISSUE TITLE
Scheduler next run time not respecting workday holidays/ workday holidays not working

### ISSUE THREAD

**Issue by BillyTheKid9588** [nielsfaber/scheduler-component#210]
### Checklist

- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I will participate in further discussion about this issue and can help by testing (if requested).

### Card Version

v2.3.5

### Bug description

It is a bank holiday in GB, England on 29/08/22, however the scheduler card states the next run time will be Monday.

### Steps to reproduce

workday code is defined like this;

`# Example 1 configuration.yaml entry
binary_sensor:
  - platform: workday
    country: GB
    province: England
    workdays: [mon, thu, fri]
    excludes: [sat, sun, holiday]
    add_holidays:
      - '2022-08-26'`

Created schedule Office - Heat To - 20.5, Workdays, Time 7am.

The next run time on the schedule states Monday at 7am.

If i amend my workday definition, such as below, next run time is Thursday.

# Example 1 configuration.yaml entry
binary_sensor:
  - platform: workday
    country: GB
    province: England
    workdays: [thu, fri]
    excludes: [sat, sun, holiday]

**Comment by nielsfaber** [comment]
Sorry for the late response.
I'm a bit confused by contradictive info provided, please help me clarify.

If I understand correctly you defined working days to be: mon, thu, fri.
And your schedule is configured to trigger on working days, Correct?

You state that 29/08/22 is a bank holiday, which is a Monday.
However the code you share for the workday integration mentions 26/08/2022, which is a Friday.
I assume we are talking about 29/08/22?

Did the schedule actually trigger on 29/08/22 ?
The workday sensor in HA only can tell whether the **current** day is a working day or not.
Hence scheduler cannot tell in advance (e.g. on Friday 26/08/2022) whether the next Monday will be a holiday.
However, on the day itself, around 00:00, the scheduler will re-schedule (based on the state of the binary_sensor.workday_sensor) and skip the current day.
This is a limitation of the workday integration, I don't see a way around this at this point.
