### ISSUE TITLE
Climate Domain - use value of helper for temperature picker

### ISSUE THREAD

**Issue by bluesheep** [nielsfaber/scheduler-component#213]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I have an input helper that sets a 'comfort' temperature for my radiator thermostats. Rather than pick fixed temperatures for scheduling my heating, I'd like to use that value. In the worst case, I'm able to reference that within a template. In the best case it would be a radio picker in the same manner as the automation UI.

### Additional info
None

**Comment by nielsfaber** [comment]
Scheduler does not have support for templates at this point.
It would be best to have scheduler trigger a script, and inside the script define the action for setting your thermostat(s) to the comfort temperature.

**Comment by Patbonamy** [comment]
Hello 
I reopen this because it will nice if we can use template.
Thanks for your work.

**Comment by mvzut** [comment]
+1

**Comment by Patbonamy** [comment]
> +1
> 
> It would be ideal if we can fill in something like "{{ states('input_number.away_temperature') }}" in the temperature field of a thermostat schedule

+1

**Comment by maristieuvelonde** [comment]
Still wanting this, it's really annoying to have to set the comfort/economy temperature for all the different schedules when I could just have a couple of helpers keep those states.
