### ISSUE TITLE
add even or odd week

### ISSUE THREAD

**Issue by m4sis** [nielsfaber/scheduler-component#219]
Hello,

would it be possible to add the possibility of selecting a week
even or odd week in day programming?

thank you

**Comment by nielsfaber** [comment]
Hello, I think this request is too specific. I don’t want to make the card more complex than it already is and I doubt many people will benefit from your proposal.
As alternative I propose that you create a binary sensor with a template, such that the sensor is ON when week number is even and OFF when the week number is odd.
You can include the state of this binary sensor as condition for a schedule via the card.

**Comment by m4sis** [comment]
Hello,
I did not succeed in making a binary sensor, nor even having the possibility of choosing a condition other than a group of thermostats

**Comment by nielsfaber** [comment]
Example for a template: 
```
{{ now().isocalendar()[1] % 2 == 0 }}
```

Set it up using a Template binary sensor: https://www.home-assistant.io/integrations/template/

The sensor will be ON when the weeknumber is EVEN.
You can include this sensor in the scheduler card, then it becomes available to configure as condition.
