### ISSUE TITLE
Add the ability to set the temperature in auto mode for thermal heads

### ISSUE THREAD

**Issue by iksrd** [nielsfaber/scheduler-component#223]
There are thermal heads (trv), for example TS0601_thermostat Taya, in which the heating temperature can be set in auto mode. In the existing version of the scheduler-component, there is no temperature slider in auto mode, there is only in heating mode (for these thermal heads, the valve opens at 100 in heating mode). I ask you to add such a function, quite a lot of trw manufacturers in auto mode allow you to set the temperature.

**Comment by JasonBSteele** [comment]
It looks like the temperature slider has been added to AUTO now, however, for me it is ignored. The thermostat continues to be set at the default "ambient" temperature of 16C rathe than the temperature of 20C I have set in the slider.
