### ISSUE TITLE
Scheme doesn't run

### ISSUE THREAD

**Issue by rubendediegomartinez** [nielsfaber/scheduler-component#225]
### Checklist
- [ x] I checked for similar existing issues (both open and closed) before posting.
- [x ] I am running the latest version.

### Expected behavior
I schedulled an ON-OFF cycle and Scheduller did only the ON, but not the OFF programmed for 1 minute later.

### Actual behavior
The lamp goes ON but not goes back to OFF

### Steps to Reproduce
See attached pdf file
[Doesn't-run.pdf](https://github.com/nielsfaber/scheduler-component/files/10073121/Doesn.t-run.pdf)

**Comment by xselvasx** [comment]
I have the same issue, with schema the change of state at midnight is not executed
