### ISSUE TITLE
Not possible to set temperature with mobile app

### ISSUE THREAD

**Issue by JoeAstor** [nielsfaber/scheduler-component#226]
### Checklist
- [x ] I checked for similar existing issues (both open and closed) before posting.
- [x ] I am running the latest version

### Expected behavior
Possibility to set temperature

### Actual behavior
When making a schedule, when wanthing to set temperature it always returns to 5°C.

**Comment by nielsfaber** [comment]
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/625
