### ISSUE TITLE
random on on time and fixed/random duration

### ISSUE THREAD

**Issue by wystewart** [nielsfaber/scheduler-component#228]
please consider adding capability of a random on time, with conditions supported, with a fixed duration on time or random duration and with repeat..

Would like to use this to randomly turn lights on to simulate occupancy with conditions, after sunset and before a specified time.

**Comment by stevem405** [comment]
Would love to have this.  HAI Omni panel has both and it makes programming lighting conditions while away much easier and more realistic.
