### ISSUE TITLE
Schema with do-nothing timeslots

### ISSUE THREAD

**Issue by xeor** [nielsfaber/scheduler-component#229]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Usecase
I want to control the value of an inputbox based on what time of day it is. This is what a schema is used for.
In addition, I want some of the timeslots to do nothing untill I call the `scheduler.run_action` service.

Example

* 00-06: `a`
* 06-15: `b` <-- This I want to be set by run_action
* 15-24: `c`

So, 00, it will be set to `a`, but at 06, nothing will happen until I call `run_action`. At 15, it will be `c`.

### Proposal

Create an option when adding a timeslot to schema to make it "non-automatic", ie, it is defined, but not triggered.

### Additional info
This enables some very neat functionality where you want something to normally be set, but you want some other action to decide when it should happen.

**Comment by nielsfaber** [comment]
I’m sorry for the late response.
The only way to achieve what you want is by temporarily disabling the schedule.
So from 6:00 to 15:00 the schedule switch entity has to remain disabled until you want to execute it.
I don’t have any plans for adding functionality to help your usage.
