### ISSUE TITLE
After restart HA automation is turned on

### ISSUE THREAD

**Issue by shevu** [nielsfaber/scheduler-component#23]
Step to reproduce:

1. Set schedule and turn it off
2. Turn off host: Supervisor -> System -> Host system SHUTDOWN
3. Run system again

After system run the schedule is turned on. Maybe it is not a bug? Am I missed something?

**Comment by nielsfaber** [comment]
Thanks for reporting this.
I will investigate and get back to you.

**Comment by nielsfaber** [comment]
Updating the component to [v2.0.2](https://github.com/nielsfaber/scheduler-component/releases/latest) should fix this.
Please test the update, and close the issue if the problem is fixed.

**Comment by knscusd8c** [comment]
Sorry for late answer. It is working now. Thanks.

**Comment by shevu** [comment]
Sorry for late answer. It is working now. Thanks
