### ISSUE TITLE
Add Support for Zone

### ISSUE THREAD

**Issue by AAllport** [nielsfaber/scheduler-component#231]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Add support for Zone sensors

### Additional info
Currently, it is not possible to add a condition for the `zone` sensor.
This would be helpful when wanting to add a condition that `zone.home` is occupied (>0)!

**Comment by AAllport** [comment]
Not stale

**Comment by CaptInsano** [comment]
Please reopen this issue:

I came here looking for this exact thing. I would like to run schedules on the condition of occupancy. 
This is most easily achieved via the zone.home sensor.

Could it please be added?

**Comment by f-blass** [comment]
I am also looking for this feature

**Comment by FBlass** [comment]
I am also looking for this feature
