### ISSUE TITLE
Timer unavailable in the front office

### ISSUE THREAD

**Issue by arno0392** [nielsfaber/scheduler-component#235]
### Checklist
- With the last version, schedule with start and stop date are unavailable (3.2.13) in the front end

### Expected behavior
- schedule entity is available in the front office

### Actual behavior
- front office message "defective schedule entity"

### Steps to Reproduce
- creation of a schedule entity with  a start and end date with the 3.2.13 version
- schedule is not available (error message)

**Comment by nielsfaber** [comment]
Thanks for reporting this.
I could reproduce the same problem, it was due to a change I made in the v3.2.13 release.
I made a fix for this problem and released it under v3.2.14.
Hope this fixes the issue for you as it did for me.

**Comment by arno0392** [comment]
Hi, thank you for the new release, the fix works for me.
