### ISSUE TITLE
Problems installing scheduler

### ISSUE THREAD

**Issue by EPeterE** [nielsfaber/scheduler-component#238]
Hi
I have downloaded the scheduler-component and the scheduler-card. I have restarted HA many times but each time I get the same message from the scheduler card i.e. "Could not connect with the scheduler component. It needs to be installed as integration before this card can be used."
![image](https://user-images.githubusercontent.com/22073432/209935740-a99fa793-204d-49d4-9cd1-6ac6cf346cec.png)
However the schedular component is installed in HACS, and I have installed it numerous times
![image](https://user-images.githubusercontent.com/22073432/209935961-42474b00-573c-4523-aa6a-ba335a3b5c56.png)
I have also installed the card numerous times to see if it will connect.
Can you please clarify the installation instructions
"Step 3: Add integration to HA (<--- this is a step that a lot of people forget)
In HA, go to Configuration > Integrations. In the bottom right corner, click on the big button with a '+'."
Where is the Configurations menu?? I assume it is the one in the HACS menu?

**Comment by nielsfaber** [comment]
This should be a button in the sidebar menu of HA (next to ‘developer tools’).
This is not related to HACS.

**Comment by EPeterE** [comment]
Hi
Could you show me where with a screenshot? This is what I see. Thanks for your time.
![image](https://user-images.githubusercontent.com/22073432/209970250-2f34dda6-eefb-46b2-84c7-1aac2c3c02ca.png)

**Comment by nielsfaber** [comment]
I’m out of town for a few days so I cannot share screenshots now.
What I meant is click on devices/services in the menu, then the button in the bottom and add scheduler to the installed integrations.
This is the step that you seem to be missing..

**Comment by EPeterE** [comment]
Perfect. Thank you, I now understand what you were saying. It is working
now.
