### ISSUE TITLE
Remove the 2 hour limit

### ISSUE THREAD

**Issue by giovesoft** [nielsfaber/scheduler-component#239]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
The before/after sunrise/sunset setting has a limit of 2 hour. Please remove it or at least increase it.

### Additional info
If the problem is the length of day/night in some areas, you could set the max equal to the min length of the day or night on that area.

**Comment by giovesoft** [comment]
Ping

**Comment by NH-Networks** [comment]
Already requested before and will not be added see #212 

@nielsfaber can be closed

**Comment by giovesoft** [comment]
I do not agree with closing this ticket and the #212 because the issues reported in the #212 can be solved or are not really an issue:
1. "-5 hours can be the previous day": This is not a problem because you can compare just the hh:mm part of the date and not also the day, because the sunrise/sunset are not changing a lot from a day to another so you can use the sunrise/sunset times of the previous day without any problem.

2. "begin and end time for a timeslot may become reversed": you can have the same issue with the 2 hours range like in Sweden and other countries in the north. 

3. "Additionally, scheduling a task with more than 2 hours offset is not meaningful, since the sun will be already completely up or down": this is not a problem because, for example, I want to turn off some lights during the night, I don't care if the sun is already down because I don't want to trigger the sun. 

In my opinion you could enable a bigger range without issues and then the users will arrange it based on their locations.
