### ISSUE TITLE
Selection of more than one entity is not saved correctly

### ISSUE THREAD

**Issue by FilmForge3D** [nielsfaber/scheduler-component#241]
### Expected behavior
When selecting two entities to control I would expect them to be saved. Might be just a visual bug of the UI.

### Actual behavior
The selection on the first tab of the Lovelace card gets discarded when saving or switching tabs when more than one entity is selected.

### Steps to Reproduce
Create an schedule with more than one entity selected for control (a person entity does cause this behaviour) inside the Lovelace card. The option for multiple entities does not have to be active.

### Additional Information
I first noticed this using climate entities but reproduced it using light entities. All tested entities are Zigbee2MQTT entities.

HA 2022.12.8
Scheduler Component 3.2.14
Scheduler Card 2.4.1

**Comment by 5664f** [comment]
You can work with a Work Arround.
1. select multiple entities (site "entitys").
2. be sure to choose an action (which was already set before).
3. if you now go to "Time", the selected entities will be kept.
