### ISSUE TITLE
Temperature reset to 10

### ISSUE THREAD

**Issue by rploeg** [nielsfaber/scheduler-component#243]
Hi,

I have tested this on Edge and Chrome. But when I try to create a heating schedule and set the temperature. The slider resets to 5. 

See short video:

https://user-images.githubusercontent.com/49752333/210870844-54734734-9b75-406f-bd29-3cef759c7a97.mp4

**Comment by nielsfaber** [comment]
Please update the card to the latest version before reporting a bug.

**Comment by rploeg** [comment]
Isn't the card updated via the HACS update?
