### ISSUE TITLE
Unexpected trigger even if conditions are not met

### ISSUE THREAD

**Issue by FedericoBS** [nielsfaber/scheduler-component#246]
### Checklist
- [ x] I checked for similar existing issues (both open and closed) before posting.
- [ x] I am running the latest version.

### Expected behavior
I scheduled a change of temperature of the conditioner every hour 
I set up a as trigger  2 conditions in AND related to tracking : PERSON1 IS NOT IN ZONEA; PERSON2 IS NOT IN ZONEA
the expected behavior is that if one of the person is in zone the event must not be triggered and the temperature should not change

### Actual behavior
Even if Neither condition is met the schedule is triggered.
In my example I had set the scheduler to change the temperature of the conditioner every  hour if the persons tracked were not at home. The event is triggered and the temperature is changed even if the persons are in zone (i checked the log of the tracker and both persons were constantly inside the zone.
it seems that the conditions are checked only when the schedule is turned on

### Steps to Reproduce
Here is the schedule:

 {
        "schedule_id": "185095",
        "timeslots": [
          {
            "start": "00:00:00",
            "stop": "02:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 16
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 16
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 16
                }
              }
            ]
          },
          {
            "start": "04:00:00",
            "stop": "05:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 16
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 16
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 16
                }
              }
            ]
          },
          {
            "start": "05:00:00",
            "stop": "06:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "06:00:00",
            "stop": "07:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "07:00:00",
            "stop": "08:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "08:00:00",
            "stop": "09:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "09:00:00",
            "stop": "10:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "10:00:00",
            "stop": "11:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "11:00:00",
            "stop": "12:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "12:00:00",
            "stop": "13:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "13:00:00",
            "stop": "14:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "14:00:00",
            "stop": "15:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "15:00:00",
            "stop": "16:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          },
          {
            "start": "16:00:00",
            "stop": "17:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 18
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 18
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 18
                }
              }
            ]
          },
          {
            "start": "17:00:00",
            "stop": "18:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 18
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 18
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 18
                }
              }
            ]
          },
          {
            "start": "18:00:00",
            "stop": "19:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 18
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 18
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 18
                }
              }
            ]
          },
          {
            "start": "19:00:00",
            "stop": "00:00:00",
            "conditions": [
              {
                "entity_id": "person.federico",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              },
              {
                "entity_id": "person.doina",
                "attribute": "state",
                "value": "vicino_a_casa",
                "match_type": "not"
              }
            ],
            "condition_type": "and",
            "track_conditions": true,
            "actions": [
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.camera_da_letto",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.soggiorno",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              },
              {
                "service": "climate.set_temperature",
                "entity_id": "climate.tinello",
                "service_data": {
                  "hvac_mode": "heat",
                  "temperature": 17
                }
              }
            ]
          }
        ],
        "weekdays": [
          "daily"
        ],
        "start_date": null,
        "end_date": null,
        "repeat_type": "repeat",
        "name": "Riscaldamento Federico fuori casa",
        "enabled": true
      }

**Comment by nielsfaber** [comment]
You can enable debug logging by adding this to configuration.yaml:
```yaml
logger:
  default: warning
  logs:
    custom_components.scheduler: debug
```
You will need to restart HA afterwards.

After enabling debug logging the scheduler component should add additional lines in the HA logs regarding the checks for the conditions.
This should help pinpointing to the issue.
Could you please try this and share the results?

**Comment by nielsfaber** [comment]
Please take note of this issue: https://github.com/nielsfaber/scheduler-card/issues/665

**Comment by FedericoBS** [comment]
maybe the problem was due to the case sensitivity of the name of the zones as the zone in the condition was coded with an initial upper case letter (see Zone condition is case sensitive #665). Now the zone and the condition are bot in lowercase. I enabled the debug and let you know if the problem persists. tks

**Comment by FedericoBS** [comment]
the problem is solved. I also noticed that if an entity in a condition is  a state 'not available', even if it is in OR with other conditions that are met, the action is not executed
