### ISSUE TITLE
Run Action called on disabled scheduler is not ignored

### ISSUE THREAD

**Issue by 3v1n0** [nielsfaber/scheduler-component#248]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]

Calling `scheduler.run_action` on a disabled scheduler, does nothing. 

### Actual behavior
[What actually happened]

The scheduler parameters are applied.

**Comment by nielsfaber** [comment]
This is the intended functionality.
This service offers a way to manually trigger a schedule, it can also be used on a disabled schedule.
