### ISSUE TITLE
Can't edit schedule

### ISSUE THREAD

**Issue by bennop** [nielsfaber/scheduler-component#251]
I don't seem to find many similar cases but ....

Whenever I make a change to a schedule (either new or existing) it is reverted to its previous state almost instantly - only once in a while I manage to save quickly enough to keep my changes.

I use the scheduler card.

Happens with Firefox, Safari, and Chrome on a Mac

Would appreciate any hints o how to fix this ...

**Comment by RomLab** [comment]
Hello,

I have same problem in Google Chrome.  When I use Microsoft Edge everything works. I deleted cookies from Google Chrome, but it is same problem.

**Comment by nielsfaber** [comment]
Update the card to the latest version via HACS.
Click yes when asked to reload the frontend resources.

**Comment by RomLab** [comment]
> Update the card to the latest version via HACS. Click yes when asked to reload the frontend resources.

Thank you. It works.
