### ISSUE TITLE
Allow notification data

### ISSUE THREAD

**Issue by Selim042** [nielsfaber/scheduler-component#256]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I'd be handy if when scheduling notifications you could apply notification data, the same as if you triggered the notification service in other ways.

**Comment by Selim042** [comment]
no stale plz

**Comment by Selim042** [comment]
no stale plz

**Comment by nielsfaber** [comment]
You can follow the procedure [here](https://github.com/nielsfaber/scheduler-card#actions) to add your own custom action to the card.
Under `service_data` you could add any (fixed) data you want to add to the notify service.
If you want to be able to modify the data via the card, you can add action variables. As explained in the documentation you could either add numerical variables (pick a value via a slider bar) or a list variable (pick from several options). It's also possible to add a text field where you can enter your own data.

**Comment by Selim042** [comment]
The new action is tied to a given device, correct?  It'd be nice for the notification service to have additional fields without needing to setup custom actions for every device.

**Comment by Selim042** [comment]
Not stale

**Comment by Selim042** [comment]
Not stale

**Comment by Selim042** [comment]
Not stale
