### ISSUE TITLE
Add light entity as an option just like a switch

### ISSUE THREAD

**Issue by spetrie13** [nielsfaber/scheduler-component#257]
### Checklist
-  I checked for similar existing requests (both open and closed) before posting.
-  My request is generic, other users may benefit from it too.

### Proposal
Add light entity as an option just like a switch

**Comment by larry-glz** [comment]
Hi.  Try adding this to the scheduler card:

```
include:
  - light
```

**Comment by spetrie13** [comment]
> Hi. Try adding this to the scheduler card:
> 
> ```
> include:
>   - light
> ```

Not sure where to add that.

**Comment by larry-glz** [comment]
When you add a scheduler card, go to "Edit" on the lower left.  This is the card configuration.  then click on "show code editor" on the lower left.  you'll see the yaml code for it.  it should start with:

```
type: custom:scheduler-card
```

and have some other stuff in it for the options you've selected.  as per above, add this: 

```
include:
  - light
```

Save.  now when you click "add" in the card, you should get an option to add lights.

**Comment by spetrie13** [comment]
Perfect. Light now shows up as an option. Many thanks for your help.
