### ISSUE TITLE
Can't add new schedule if user type is 'user'

### ISSUE THREAD

**Issue by shevu** [nielsfaber/scheduler-component#26]
When user type is "user" i'm not able to add new schedule. I'm trying to add it by scheduler-card.

After save on screen I see:
![image](https://user-images.githubusercontent.com/5359829/94376980-4d274d00-011e-11eb-9739-48959f6fcf02.png)

**Comment by KTibow** [comment]
Should a user be able to add a schedule? Users are untrusted by default; they can control entities, but not do advanced stuff. I think this is correct behavior.

**Comment by shevu** [comment]
> Should a user be able to add a schedule? Users are untrusted by default; they can control entities, but not do advanced stuff. I think this is correct behavior.

Maybe you have right. In that case button "Add" shouldn't be visible in scheduler-card. What do you think?

**Comment by KTibow** [comment]
That sounds good. Now just how to detect whether a user is an admin or not...

**Comment by shevu** [comment]
I thought that could be available for users because adding new schedule is very easy. But right, maybe it is not possible because of users management :(

**Comment by nielsfaber** [comment]
Good question!
I _think_ this is a limitation of HA. At least it was never my intention to make a restriction here.
I am using `async_register_admin_service` for the service 'scheduler/add'. 
As far as i know, this is the only method that allows to add new entities after startup.
Pretty much all other integrations load entities only at startup, either from your yaml configuration, or through a discovery process asking for a list from bridge devices in your house.
Documentation of HA is quite poor so I am not sure if there are alternative methods that do not impose restrictions to admin.

I think the 'scheduler/edit' (and turn_on/turn_off) are available for all users. I suppose that this is a minimum level you want all HA users to have.

**Comment by shevu** [comment]
So maybe I will create new "issue" for scheduler-card. Maybe it is chance to hide key "Add item" when user is loged in.

**Comment by nielsfaber** [comment]
Consider it done. For consistency, also the right to delete schedules will be revoked for non-admin users.
