### ISSUE TITLE
Setting the temperature for Thermostat Auto mode does not work

### ISSUE THREAD

**Issue by JasonBSteele** [nielsfaber/scheduler-component#264]
### Checklist
- [x ] I checked for similar existing issues (both open and closed) before posting.
- [x ] I am running the latest version.

### Expected behavior
The temperature slider has been added for Auto mode (https://github.com/nielsfaber/scheduler-component/issues/223 ). I would expect the thermostat to be set to this temperature at the same rime as it is scheduled to be switched to Auto mode.

### Actual behavior
The temperature is always set to 16C (a default ambient temperature) rather than 20C I have set in the slider.

Nothing visible in the logs

### Steps to Reproduce
Configure the thermostat like so:
![image](https://user-images.githubusercontent.com/1202763/229456733-375b7246-ce20-49cc-a7f9-1a7ebed7edba.png)

Could this be a race condition between the thermostat automatically setting to 16C when it switched to Auto, and the Scheduler setting it to 20? The Scheduler sets to 20C, but the thermostat sets itself to 16C immediately afterwards?

**Comment by JasonBSteele** [comment]
In Zigbee2MQTT the thermostat presents as model TS0601_thermostat_3, manufacturer _TZE200_6rdj8dzm.

I suspect that this model is using Auto mode for a built-in schedule that is defaulting to an "ambient" 16C, rather than to enable the intelligent partial opening of the valve with adjustments that I had hoped.

TBH I find it hard to tell whether the valve is full on and off rather than partial, so it may be doing this already in ON mode.

**Comment by nielsfaber** [comment]
I cannot tell you whether your device supports setting mode to auto together with a setpoint.
You could try this yourself via the Developer Tools -> Services menu.
This would be the equivalent to the task you set up in the scheduler card:
![image](https://user-images.githubusercontent.com/16861605/236603527-3b1a8d88-bd16-46cf-8bfb-0076c020e30c.png)

If your thermostat ignores the setpoint, it's better to leave the checkbox in front of the slider bar unchecked. In this case scheduler will only set the mode.
