### ISSUE TITLE
Allow input_boolean as a condition

### ISSUE THREAD

**Issue by petosak** [nielsfaber/scheduler-component#266]
Allow setting input_boolean as a condition.
I want manually set "heating season" for other automation.

### Checklist
- [X ] I checked for similar existing requests (both open and closed) before posting.
- [X ] My request is generic, other users may benefit from it too.

### Proposal
[clear description of what you want to see changed or added]

### Additional info
[some example of how the new functionality should look like]

**Comment by nielsfaber** [comment]
This is already possible.
Just make sure to include the input_boolean entities to the card, then they should show up both for creating schedules to change them, and for using in conditions of other schedules.

**Comment by petosak** [comment]
You mean like motion sensor?

**Comment by nielsfaber** [comment]
No. A motion sensor would be a binary_sensor entity in HA.

**Comment by petosak** [comment]
i'm sorry. i don't know where to put input boolean and how :(
into awesome thermostat config? how?
