### ISSUE TITLE
Allow custom repetition delay (eg. two weeks)

### ISSUE THREAD

**Issue by osmeest** [nielsfaber/scheduler-component#267]
### Checklist
- [y ] I checked for similar existing requests (both open and closed) before posting.
- [ y] My request is generic, other users may benefit from it too.

### Proposal
Scheduler and companion scheduler card foresee a repeat daily or weekly option. But there is no option to repeat every N days or every N weeks.

### Additional info
Just adding a repetition delay (with unit depending on the "weekdays": daily repeats every N days; any other choice repeats every N weeks).

**Comment by PeterHoge** [comment]
i need a intervall every month, e.g. every first day of month.

**Comment by HVR88** [comment]
I've been wanting this as well.  It's also not possible in HA's own much more limited scheduler or any other schedule-based add-on.  

Currently, something as simple as bi-weekly (every 2 weeks) or first Monday of the month or 15th of every month, is impossible without writing YAML and possibly also integrating a calendar.

I have an immediate need for every other Friday (bi-weekly) and every 2 days (days will be different every week)
