### ISSUE TITLE
Restore schedulers actions after HA restart

### ISSUE THREAD

**Issue by eteodun** [nielsfaber/scheduler-component#277]
### Checklist

- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.
- [X] I will participate in further discussion about this feature and can test it (if requested) once it's done.

### Proposal

 After HA restart, scheduler tasks are not triggered in current time . for example: I have a schedule between 12 PM and 2 PM , if HA restarted in this interval, the schedule is not triggered, just next trigger.
 In this moment, I have to stop and start again manualy all schedulers to come back
 I asked this because if I have heating with 3 schedules , the heating not working till next time  trigger  after HA restart from diferent causes

### Additional info

must be active after HA restart due to the power issue or manual restart. Not to stop and start again manually

**Comment by nielsfaber** [comment]
I don't think downgrading the version is really the solution here.
I believe that a setting needs to be added to allow the user to choose between the old and new behaviour instead.
So lets keep this open until I find the time to do so.

**Comment by eteodun** [comment]
Hi ,
I have deleted from thermostat config target temperature to work in latest version.
Thanks a lot !
