### ISSUE TITLE
Feature Request: One time schedule.

### ISSUE THREAD

**Issue by cibernox** [nielsfaber/scheduler-component#28]
Just to weight on whether this is doable or if someone has ever requested it before.

Much like alarms on the clock app of most phones allows you to set up an alarm only for tomorrow, that won't repeat until you explicitly enable it again, I think it could be useful to allow to schedule something for a one-time event.

See screenshot of the clock app in Android. 
![alarm-for-tomorrow](https://user-images.githubusercontent.com/265339/94867662-ef5a7400-0441-11eb-82d7-21aa8af2b23b.jpeg)

The idea would be to add another option to the card that would say either `Once` or `One time` that will create a scheduler and will automatically switch it off after is run.
<img width="402" alt="scheduler-card-proposal" src="https://user-images.githubusercontent.com/265339/94868011-993a0080-0442-11eb-93f0-c9e362e132ea.png">
If the user selects "Once" and sets the time to 21:00 and when it's 18:00, it will run in 3 hours. If It's 22:00 it will fire in 23 hours.
<img width="405" alt="scheduled-for-tomorrow-noon" src="https://user-images.githubusercontent.com/265339/94868233-12395800-0443-11eb-94b8-30d57e3030ad.png">

<img width="406" alt="scheduled-but-disabled" src="https://user-images.githubusercontent.com/265339/94868386-62b0b580-0443-11eb-9bb4-1bcfe8eee175.png">

Is this something feasible with the current architecture and something you would be interested in?

**Comment by KTibow** [comment]
Duplicate of https://github.com/nielsfaber/scheduler-card/issues/34 🤷

**Comment by cibernox** [comment]
@KTibow I didn't check the repo of the card component. That said, and since you mentioned that what seemed complex to you was the UI, what do you think about what I suggested?

**Comment by KTibow** [comment]
Well maybe they're linked issues. But most users raise issues on the card's repo.

**Comment by cibernox** [comment]
I'll comment on the other issue then. I'll close this one.
