### ISSUE TITLE
Impossible to create a new schedule

### ISSUE THREAD

**Issue by TomcatPi** [nielsfaber/scheduler-component#289]
### Checklist
- [ ] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]
Trying to add a new schedule

### Actual behavior
[What actually happened]
When I triy to add a new schedule, the window is empty (see screen capture)
My existing schedule works fine, but I cannot add a new one, it only propose to add a schedule to the switch I already use, not another one
It just updated my HA from à supervised one to HAOS with a restore backup
I tried to uninstall the componant and the card and reinstall it via HACS, still the same
I delete the schedule i had, and was only able to create a new one with the switch I used before, not with another one

Any idea of what I can do to solve my problem ?

![Capture](https://github.com/nielsfaber/scheduler-component/assets/130712179/db301218-6fc2-42d3-8da4-a3b023269740)
![Capture2](https://github.com/nielsfaber/scheduler-component/assets/130712179/a1aaa47d-f8f7-44f5-8389-a1c05c52942b)

**Comment by TomcatPi** [comment]
I tried to investigate, and when I try to create a scheduler I 've got briefly two pop-up before the blank one
here they are


maybe it could help
![Capture3](https://github.com/nielsfaber/scheduler-component/assets/130712179/fff1fd22-9c84-4837-be2e-c6676b6d0d69)
![Capture4](https://github.com/nielsfaber/scheduler-component/assets/130712179/fe0caa99-2483-4eb4-9784-61243c28bb9a)

**Comment by nielsfaber** [comment]
Schedules are created via the scheduler card.
You need to go into the edit mode to configure the card options:
![image](https://github.com/nielsfaber/scheduler-component/assets/16861605/da42959c-3dde-4792-a4bd-33b129e3f670)

**Comment by TomcatPi** [comment]
ok, i'm an idiot, I just forgot how I did it the first time. Thanks for the reply
By the way, I was wondering if it possible in the option of the scheduler it is possible to use a condition between 2 values
I would like to active teh schedule of my pool pump between 2 temp
I only see Below and above
Anyway to do this ?

**Comment by TomcatPi** [comment]
I was just not using the components the right way, thanks to the authors
