### ISSUE TITLE
Adding the ability to start at a time from a input_datetime helper with a duration from another input_datetime

### ISSUE THREAD

**Issue by tigers75** [nielsfaber/scheduler-component#290]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
As many people I use an algorithm for watering the garden that corrects the duration based on temperature and rainfall and often runs a sequence of events to start-stop the watering zones.
Thus the starting time of the zone s may vary together with the running time.
I'd like to use scheduler for this to align with my other scheduled tasks and also using the clean interface. I think this could be useful for others and also for different use cases.
So I'd like to have the ability to set a schedule similar to the fixed time we have now, but with the ability to select an input_datetime as the start time and another input_datetime for the duration.
I also think that setting a duration after which the entity should be toggled could be a nice general improvement too (but this would be another feature request I assume).

### Additional info
Excuse the poor paint skills:
![image](https://github.com/nielsfaber/scheduler-component/assets/37505492/e0af1ce7-f167-4067-b0b4-0bde99d9c2e3)

**Comment by nielsfaber** [comment]
This seems to defeat the whole purpose of scheduler, it is mostly intended to control the time via the card.
Why not using a automation instead?

**Comment by tigers75** [comment]
I admit that the main purpose is to have a clean and uniform interface across all scheduled tasks, of course I can do it with an automation (I am doing this at the moment), but exactly like I could do with an automation the "run at a fixed time" task.
Thinking of it anything in scheduler could be made with an automation, but with MUCH more effort, especially for someone not very skilled with automations.
I think that the whole scheduling part is really a huge missing part in HA, and this add-in really fills in many holes. Justo to saty, what I miss mainly from my precedent automation system is how easy it was to run a switch for a certain amount of time directly from the switch command window: there was a "turn on/off for X seconds/minutes/hours", now in HA I have to write an automation every time, and I can't ask my wife to do so.
