### ISSUE TITLE
conditions dont allow.... conditions

### ISSUE THREAD

**Issue by magiva** [nielsfaber/scheduler-component#291]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]
when i selected conditions, i thought i could set one for if anyone was home, use a boolean entity etc but it asked for other climate entities.

### Actual behavior
[What actually happened
conditions asked for climate entities only

### Steps to Reproduce
[Explain how to see the behaviour]
add a condition

if this is not a feature then it really should be as it makes sense to have a schedule that only activates if someone is home, in a room etc

**Comment by nielsfaber** [comment]
Duplicate of #292

**Comment by magiva** [comment]
this is not closed as detailed in #292 this does not work, i can only select from the climate group
