### ISSUE TITLE
please review the conditions bug as it doesnt work

### ISSUE THREAD

**Issue by magiva** [nielsfaber/scheduler-component#293]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]
ability to use any entity for a condition.
refer to #291  and #292 - these were closed but conditions do not work

### Actual behavior
[What actually happened]
can only select climate entity

### Steps to Reproduce
[Explain how to see the behaviour]
add a condition to a schedule

**Comment by nielsfaber** [comment]
Please do not create any more (false) bug reports.
This card has 1000+ users and many (including myself) use conditions on a daily basis, it definitely works.
Just because you fail to understand how to configure the card is not a valid reason to raise it as an issue.

**Comment by magiva** [comment]
ive asked you to clarify and you didnt reply
i supplied screenshots of how it responds which backs my question and issue and you have not correct that.
what else should i do

**Comment by nielsfaber** [comment]
This video shows how to edit a card in HA dashboard: https://youtu.be/XY3R0xI45wA
It works the same for scheduler-card.
If you cannot figure it out on your own, I cannot help you. Maybe this card is not for you in that case.
