### ISSUE TITLE
Bi weekly schedule

### ISSUE THREAD

**Issue by stavroskool** [nielsfaber/scheduler-component#296]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
I know it has been requested but I open it again. It would be very helpful to have a biweekly schedule or a schedule that it is repeated every n weeks. In the very stupid approach even the option to check specific days in calendar would help

**Comment by duczz** [comment]
The integration for a external helper would be great and solce your problem, i have ask for these multiple times, but always ignored
![image](https://github.com/nielsfaber/scheduler-component/assets/25475385/55da712d-d5e4-4781-b07b-41f4d7663edf)

**Comment by ukanuk** [comment]
I would find a biweekly schedule helpful, too. Recycling bins need to be put out every other week.

**Comment by ukanuk** [comment]
Oh, I just learned the Home Assistant Local Calendar supports creating events every N weeks. And then those can drive notifications. Interface is less slick than this HACS integration, but it seems like it'll work for me.

https://www.home-assistant.io/integrations/calendar#automation
