### ISSUE TITLE
Integration Failed to set up

### ISSUE THREAD

**Issue by echtikke** [nielsfaber/scheduler-component#297]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Actual behavior
First of all, thank you for the scheduler-component. However I'm not able to get it working. I'm on Home Assistant core 2023.6.3 and using the latest version of the scheduler-compoonent (3.2.15)

I installed the component, integration and card following the instructions. In the devices part, I see a 'Failed to set up' error. When adding a card, I receive the message: 'Could not connect with the scheduler component. It needs to be installed as integration before this card can be used.'

Attached the debug logging.

I'm not sure what I'm doing wrong. Couldn't find something similar on the internet, so thank you for your help! Please let me know if you need any other information.

[home-assistant_scheduler_2023-10-14T11-31-34.415Z.log](https://github.com/nielsfaber/scheduler-component/files/12904985/home-assistant_scheduler_2023-10-14T11-31-34.415Z.log)

**Comment by lamixer** [comment]
Go back into Hacs, this time instead of Frontend, add an integration. It is called Scheduler component. 

THEN go into the normal HA settings, and again click + to add integration. Now it is just called Scheduler.

I just went through this myself. Seems harder than it should be! But thanks again to Nielsfaber for making it for us all to use!

**Comment by echtikke** [comment]
Thanks for the help. However, I installed the Scheduler component and integration already.

**Comment by LiloBzH** [comment]
Hi.

same probleme here. i have installed the both app and it doesn t work

"Could not connect with the scheduler component."
