### ISSUE TITLE
[Feature request] service "Scheduler: Run Action" with option for ignore condition

### ISSUE THREAD

**Issue by devildant** [nielsfaber/scheduler-component#301]
hi,
the "Scheduler: Run Action" service allows you to trigger a schedule, however if the schedule has conditions that do not match, the schedule is not executed.

It might be nice to have an option like automation service to ignore the conditions.

**Comment by jaynis** [comment]
I was looking for the same feature and implemented this in a pull request. Hopefully @nielsfaber finds some time to review this soon.
