### ISSUE TITLE
Priority system

### ISSUE THREAD

**Issue by sirkojon** [nielsfaber/scheduler-component#302]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Hi, 
recently I forked your repo and implemented a simple priority system in which you can specify a priority for each schedule. The main idea is that sometimes you want to quickly switch between schedule setups (e.g. leaving for vacation) and turn them back on afterwards. When schedule with higher priority is created (or enabled) it turns off lower priority schedules that operates on the same _[1]_ entities. After it is disabled or deleted it turns the schedules that it previously disabled back on.  I also made the necessary changes in the scheduler-card. 
Would you be interested in adding such thing to your project? 

_[1]  Lower schedules are affected if their entities are subset of the higher priority schedule entities (so you can affect multiple schedules with a single higher priority schedule)._

**Comment by devildant** [comment]
Hi, I'm not a dev on this project, but you can already do it with the conditions and either an input_boolean if you only have 2, or with an input_number if several

exemple in my case :

![image](https://github.com/nielsfaber/scheduler-component/assets/8700106/baed6bd2-7619-491c-aa00-d360a717eddd)

"Chauffage Salon : Present"  activates when I'm at home and if I'm away it's "Chauffage Salon : Absent", both are on the same time slot

![image](https://github.com/nielsfaber/scheduler-component/assets/8700106/bb146688-d610-4400-aafa-9d66924f7189)
