### ISSUE TITLE
Schema Display 

### ISSUE THREAD

**Issue by mattfox27** [nielsfaber/scheduler-component#308]
Not sure if this is a bug but when I use the schema it shows in status next light schedule in 3 hours even though it's not until the next morning at 8am and it's only 9pm the day before, so that's like 11 hours![Screenshot_20231114_211458_Home Assistant.jpg](https://github.com/nielsfaber/scheduler-component/assets/6801877/d0300fa2-9f77-4b10-85df-a83acc0e6e05)

**Comment by nielsfaber** [comment]
I cannot tell you if this could be a bug, since you didn’t share the schedule that you programmed.
I am guessing you have a timeslot starting at 00:00, so at midnight some action is scheduled.
