### ISSUE TITLE
Potential code issue in v2.1.0: 'Unable to prepare setup for platform scheduler.switch'

### ISSUE THREAD

**Issue by infinitesunrise** [nielsfaber/scheduler-component#31]
Hey there, I think I might have come across a code issue in v2.1.0. When attempting to add a new schedule with your scheduler-card I was seeing the attempt fail with the error "Unable to prepare setup for platform scheduler.switch. No module named 'homeassistant.helpers.trigger'". I traced this back to the include statement on line 17 of custom_components/scheduler/switch.py:

```from homeassistant.helpers.trigger import async_initialize_triggers```

I'm new to HA and pretty garbage at python, so naturally I just commented the line out hoping the issue would disappear. Amazingly, it actually did. My lights have been following my schedules correctly for the past day. But I'm not sure if this error was because my HA is misconfigured or simply because the wrong file was being called for the import.

scheduler-component v2.1.0
scheduler-card v1.7.0
HACS v1.6.0 /  frontend v202009091732
home assistant 0.114.4

**Comment by KTibow** [comment]
Yup, it's unused. Check the latest GitHub Actions flake8 runs to see all of the unused stuff. Incoming PR!

**Comment by nielsfaber** [comment]
Nice catch!
I must admit this is also my first project in Python. Getting this thing of the ground is a bit of trial and error.
Weird that apparently I was experimenting with a function that is introduced in 0.115.
I recommend you to update to latest HA version though. I cannot guarantee things will be compatible with older versions (especially for the card).
