### ISSUE TITLE
schedule a pellet stove

### ISSUE THREAD

**Issue by merlino1975** [nielsfaber/scheduler-component#312]
I tried to set the programming according to my needs.
if I tried to write here what I should achieve using this component, could someone tell me if it can be done, and if so, how?
I have a pellet stove that I have to turn on in the morning after 6.30 if the room temperature is below 19 degrees. To the power 4.
Once the temperature of 20.5 has been reached, the stove must reduce the power to minimum.
if the room temperature, despite the stove at minimum, reaches 22 degrees then the stove should be turned off until it reaches 20 degrees (or 19 if it cannot be done otherwise)
and after 10.30pm the stove must turn off, or remain off, even the temperature drops below 20 degrees or 19 degrees.
Did I explain myself well? thanks

I forgot one thing
the stove is a pellet stove that also burns wood, this programming for wood cannot be done, because obviously the wood fire cannot be turned off on command. so I’m wondering if the programming can be blocked when the stove is in wood mode

**Comment by Chalcear** [comment]
Yes its possible
![Screenshot_20240120_115302_Home Assistant](https://github.com/nielsfaber/scheduler-component/assets/122736940/b254d3e5-7544-4cdd-a28e-f6be2fa48d57)

![Screenshot_20240120_115353_Home Assistant](https://github.com/nielsfaber/scheduler-component/assets/122736940/06149f18-c357-45ca-9076-6a6c629ffde6)

**Comment by Chalcear** [comment]
![Screenshot_20240120_115449_Home Assistant](https://github.com/nielsfaber/scheduler-component/assets/122736940/46ab7acc-9273-4031-9d8b-7203865ffd1d)

**Comment by Chalcear** [comment]
I m testing this sine 1 week
