### ISSUE TITLE
Climate temperature incorrectly set &  triggers in the middle of the night

### ISSUE THREAD

**Issue by wranglatang** [nielsfaber/scheduler-component#313]
Hello,  I have been having a with my schedules - when a trigger occurs the value that is set on my climate device is incorrect. This also happens at 00:00 when the temperature is meant be be set to 5 but it gets set to 20. in the screenshot below the "shelly_trv_master_beedroom" is meant to be set to 18 - but it is being set to 20. 

Here are some screenshot examples of where it has happened:
<img width="580" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/30660751/cf6d3533-76ca-4564-a3ad-18f883b2d1f6">

Config in [Pastebin](https://pastebin.com/R07igQJD)

**Comment by wranglatang** [comment]
I am still Jack this issue

**Comment by nielsfaber** [comment]
From the configuration you shared I can conclude that scheduler is not setting your thermostat to 20.
Perhaps this is done by the device itself when the mode is changed to heat.
Your issue seems the same as #311 so I think its best to continue the discussion there.
