### ISSUE TITLE
'program advance' (like normal heating controllers) forces NEXT time-slot

### ISSUE THREAD

**Issue by team-tech-works-uk** [nielsfaber/scheduler-component#314]
I checked for similar existing requests (both open and closed) before posting.  There are 'similar' requests - one mentioned a 'skip' feature ? but I could find nothing the same in the integration, but please forgive me if I've missed it !!

My request is generic, other users may benefit from it too. ALL central-heating systems have an 'advance' button - usually used to force heating ON or OFF without disrupting schedule.

### Proposal
To allow a user (automation etc.) to force scheduler to the NEXT 'time slot' in it's schedule 

### Additional info
e.g. sched = ON 8am .. OFF 12pm .. ON 4pm .. OFF 10pm :  if it's 1pm, this command will cause scheduler to activate the 4pm slot.
Perhaps an additional option in Scheduler: Run Action or an additional script 'Scheduler: Advance'

**Comment by nielsfaber** [comment]
This feature has been requested multiple times.
I agree it can be useful.
However, I had trouble finding space in the card to add a button for this. I guess the UI part is the only thing holding me back from implementing this.
If you have a good idea how this should look like, please share.
