### ISSUE TITLE
Known the  schedule state (with condition taken into account)

### ISSUE THREAD

**Issue by afaucogney** [nielsfaber/scheduler-component#315]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Have an attribut that expose the state of a scheduler, but that take in consideration the condition of the scheduler

### Additional info
Use Case:
- I have 3 different schedulers for the same target ( a climat thermostat)
- The different scheduler are used when various conditions are true (offpeak hour for electricity, day of the week...)

=> I do not really know which schedule is taken into account in real-time ! I need this for debugging and testing to secure the fact that the schedule has been applied or not during the day.

**Comment by nielsfaber** [comment]
Conditions (and their entities) are not continuously watched, but only checked at the time the schedule is triggered.
What you are requesting would require a big architectural change and it would require 24/7 monitoring of all conditions of all schedules, and recomputing them when any condition entity changes its state.
I think this would be a step too far for this project.
The schedules are meant to trigger based on time and I would like to keep it like this.

**Comment by x-drum** [comment]
Hi,
thanks for your amazing job with scheduler-component (and card) I've found it very useful.

I have a similar need: to know for a given active and triggered schedule what's the actual active hvac_mode  (e.g: off, heat  etc.).

@nielsfaber is it possible to expose something or to execute a "post action" once a given automation gets triggered? 
I would love to update an helper (Boolean) and use it's state later in automation.

Thanks!

**Comment by Gandulf78** [comment]
> Conditions (and their entities) are not continuously watched, but only checked at the time the schedule is triggered.
> 
> What you are requesting would require a big architectural change and it would require 24/7 monitoring of all conditions of all schedules, and recomputing them when any condition entity changes its state.
> 
> I think this would be a step too far for this project.
> 
> The schedules are meant to trigger based on time and I would like to keep it like this.

I have a similar request. I have a lot of schedules on the same targets taking into account several conditions (school holidays, electricity economy days). I understand you don't want to monitor in real time all the conditions but maybe you could just consider to log a scheduler state at each transition (when you are reevaluating the condition anyway)? It would be helpful for validation. 
Thanks for your amazing scheduler.
