### ISSUE TITLE
"Re-evaluate conditions when conditions change" constantly re-evaluating

### ISSUE THREAD

**Issue by sven337** [nielsfaber/scheduler-component#316]
Hi,
I see something similar to issue #156.

I have a schedule that changes the temperature on a thermostatic radiator valve, with a condition "TRV is not off".
The problem is that I cannot change the temperature manually when the schedule is active, because every few seconds it will forcefully revert the setting to what is in the schedule. When I disable the schedule or untick the "re-evaluate conditions" checkbox, the problem disapperas.

### Checklist
- [x ] I checked for similar existing issues (both open and closed) before posting.
- [ x] I am running the latest version.

### Expected behavior

Re-evaluate conditions when they change should only trigger.. when the condition changes.
In the scenario that I describe, the TRV stays ON all the time as I manually override the temperature setpoint. Changing the temperature therefore should not trigger re-execution of the scheduled action.

### Actual behavior

Changing temperature seems to confuse the scheduler component into re-evaluation the "TRV is not off" condition.
Can you please take a look at what might be happening? 
Thanks

### Steps to Reproduce

Covered above.

**Comment by sven337** [comment]
It would have been nice to get some attention on this problem; at any rate at the moment I seem not to be able to observe it any longer. (HA update may have made the problem disappear)

**Comment by nielsfaber** [comment]
Your TRV integration triggers a 'state change' for the climate entity when you change the setpoint.
Scheduler does not compare the old state with the new state so even if the operational mode remains the same, this could the schedule to be triggered.
Likewise, if you create an automation in HA to trigger on a state change of your climate entity, it would also be fired every time the setpoint (and not operational mode) changes.
If you want to specifically use the operation mode as condition in the schedule, you should consider to create a template sensor to store the operation mode of the climate device (for example the `hvac_action` attribute), and use this template sneosr in your condition.

**Comment by sven337** [comment]
Thanks, I will investigate further based on your indications, if I see the problem again.
However, I confirm that I cannot reproduce any longer at the moment.
I was running HA 2023.10.3 when I got the problem, now I am on 2023.12.3, so maybe the upgrade changed something. Do you have any information to that effect?

**Comment by nielsfaber** [comment]
>  Do you have any information to that effect?

No. Scheduler has not been updated since last May, so any change would be on the side of HA.

**Comment by sven337** [comment]
The side of HA was what I was talking about, precisely. :)

**Comment by sven337** [comment]
OK, I can still reproduce this readily. I've set up an automation as you described to check your hypothesis, and it does fire when I change the setpoint. I do not think it is surprising though, as you'd want to be able to set up automations when the setpoint changes.

> Scheduler does not compare the old state with the new state so even if the operational mode remains the same

This seems like a bug to me. The checkbox reads 'Re-evaluate when conditions change' which implies to re-evaluate only when they change and not when they don't change. I believe you'd need to compare, otherwise you lose orthogonality between setpoint and operation mode.

**Comment by nielsfaber** [comment]
I just released v3.3.0 which adds a check comparing the old vs new state when HA triggers a state change event. The schedules will only be triggered when the state of the condition entities has changed.
I hope this helps for your usage. Otherwise let me know.
