### ISSUE TITLE
Weekend Schedule: Saturday trigger ~ 19 minutes delayd, Sunday trigger at configured time

### ISSUE THREAD

**Issue by mawa356** [nielsfaber/scheduler-component#317]
All my Weekend schedules fire the Saturday trigger ~ 19 minutes after configured time, but Sunday trigger on time.

![Schedule](https://github.com/nielsfaber/scheduler-component/assets/141647470/31ce56ee-cd89-4290-80d7-39cd5753fd69)

Attached a screen shot of one of my weekend schedules. The covers are set to open at 8:00 am and to close at 21:00. On Saturdays, the covers open around 8:19 am and close at 21:00. On Sundays, the covers open at 8:00 am sharp and close at 21:00. 

I have a similar workday schedule and I do not face any issues with this schedule.

**Comment by nielsfaber** [comment]
Please enable debug logging for scheduler by adding this to the configuration.yaml (and restart HA afterwards):
```yaml
logger:
  default: warning
  logs:
    custom_components.scheduler: debug
```

Next time the issue occurs, you should see more information in the HA logs.
Perhaps the entity is unavailable and scheduler waits (for 19 minutes) for it to become available before he can perform the action.

Please share the logging results.

**Comment by mawa356** [comment]
Beginning of the week I added the debug logging and restarted HA. This weekend I did not face the delay issue ... not sure whether this is related to the configuration.yaml change or the HA restart.

Anyway, I will re-check the next weekends and post the results here.

**Comment by mawa356** [comment]
Also this week no issue/delay. I will disable debug logging and re-check next weekend.

**Comment by mawa356** [comment]
And this weekend again no way to reproduce the issue. So I think best to consider it as solved.
