### ISSUE TITLE
Add "Enable" and "Disable" to Scheduler Service 

### ISSUE THREAD

**Issue by Neevok** [nielsfaber/scheduler-component#320]
### Checklist
- [ x] I checked for similar existing requests (both open and closed) before posting.
- [x ] My request is generic, other users may benefit from it too.

### Proposal

I'd love to have a general Switch to tun the Service on and of in general instead of going through each schedule item to enable an disable it.

### Additional info
Scenario: I want to create a Manual Heating Override Switch. If I turn it on I don't want to have any scheduler item to be executed. Turning it off shall enable the scheduler Component again.

**Comment by nielsfaber** [comment]
I added services `scheduler.disable_all` and `scheduler.enable_all` in the v3.3.0 release which controls all schedules simultaneously. Hope this helps for your usage.

**Comment by Neevok** [comment]
Thank you. Exactly what I've been looking for!
