### ISSUE TITLE
Support extra entity types (input_number, input_boolean)

### ISSUE THREAD

**Issue by michaelpiron** [nielsfaber/scheduler-component#327]
### Checklist
- [X] I checked for similar existing requests (both open and closed) before posting.
- [X] My request is generic, other users may benefit from it too.

### Proposal
Currently, Scheduler can perform actions on following entity types: switch, light, climate, alarm panel.
Proposal to extend the list of supported entity types, to include "helper-type" of entities:
- input_number
- input_boolean

### Value
This feature would unlock more advanced cases of automation (eg. for the smart control of heat pumps, car chargers, etc).
Current work-around is to use time triggers in an automation, which is not ideal:
* Time schedules are not located in one place, so you lose oversights: partly in scheduler component, partly in automations.
* In automations, we don't have the handy UI to modify time schedules, as we have in scheduler component.

**Comment by nielsfaber** [comment]
this is already in place, you should check your card configuration.

**Comment by michaelpiron** [comment]
Indeed.. Sorry, I overlooked that
