### ISSUE TITLE
slider not showing on MS Edge

### ISSUE THREAD

**Issue by feradelectronics** [nielsfaber/scheduler-component#33]
Slider works with Chrome but not edge browser.

**Comment by KTibow** [comment]
New Edge or old Edge?

**Comment by nielsfaber** [comment]
Wrong repo.

**Comment by feradelectronics** [comment]
Latest edge

**Comment by KTibow** [comment]
Chromium edge? Upgrade to it here: https://www.microsoft.com/en-us/edge

**Comment by feradelectronics** [comment]
Excellent thanks




Sent from phone







On Sun, Oct 4, 2020 at 8:06 AM -0600, "Kendell R" <notifications@github.com> wrote:















Chromium edge? Upgrade to it here: https://www.microsoft.com/en-us/edge
