### ISSUE TITLE
Can't find component

### ISSUE THREAD

**Issue by stephanlarsson** [nielsfaber/scheduler-component#330]
I feel quite silly asking this. Have tried several times to install, uninstall & reinstall both the card and the compenent, but I keep getting the following: "Could not connect with the scheduler component. It needs to be installed as integration before this card can be used."

The card is installed manually and the custom component through HACS UI. Could that be the issue?

**Comment by Dimitry-Muzi** [comment]
The same situation. It is not present in integration.

**Comment by jmarlier** [comment]
I have the same problem, I installed the integration and interface with HACS

**Comment by MauRau75** [comment]
same problem...

**Comment by kds69** [comment]
same here

**Comment by jmarlier** [comment]
Have you completed this step ? @stephanlarsson @kds69 @shalldavies 

Step 3: Add integration to HA (<--- this is a step that a lot of people forget)
