### ISSUE TITLE
hass.components.websocket_api deprecated

### ISSUE THREAD

**Issue by Drewskieza** [nielsfaber/scheduler-component#336]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
No Error

### Actual behavior
Error in the log file

Logger: homeassistant.helpers.frame
Source: helpers/frame.py:156
First occurred: 08:49:40 (2 occurrences)
Last logged: 08:49:41

Detected that custom integration 'scheduler' accesses hass.components.websocket_api. This is deprecated and will stop working in Home Assistant 2024.9, it should be updated to import functions used from websocket_api directly at custom_components/scheduler/websockets.py, line 235: hass.components.websocket_api.async_register_command(, please create a bug report at https://github.com/nielsfaber/scheduler-component/issues

### Steps to Reproduce
Restart HA 2024.3.0
Check logs

**Comment by agak79** [comment]
I came to report the same log warning

**Comment by olli711** [comment]
same problem by me. After installing latest Version of HA

**Comment by robertp007** [comment]
same problem by me.

**Comment by nielsfaber** [comment]
I believe this issue is not actual and solved by updating your scheduler-component installation.
