### ISSUE TITLE
Unable to remove missing HA lights

### ISSUE THREAD

**Issue by GitittomeNow** [nielsfaber/scheduler-component#339]
I’ve been adding and removing lights from home assistant (HA). If I forget to first remove the light to be deleted from a scheduler-component schedule it is then not possible to edit and remove what it shows as an orphaned light. You can deselect working lights, just not orphaned ones. The only fix is to delete and recreate the schedule. 

### Checklist
I am running the latest version and did not find this issue elsewhere. 

### Expected behavior
It should be possible to edit schedules and delete lights that are no longer in home assistant. 

### Actual behavior
When editing schedules with missing lights, these light are not deselect-able. 

No errors in logs. 

### Steps to Reproduce
Leave a light in a schedule and remove that light from home assistant. Then try to edit the schedule.

**Comment by nielsfaber** [comment]
I agree this behaviour should be improved.
For the time being, you can use the scheduler.remove service (via HA developer tools panel) to remove schedules manually.
When I have the time for it I will work on better support for this via scheduler-card.

**Comment by GitittomeNow** [comment]
Thank you.
