### ISSUE TITLE
Lost setting after update 

### ISSUE THREAD

**Issue by mf42** [nielsfaber/scheduler-component#34]
Hi, 
I just updated the schedule integration as well as the schedule card. 

Result:
- all my settings I did beforehand (which worked perfectly til now)  are lost
- I cannot setup new schedule. After "saving" nothing happens. No entries.

To be honest... absolutely useless at this point. Yes, I cleaned the cache, yes I restarted HA 2 times... Nothing. What happened?
Any idea?

**Comment by KTibow** [comment]
Can you see `scheduler.add` in the list? Try manually removing the integration from `custom_components` with the command line addon and restart and readd and try again.

**Comment by nielsfaber** [comment]
Lets start by telling us:
- Which HA version you are running
- Which version of the scheduler-component you are running
- What the logs say

Without this info, i cannot help you at all...

**Comment by mf42** [comment]
Hi, 

HA version : 					0.112.5; Python 3.7  (irtualenv)
Scheduler card version: 			v 1.7.2
Scheduler integration version: 	v 2.1.0


That is what my log says:
Protokolldetails ( ERROR )
Logger: homeassistant.setup
Source: setup.py:280 
First occurred: 4. Oktober 2020, 20:43:48 (1 occurrences) 
Last logged: 4. Oktober 2020, 20:43:48

Unable to prepare setup for platform scheduler.switch: Platform not found (No module named 'homeassistant.helpers.trigger').

**Comment by mf42** [comment]
just updated to v 2.1.1; now I can see my entries. Uhmm, ok. Seems to work now. Thanks for your quick response.
