### ISSUE TITLE
Add lawn_mower in the list of available entities

### ISSUE THREAD

**Issue by Fly0017** [nielsfaber/scheduler-component#344]
Hello ! 

with an update, they added lawn mower in HA instead of seeing them like vaccum, and i can't schredule my mower cause i can't see it anymore in the card. 

It's a bug on my install or just a missing functionnality?

Thank in advance.

**Comment by nielsfaber** [comment]
I added this in the latest version of the card. Make sure to include the lawn mower entities in the card configuration.
