### ISSUE TITLE
Quando aggiungo schedulare da impostazioni-integrazione

### ISSUE THREAD

**Issue by ProcuratorTitan** [nielsfaber/scheduler-component#345]
Errore
Impossibile caricare il flusso di configurazione: {"message":"Invalid handler specified"}

Registratore: homeassistant.config_entries
Fonte: config_entries.py:2589
Prima occorrenza: 19:51:19 (5 occorrenze)
Ultima registrazione: 19:59:02

Error occurred loading flow for integration scheduler: No module named 'custom_components.scheduler.store'

**Comment by nielsfaber** [comment]
This issue seems to be related to your installation.
The error suggest that the file `custom_components/scheduler/store.py` is missing.
This shouldn't happen if you copy all the files, or when installing via HACS.
