### ISSUE TITLE
"Add" button no longer appear on the lovelace card after upgrade scheduler-component to 3.3.3

### ISSUE THREAD

**Issue by persuasive0pest** [nielsfaber/scheduler-component#346]
Scheduler-card:
![image](https://github.com/nielsfaber/scheduler-component/assets/160201971/82170b7e-ca9b-4c5e-966f-1c965c156840)

Scheduler-component:
![image](https://github.com/nielsfaber/scheduler-component/assets/160201971/8aef08fa-60f2-4331-ace8-7375c35a6753)

### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]

### Actual behavior
[What actually happened]

### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by jbergler** [comment]
Not sure which of these two is preferred, but leaving a comment to link them to each other either way https://github.com/nielsfaber/scheduler-card/issues/810

**Comment by nielsfaber** [comment]
Closed for being a duplicate.
