### ISSUE TITLE
Multiple entries in a timer not working 

### ISSUE THREAD

**Issue by winetou** [nielsfaber/scheduler-component#347]
### Checklist
- [x] I checked for similar existing issues (both open and closed) before posting.
- [x] I am running the latest version.

### Expected behavior
[What you expected to happen]

### Actual behavior
[What actually happened]

### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by Breworks** [comment]
I seem to be having a similar issue with most Schedules not working since updating to HAAS 2024.4.1. This is the only thing that has changed.

**Comment by winetou** [comment]
No it not working with 2024.4.2

**Comment by bbwebb** [comment]
I also had this problem after upgrading to 2024.4.1.  I upgraded to the latest version of the scheduler component and the lovelace scheduler-card and then did a full reboot of my environment.  That seemed to resolve the issue for me.  It appeared to me that the scheduler was not getting TIME information for some reason.  My timers were not progressing with the time until next schedule change not moving.

**Comment by garthy** [comment]
I just had a schedule miss. I'm going to reboot my machine and report back.

**Comment by winetou** [comment]
Thanks, now it works for me again
