### ISSUE TITLE
Defective Schedule if weekday not within optional period

### ISSUE THREAD

**Issue by mburget** [nielsfaber/scheduler-component#349]
### Checklist
- [X ] I checked for similar existing issues (both open and closed) before posting.
- [ X] I am running the latest version.

### Expected behavior
Not possible to get "defective schedule entities"
<img width="504" alt="image" src="https://github.com/nielsfaber/scheduler-component/assets/77898400/c6836037-6d9d-454c-b908-f0a2cfa8448f">

### Actual behavior
Example:
1. Setting a schedule which runs on mondays at 12:00
2. In the option tab limit the schedule to a period wich do not include a monday e.g from 18.4.24 to 18.4.24
3. saving the schedule leads to a defective schedule entity
  

### Steps to Reproduce
100% reproducible by following the described steps: see actual behavior

Thanks for your work !

**Comment by nielsfaber** [comment]
18.4 is not on a monday, so this is indeed a schedule that cannot be processed (hence defective).
I don't consider this a bug, it's a user error.

**Comment by mburget** [comment]
Ok but is there a way to get rid of these schedules entities? I did not find one.

**Comment by nielsfaber** [comment]
There is a scheduler.remove service for deleting schedules.
Ideally the card should be able to edit these as well, but this is currently not working well.
