### ISSUE TITLE
Schedule vacuum with rooms

### ISSUE THREAD

**Issue by Joe-githubby** [nielsfaber/scheduler-component#357]
I would like to request a feature that allows for specific rooms to be vacuumed. 

On certain days I want only selected rooms to be vacuumed.

**Comment by nielsfaber** [comment]
You can add a custom action to the card yourself, see [customize](https://github.com/nielsfaber/scheduler-card?tab=readme-ov-file#customize).
I won't add anything to this project which is not generic (i.e. actions that are specific to certain brands of vacuums).
