### ISSUE TITLE
Warning message when upgrading to 2024.7.0

### ISSUE THREAD

**Issue by ColinRobbins** [nielsfaber/scheduler-component#362]
### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
[What you expected to happen]
Work with no errors reported in the log

### Actual behavior
[What actually happened]
See error message below.

```
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:151
First occurred: 08:40:11 (1 occurrences)
Last logged: 08:40:11

Detected code that calls async_forward_entry_setup for integration scheduler with title: Scheduler and entry_id: 0a52a583b2f94f6196da4119370d6c94, during setup without awaiting async_forward_entry_setup, which can cause the setup lock to be released before the setup is done. This will stop working in Home Assistant 2025.1. Please report this issue.rors 
```

### Steps to Reproduce
[Explain how to see the behaviour]
Upgrade to HA 2024.7.0

**Comment by nielsfaber** [comment]
Thanks for reporting the issue, this is resolved in release v3.3.4.
