### ISSUE TITLE
Schedule switch error in version 3.3.4 during a script repeat loop

### ISSUE THREAD

**Issue by mobilifone** [nielsfaber/scheduler-component#363]
### Checklist
- [ ] I checked for similar existing issues (both open and closed) before posting.
- [ x] I am running the latest version.

### Expected behavior
[What you expected to happen]
All schedule switches related to the list should be turned on

### Actual behavior
[What actually happened]
Only the first element in the list is turned on and than error is raised

### Steps to Reproduce
[Explain how to see the behaviour]
This happen after the last scheduler update to version. 3.3.4

In my case I have several schedule items with different tags.

I have a script that provide a list of schedule switches (with a specific tag) to be turned on. 
When the script iterates the list, only the first element (the {{repeat.item}} scheduler switch) turns on but an error **"object NoneType can't be used in 'await expression"** is raised.

In the previous version was working fine. The problem seems related to scheduler switches only (working fine with any other switch in the house)

Here is the script fragment in yaml to reproduce (see the attached image with the script trace)

alias: myscript
sequence:
  - repeat:
      for_each: >-
        {{ states.switch  | selectattr('object_id', 'match', 'schedule') |
        selectattr('attributes.tags', 'contains','mytag')|
        map(attribute='entity_id') | list }}
      sequence:
        - service: switch.turn_on
          metadata: {}
          data: {}
          target:
            entity_id: "{{ repeat.item }}"
          enabled: true
description: ""

---------
any help is appreciated.
Thanks
Dario

![image](https://github.com/nielsfaber/scheduler-component/assets/342627/36ee14b2-e971-4a23-b770-4865511e5ccf)

**Comment by dc911x** [comment]
I can confirm this, my cover opening schedules gives the same error. Even when toggling on/off.
The bellow is what is shown in the log viewer:

`    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/scheduler/switch.py", line 458, in async_turn_off
    await self.coordinator.async_edit_schedule(
TypeError: object NoneType can't be used in 'await' expression`

**Comment by nielsfaber** [comment]
Ouch, this seems 100% related to a change I made in the 3.3.4 release.
I will make a fix for this tomorrow (I’m not at home today).

**Comment by nielsfaber** [comment]
This is now resolved in the v3.3.5 release

**Comment by mobilifone** [comment]
Thanks!
Dario
