### ISSUE TITLE
scheduler doesn't work anymore since last update

### ISSUE THREAD

**Issue by DirkScheumann** [nielsfaber/scheduler-component#370]
Hi, sine the last update to 3.3.5 scheduler doesn't work any more. I am running home assistant core 2022.2.7
 
The error I am getting in HA is:

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.config_entries
Source: custom_components/scheduler/__init__.py:64
Integration: Scheduler (documentation, issues)
First occurred: 23:29:42 (1 occurrences)
Last logged: 23:29:42

Error setting up entry Scheduler for scheduler
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 327, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/scheduler/__init__.py", line 64, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, [PLATFORM])
AttributeError: 'ConfigEntries' object has no attribute 'async_forward_entry_setups'

Do you have an idea what's wrong?
Is it because of ma HA version 2022.2.7?

-Dirk

**Comment by nielsfaber** [comment]
> Is it because of ma HA version 2022.2.7?

Yes. You should either update HA or use older version of the scheduler integration.
