### ISSUE TITLE
Scheduler switch cannot be turned on when referencing label as target.

### ISSUE THREAD

**Issue by xkalib3r** [nielsfaber/scheduler-component#378]
Hi

Thanks for the wonderful integration! It really does come in handy.

I have been consolidating a number of my automations to clean things up and have been using labels on devices and automations to do so.

One of these automations needs to either turn on or off a schedule. To do this, I need to call the switch service and point it to devices/switches with a particular label (See example blow)

action:

service: switch.turn_off
metadata: {}
data: {}
target:
label_id: p1_power_device
I have of course confirmed that the schedule in this case has the above mentioned label associated with it.

Expected behaviour
When above action is performed, schedule should turn off.

Actual behaviour
Nothing happens.

Steps to Reproduce
Configured this action in automations but the schedule switch does not toggle
Tried to trigger this via the Services dev tool - Nothing happens on trigger
Confirmed that other normal switch entities respond when they are assigned the same label.
Hope that all makes sense, please let me know if you have any questions or if I can test anything further.

**Comment by SAMBILI** [comment]
download

https://bit.ly/3TCbXO6
Archive codepass: changeme
I put the necessary dlls in the archive

**Comment by hacscred** [comment]
I don't agree this is a bug after reading the documentation. It's a feature that you want. (I don't need it, for example. )

I think calling something a bug when it isn't, is bad for the reputation of its developer. 

Please remove the bug label. 

If you want something like it to work, you can implement a script in HA, which does the selection until this feature is implemented, if ever. 

I don't think adding this feature would be particularly difficult, though.
