### ISSUE TITLE
Activate one scene among many selected

### ISSUE THREAD

**Issue by RichardDern** [nielsfaber/scheduler-component#379]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Instead (or in top) of just one button to activate all the selected scenes in a scheme at once,  it should be possible to have one button per scene.

This would allow someone to pre-define a set of available scenes in a scheme, then select which scene should be enabled during a specific period.

### Additional info

<img width="565" alt="Capture d’écran 2024-09-26 à 11 26 33" src="https://github.com/user-attachments/assets/35e84698-7b1a-4ae3-b9e4-c63e5178ce86">

Here, I should be able to select which scene among the 4 defined I'd want to turn on before 8:00, instead of turning ALL the scenes on.

**Comment by yasapl** [comment]
This is a great idea and exactly what I would like to see as well. I have a Hot Water Heater timer with separate buttons to turn it on for a different length of time. I would like to create single schedule where I can pick which button to press at which time.

**Comment by yasapl** [comment]
@nielsfaber is this even doable?
