### ISSUE TITLE
Disable all/some scheduled actions, vacation mode

### ISSUE THREAD

**Issue by TRon993** [nielsfaber/scheduler-component#38]
Hi, couldn't find anything related so I thought I'll open this feature request.

I'm on vacation in the foreseeable future and would like to disable/suspend all/some of the schedules I planned.

I've tried writing something in ha to achieve this but couldn't find a place to hook in. I've tried to disable/stop all schedules with a single switch but that didn't work.

So, it would be nice to have a on/off switch for each (and/or all) scheduled item.

Thanks for the great work, loving it so far ;)

BR

**Comment by KTibow** [comment]
A vacation mode can be achieved using Home Assistant scenes, because each schedule is just a switch.

**Comment by TRon993** [comment]
Ah ok, didn't know that. I haven't used scenes so far but I can surely give it a try. I just wanted to avoid to write down / c&p the 50something scheduled entries, especially as they aren't that good readable... So I thought I can make use of the globbing like the recorder component supports it. Doesn't seem to be the case with automations...

Anyways, I'll check that out. Thought it would be a nice feature 👍

**Comment by nielsfaber** [comment]
I agree something like this is needed!
Or the switches should come back to the overview page (I kind of miss them)..
What would you like to see added for this?

**Comment by KTibow** [comment]
Maybe something like the entities card:
![image](https://user-images.githubusercontent.com/10727862/95785681-0ba0b100-0c8b-11eb-81cb-3bdf4579b31c.png)

**Comment by nielsfaber** [comment]
You mean a master switch?
Would be very easy to add.
But I guess when going for a holiday you don’t want to turn off all schedules necessarily..

**Comment by TRon993** [comment]
Hi, a master switch would do for me :)

Maybe one could also say: turn off all schedules for .... Time. Or between this date and another? Like a planned down time so to speak.

I don't want to delete/touch all items...

Thanks for looking into this!

**Comment by nielsfaber** [comment]
Time to clean up old issues.. Please re-open if the issue is not resolved.
