### ISSUE TITLE
input boolean not selectable as option

### ISSUE THREAD

**Issue by rudiratlos** [nielsfaber/scheduler-component#381]
Hi, i want to use a switch variable (on/off) as an selectable sensor in the option tab.

e.g. if boolean variable named 'HeatingControl' is on, then use schedule. if off, then do. not use the schedule

**Comment by hacscred** [comment]
No idea what you mean, but schedules already are switches, so you can just make a template sensor.

**Comment by nielsfaber** [comment]
@rudiratlos Make sure to include the input_boolean entity in the card configuration. Then you can create a condition to a schedule so it only runs when the input_boolean is on.
Note that this is not the place to ask for support.
