### ISSUE TITLE
STATE_ALARM_TRIGGERED was used from scheduler, this is a deprecated constant

### ISSUE THREAD

**Issue by ColinRobbins** [nielsfaber/scheduler-component#388]
The following is reported in the log file, after upgrading to HA 2024.11.0

### Checklist
- [X] I checked for similar existing issues (both open and closed) before posting.
- [X] I am running the latest version.

### Expected behavior
[What you expected to happen]
No error

### Actual behavior
[What actually happened]
error message produced...

```
Logger: homeassistant.const
Source: helpers/deprecation.py:222
First occurred: 20:09:38 (1 occurrences)
Last logged: 20:09:38

STATE_ALARM_TRIGGERED was used from scheduler, this is a deprecated constant which will be removed in HA Core 2025.11. Use AlarmControlPanelState.TRIGGERED instead, please report it to the author of the 'scheduler' custom integration
```
### Steps to Reproduce
[Explain how to see the behaviour]

**Comment by ColinRobbins** [comment]
Thanks for fixing this.    
When do you plan to make a release so HA can pick up the latest version?

**Comment by nielsfaber** [comment]
@ColinRobbins Today 🙂  
Note that this is only a warning that something will break in a year from now.
