### ISSUE TITLE
Need Time Scheme with sunrise/sunset times

### ISSUE THREAD

**Issue by booroondook-eng** [nielsfaber/scheduler-component#390]
I have 11 TRVs on my radiators at home.
And I want to change their target temperatures twice a day: at sunrise and at sunset.
The Time Scheme is a very convenient tool for creating a daily schedule, but it does not support sunrise and sunset times. It only supports fixed times.
On the other hand, I can use one-time solar actions to solve my problem, but then I would have to create 22 schedules for my 11 TRVs.

Could you please add solar times to the Time Scheme?

**Comment by nielsfaber** [comment]
Scheduler does support sunrise and sunset time (also with offset).
Just click on the balloon marking start/end time of a slot to configure it.

**Comment by booroondook-eng** [comment]
> Scheduler does support sunrise and sunset time (also with offset). Just click on the balloon marking start/end time of a slot to configure it.

I know it. But I ask to add this feature in future releases.
