### ISSUE TITLE
v3.3.8 does not install on HA 2024.10.x

### ISSUE THREAD

**Issue by lamixer** [nielsfaber/scheduler-component#393]
Probably not exactly a bug, but I just wanted to check that it's really correct that if v3.3.8 were installed on a HA2024.10.x system it would cause a problem?

I like to wait before doing HA upgrades, so I haven't done 2024.11 yet. This way any integrations that need to be updated to be compatible have time to do so and I can install them before I upgrade.

You seem to have made a minor update for HA2024.11 in v3.3.8 but I cannot install that version due to you setting a minimum HA version of 2024.11 for v3.3.8.

### Expected behavior
Install latest version on second to last HA version

### Actual behavior
Can only install latest version on latest HA version

### Steps to Reproduce
Attempt to accept update for v3.3.8 on HA2024.10.4, does not install stating minimum version is 2024.11.0

**Comment by z-master42** [comment]
Ready #389.

**Comment by lamixer** [comment]
Very intentional then! Thanks.
