### ISSUE TITLE
Allow to disable version display in scheduler card

### ISSUE THREAD

**Issue by peteh** [nielsfaber/scheduler-component#394]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Either remove or give the option to remove the version from the schedule card display to allow the user to have a clean look. The information is irrelevant for any dashboard. 

![image](https://github.com/user-attachments/assets/3697ad92-c33f-4a5f-a130-dbf045ace560)

### Additional info
A simple switch would be ok in the card settings. Default can stay enabled but please give me an option to remove it. 

Small Update: 
If found that HACS proposes pre-release updates by default, thus that's why I updated to beta version. I rolled back and the version info is not visible anymore. I enabled HACS to not provide pre-releases anymore. 

Not sure if this feature request is valid anymore then. Let me know what you think.

**Comment by z-master42** [comment]
I don't have that. Is this possibly because a beta version is being used?
