### ISSUE TITLE
Daiking airco are not seen by the component as climate

### ISSUE THREAD

**Issue by rploeg** [nielsfaber/scheduler-component#396]
My daikins are not seen anymore as climate within this component. Within HA the daikins have a climate entity:

<img width="564" alt="image" src="https://github.com/user-attachments/assets/1a810ef0-599c-4b00-98d9-ff09542d0128">

and dont' see the aircos back in the card:

<img width="577" alt="image" src="https://github.com/user-attachments/assets/4e2a252a-bd9a-444b-9d03-ada91328b890">

**Comment by benbox69** [comment]
I have the same issue with my Versatile thermostats that are not viewed.

**Comment by nielsfaber** [comment]
Please check your card configuration. You need to edit the card settings and make sure all climate entities are included.

**Comment by benbox69** [comment]
> Please check your card configuration. You need to edit the card settings and make sure all climate entities are included.

My bad, forgot that step. It works perfectly!
