### ISSUE TITLE
Set temperature with 0.5 degrees

### ISSUE THREAD

**Issue by menloperk** [nielsfaber/scheduler-component#411]
### Checklist
- [x] I checked for similar existing requests (both open and closed) before posting.
- [x] My request is generic, other users may benefit from it too.

### Proposal
Please allow to set temperature with 0.5 degrees intervals

### Additional info
Self-explanatory

**Comment by nielsfaber** [comment]
Scheduler should use the step size that is advertised by your climate entity. Please share the properties of your entity (see developer tools -> states).

**Comment by menloperk** [comment]
I see, nice. It's set to 1 degree indeed. I will need to check with Daikin integration then...
