### ISSUE TITLE
Generic thermostat issue with Heat/Turn Off

### ISSUE THREAD

**Issue by nelim** [nielsfaber/scheduler-component#42]
Hello,
I have issue setup scheduler to switch between Heat and Turn Off
Posting screenshots below.
Generic Thermostat, which is working fine, but Scheduler only set_temperature for hvac_mode: heat to 23, without switching mode with set_hvac_mode: heat
Is this normal behavior and  how can I use Scheduler to just turn off and turn back on General Thermostat ?

- service: set_hvac_mode
  entity: climate.stove
  hvac_mode: 'off'
- service: set_temperature // Shouldn't this also set_hvac_mode to heat, not only changing temperature ?
  entity: climate.stove
  hvac_mode: heat
  temperature: 23

Thanks in advance.

PS. Otherwise, everything else is OK, i'm using your Scheduler with another MaxCube thermostat and works find, triggering OK, the problem is General Thermostat does not have Auto or On mode, just Heat and Turn Off
![Screenshot from 2020-10-30 20-01-57](https://user-images.githubusercontent.com/3601587/97741156-fdf08580-1aea-11eb-970c-a6202187153d.png)
![Screenshot from 2020-10-30 20-01-34](https://user-images.githubusercontent.com/3601587/97741181-0648c080-1aeb-11eb-81bb-1f4115baf1dd.png)
![Screenshot from 2020-10-30 20-02-31](https://user-images.githubusercontent.com/3601587/97741194-0a74de00-1aeb-11eb-82cc-f0122036dc97.png)

**Comment by nielsfaber** [comment]
I'm not sure what is the problem exactly.

> Generic Thermostat, which is working fine, but Scheduler only set_temperature for hvac_mode: heat to 23, without switching mode with set_hvac_mode: heat

In your actions list i see the complete service call, which sets `hvac_mode: heat` and `temperature: 23`.
Is this wrong?

**Comment by nelim** [comment]
It only sets temperature to 23 for hvac_mode heat, but does not switch mode to Heat.

**Comment by nielsfaber** [comment]
okay.
That sounds more like a problem with your thermostat then.
Did you try making normal service call?
I mean, go to Developer tools -> Services
And then choose `set_temperature`
with the hvac_mode and temperature as service_data

Does this work?
Because that's what scheduler does..

**Comment by nelim** [comment]
> okay.
> That sounds more like a problem with your thermostat then.
> Did you try making normal service call?
> I mean, go to Developer tools -> Services
> And then choose `set_temperature`
> with the hvac_mode and temperature as service_data
> 
> Does this work?
> Because that's what scheduler does..
It is working just fine, but only Set Temperature of Mode Heat to 21/22/23 , but not switching from Off to Heat mode.
How can i Turn back Generic Thermostat from Off to Heat with Scheduler ?
![Screenshot from 2020-10-30 20-18-23](https://user-images.githubusercontent.com/3601587/97742557-1e214400-1aed-11eb-8217-70406ae0ae4c.png)

**Comment by nelim** [comment]
service: set_temperature --> this one change temperature of heat mode to 23 (ot whatever) without switching thermostat mode from OFF to Heat
entity: climate.stove
hvac_mode: 'heat"
temperature: 23

service: set_hvac_mode --> this one turn thermostat from Off to Heat
entity: climate.stove
hvac_mode: 'heat"

Both work from developer tools, but how can i make set_hvac_mode:  'heat' from Scheduler, it only change temperature ?

**Comment by nielsfaber** [comment]
If you really want it, you can do this:
```
customize:
  climate.stove:
    actions:
      - service: climate.set_hvac_mode
         name: set hvac mode manually
         variable:
           field: hvac_mode
           options:
             - value: off
                icon: power
             - value: heat
                icon: flame
```

But the idea is that HVAC_mode is automatically switched when using the set_temperature action.
That's why it is shown in HA as an option for the set_temperature service (and that option is set by scheduler).
It seems that your climate entity has a limitation here.

**Comment by nelim** [comment]
Sorry, it is not general but generic thermostat :)
  - platform: generic_thermostat
And yes.. i've tried with maxcube thermostat, if you are Off and set_temperature, it turn it back to heat.. but on generic thermostat it does not work, i'm also using Slider from card and thermostat always stay at Off, no matter i'm changing temperature, will try with that customize (i'm not sure it can work ont generic_thermostat) and will write you back.
Thanks in advance.
https://www.home-assistant.io/integrations/generic_thermostat/

**Comment by nelim** [comment]
Do I need to post this on "scheduler-card" now?

Modes not show up for variable hvac_mode, can you help please?
I also tried with example from github - does not work also i can choose "set mode" but nothing shows up after

customize:
  climate.stove:
    name: My thermostat
    icon: thermometer
    actions:
      - service: set_hvac_mode
        name: Set mode
        icon:
        variable:
          field: hvac_mode
          name: Operation mode
          options:
            - value: heat
              icon: fire
            - value: cool
              icon: snowflake
            - value: 'off'
              icon: power
Maybe there is problem with Generic Thermostat on scheduler-card also?

![Screenshot from 2020-10-30 21-34-18](https://user-images.githubusercontent.com/3601587/97749423-b4f2fe00-1af7-11eb-9720-c6e46b2cdea1.png)
![Screenshot from 2020-10-30 21-38-34](https://user-images.githubusercontent.com/3601587/97749793-57ab7c80-1af8-11eb-871a-f779812393d4.png)

**Comment by nelim** [comment]
Ok, looks like there is a bug in Generic Thermostat, i cannot set temperature and change mode with one action/call and need 2 separate.
Thanks, i'm closing this.

**Comment by andreipopovici** [comment]
@nelim Could you expand on how you fixed or got around the Generic Thermostat bug? I am seeing the same issues.

**Comment by nielsfaber** [comment]
I see that the thermostat doesn't check for the `hvac_mode` parameter in the `set_temperature` service:
https://github.com/home-assistant/core/blob/8868028dcdc99b5272cb100f26367eb785b426ef/homeassistant/components/generic_thermostat/climate.py#L342

The fix is quite easy, it's a matter of calling `async_set_hvac_mode` as well (which is defined 10 lines above it), with the provided `ATTR_HVAC_MODE`.

I recommend to make a PR with this change or open an issue about it in HA/core.

**Comment by nelim** [comment]
> @nelim Could you expand on how you fixed or got around the Generic Thermostat bug? I am seeing the same issues.

@andreipopovici workaround, i'm not turning it off, scheduler just switching temperature and i'm using 17 instead of turn off :)

@nielsfaber thanks :)
