### ISSUE TITLE
Set temp. does not seems to work on group climate

### ISSUE THREAD

**Issue by JSteunou** [nielsfaber/scheduler-component#43]
Hi @nielsfaber 

opening the issue here rather in the card repo because I do not think this is UI related.

I'm using [climate group](https://github.com/daenny/climate_group) to group several eTRV together, it works very well in normal lovelace climate card, but the scheduler does nothing and I do not see errors in log :/

**Comment by nielsfaber** [comment]
And you expect me to be able to help you without any info?

**Comment by JSteunou** [comment]
What info is missing and could help you?

**Comment by nielsfaber** [comment]
Couple of things you could share:

- Attributes of your climate group entity (See Developer Tools -> Entities)
- Attributes of the schedule entity that does not work (See Developer Tools -> Entities)
- Details from history / logbook of schedule entity + climate group entity at the time when schedule should have triggered

Please be aware that you are using a custom_component.. It could be poorly implemented.
There is no documentation, so changes are that i can give you no support..

Consider using a normal [group](https://www.home-assistant.io/integrations/group/).
It is tested with the scheduler..

**Comment by JSteunou** [comment]
Here the attribute from the climate group created with the custom_component

```yml
hvac_modes:
  - auto
  - 'off'
  - heat
min_temp: 7
max_temp: 35
current_temperature: 19.2
temperature: 18
friendly_name: eTRV Living
supported_features: 1
```

here the attributes when using a *native* group

```yml
entity_id:
  - climate.thermostat_39
  - climate.thermostat_28
order: 0
friendly_name: Thermo Living Group
```

I cannot use this one in a lovelace card, it just have a state on/off. HA is moving group of *something* to *something* but with platform group, like [light group](https://www.home-assistant.io/integrations/light.group/) over cover group. But they did not do yet the climate group.

here the attributes of the scheduler

```yml
entries:
  - 0DT0000T0530A0
  - 0DT0530T2230A1
  - 0DT2230T0000A2
actions:
  - service: set_temperature
    entity: climate.etrv_living
    hvac_mode: heat
    temperature: 18
  - service: set_temperature
    entity: climate.etrv_living
    hvac_mode: heat
    temperature: 20.5
  - service: set_temperature
    entity: climate.etrv_living
    hvac_mode: heat
    temperature: 19
next_trigger: '2020-11-03T22:30:00+01:00'
friendly_name: 'Schedule #9313bc'
icon: 'mdi:calendar-clock'
```

I think the issue could be setting the `hvac_mode: heat` because my eTRV only supports `auto`. The group might be stricter and does not allow the command. I will check the log to see if I find something.

**Comment by JSteunou** [comment]
Ok, that's it 

```
Error executing service: <ServiceCall climate.set_temperature (c:e8c9683ee82dab6172187d03996d6122): hvac_mode=heat, temperature=25.0, entity_id=['climate.etrv_living']>

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1464, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 544, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/climate_group/climate.py", line 218, in async_set_temperature
    await self.async_set_hvac_mode(hvac_mode)
  File "/config/custom_components/climate_group/climate.py", line 261, in async_set_hvac_mode
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1448, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1483, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 482, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 519, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/deconz/climate.py", line 115, in async_set_hvac_mode
    await self._device.async_set_config(data)
  File "/usr/local/lib/python3.8/site-packages/pydeconz/deconzdevice.py", line 30, in async_set_config
    await self.async_set(field, data)
  File "/usr/local/lib/python3.8/site-packages/pydeconz/api.py", line 112, in async_set
    await self._request("put", field, json=data)
  File "/usr/local/lib/python3.8/site-packages/pydeconz/gateway.py", line 106, in request
    _raise_on_error(response)
  File "/usr/local/lib/python3.8/site-packages/pydeconz/gateway.py", line 220, in _raise_on_error
    raise_error(data["error"])
  File "/usr/local/lib/python3.8/site-packages/pydeconz/errors.py", line 58, in raise_error
    raise cls("{} {}".format(error["address"], error["description"]))
pydeconz.errors.RequestError: /sensors/28/config/mode parameter, mode, not available
```

the most important part is `pydeconz.errors.RequestError: /sensors/28/config/mode parameter, mode, not available`

The only thing I do not understand his that scheduler for individual climate works very fine, they also have the `hvac_mode: heat` so they should trigger the same error but instead they work very fine.

**Comment by nielsfaber** [comment]
From the logging, it's pretty clear that the problem is caused by the `climate_group` component.
The `climate_group` entity shows `heat` in the list of supported `hvac_modes`.
So it's claiming that all entities in the group support this mode.
But when scheduler is calling the service, the Deconz integration reports that this entity does not support `hvac_mode: heat`.

You're posting an issue in the wrong component.
This is a bug in `climate_group`.

I'm quite sure you will see the same issue if you try the service call yourself.
Try to execute [set_temperature](https://www.home-assistant.io/integrations/climate/#service-climateset_temperature) with `hvac_mode:heat` and some `temperature`.
You can do this via Developer Tools -> Services.

**Comment by JSteunou** [comment]
Yeah I ve already seen this issue, but again the weirdest is that all my climate are the same, `heat` is in all list, all schedulers set temperature *and* heat mode, but only the group raise the error from pyconz.

**Comment by nielsfaber** [comment]
Ask for help somewhere else please.
Its not related to scheduler..

**Comment by JSteunou** [comment]
This specific bug is not indeed. Using group did the trick and allow me to create a scheduler with `set_temperature` only. Why on other climates I can only select *heat* and not *set temperture* only. I'm pretty sure I could do it in previous version.

Anyway, sorry to bother you, seems to be the wrong day...

**Comment by nielsfaber** [comment]
> Anyway, sorry to bother you, seems to be the wrong day...

I'm not bothered 😄 
I mean _literally_, ask somewhere else.
It looks like somewhere between the Deconz implementation and the climate group there is a compatibility issue.
So we can keep discussing it but the solution is somewhere else, I will not be able to solve this problem. 
There's no bug in the scheduler..

You can try adding a 'legacy' action to make the climate group (possibly) work:
```
customize:
  climate:
    actions:
      - service: set_temperature
         name: legacy set temperature
         variable:
           field: temperature
           min: 10
           max: 30
```
But i cannot fix this on the scheduler side.
I cannot predict which integrations will fail when sending the command matching with their advertised features.
Also, service-calls in HA are fire-and-forget, meaning that i get no feedback whether the command was successful or not.

Good luck!

**Comment by JSteunou** [comment]
Thank you.

I found another way through HA customization, overriding modes to `["auto"]` only.

I also report the issue to deconz / pyconz.
