### ISSUE TITLE
Sun based actions

### ISSUE THREAD

**Issue by hugodelaroza** [nielsfaber/scheduler-component#47]
Hi. I think this work is really good, the card is aolmost perfect.

It would be even better if you could set sunrise and sunset as the trigger for the actions, not olny times. Even more, you could configure a light to turn on when sun sets and turn off at 23:00.

Thanks again for yor work!!

**Comment by KTibow** [comment]
You can already do that. Try looking in the forms to see how. But this isn't anything new, it's been in there for awhile.

**Comment by KTibow** [comment]
Consider closing?

**Comment by hugodelaroza** [comment]
Sorry, you´r right. 

The card is PERFECT!!

Thanks a lot!!
