### ISSUE TITLE
Sort entities inside card

### ISSUE THREAD

**Issue by hugodelaroza** [nielsfaber/scheduler-component#48]
Hi. I think it wolud be great to change the way timers are sorted inside the card.

By now, my timers are sorted this way:

in first place the turn on actions
in second place, the turn off actions
it doesn´t matter if the envolved entitie is the same or not

I think it would be better to group in first place by entities, and in second place by actions (on or off), so you can have all timers related to a entitie agrouped together

Thanks a lot

**Comment by KTibow** [comment]
Use schemas if you want them together. I think it would make the card more confusing if it was this way, IMO

**Comment by nielsfaber** [comment]
Grouping by entity will not be made.
It is very depending on usage whether it would improve structure of make things worse.

In the future, I want to create the possibility to create a schedule for multiple entities.
This would also create conflicts here.

Why do you have a long list of schedules?
I only have like 10, and this is very manageable..

**Comment by KTibow** [comment]
Consider closing?
