### ISSUE TITLE
Generic Thermostat Schedule

### ISSUE THREAD

**Issue by ITMarco93** [nielsfaber/scheduler-component#49]
Hi, I am quite new to the HA scene.

My problem is very simple... I was trying to add a schedule for a "generic thermostat" entity.
When | create a schedule for turning on the thermostat via the Scheduler Card , this is what is created
![image](https://user-images.githubusercontent.com/48054188/98391746-58439600-2057-11eb-8709-246c5c9ec552.png)
as you can see, the "on" action (A1) is a _"set_temperature"_ which doesn't actually _"turn_on"_ the thermostat, neither it does _"set_hvac_mode"_ to _heat_.
I don't know if this worked correctly in previous versions of HA (I'm using version 0.117.4)...

A "workaround" I could apply to the issue is changing A1 to a _"turn_on"_ or a _"set_hvac_mode"_, but I would lose the possibility to set the temperature via the (**super cool**, btw) Scheduler Card.

If the _"set_temperature"_ behavior doesn't change, is there a way around?
Also I don't now if this applies to a physical thermostat, since I don't have one (not a smart one, at least)

Maaaaany thanks

**Comment by ITMarco93** [comment]
Of course I could also fire a script which sets the temperature and turns on the thermostat, but again, I wouldn't be able to set the temperature via the Scheduler Card, not even with a variable... I think

**Comment by nielsfaber** [comment]
Check [here](https://community.home-assistant.io/t/scheduler-card-custom-component/217458/893?u=neliss), also his other posts.

And [here](https://github.com/nielsfaber/scheduler-card#my-climate-entity-does-not-work-when-i-create-a-schedule-to-change-the-temperature).

**Comment by KTibow** [comment]
Consider closing?

**Comment by ITMarco93** [comment]
Ok, then I solved just creating a custom component based on generic_thermostat, that turns on when setting the temperature.

Thank you very much
