### ISSUE TITLE
scheduler/add Service not found

### ISSUE THREAD

**Issue by derekoharrow** [nielsfaber/scheduler-component#50]
Hi
I'm running HASS 0.117.5 in Docker and just installed Scheduler and the Lovelace card.

When I try to add a schedule I get the error that scheduler/add Service not found.

I've checked the issues here and have ensured I have enabled the sun integration. I cannot see the scheduler integration under configuration->integrations, but I can see it under HACS->Integrations.

I do see the following message in my HASS log file:
`2020-11-11 10:57:11 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for scheduler which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.`

Any ideas?
Thanks

**Comment by nielsfaber** [comment]
Looks like you're VERY close to success 😄 

> I cannot see the scheduler integration under configuration->integrations

This is a problem.
You will need to add it before things can work.

In integrations it should look roughly like this:
![Capture9](https://user-images.githubusercontent.com/16861605/98827698-71718b80-2437-11eb-9845-e635b3f6d403.PNG)

I assume you found the big orange + button on the bottom of the page?
Scheduler is not in this list?
![Capture10](https://user-images.githubusercontent.com/16861605/98827842-9cf47600-2437-11eb-8c7c-5604cd6e0833.PNG)


If so, then i think its a browser-caching issue.
Try in private mode or a different browser/device.
You're not the first who had problems with that.

**Comment by derekoharrow** [comment]
Doh! Now I feel dumb!

Thank you!

**Comment by KTibow** [comment]
Consider closing?

**Comment by nielsfaber** [comment]
Who needs a stalebot, if you can have a @KTibow Bot 😄 

@derekoharrow glad you fixed it. Please use our HA [thread](https://community.home-assistant.io/t/scheduler-card-custom-component/217458) for further questions. GitHub issues are only meant for reporting bugs + feature requests.
