### ISSUE TITLE
Scheduler services do not exist

### ISSUE THREAD

**Issue by roofuskit** [nielsfaber/scheduler-component#55]
No errors in the logs upon loading the component, but the scheduler services are not created.

Home Assistant Core 0.117.6

**Comment by KTibow** [comment]
You need to add it via the UI. Clear your cache, go to config, go to integrations, press "new integration", and press "scheduler".

**Comment by roofuskit** [comment]
> You need to add it via the UI. Clear your cache, go to config, go to integrations, press "new integration", and press "scheduler".

Well that's embarrassing. I thought it was describing adding it via HACS. That did the trick, thank you!
