### ISSUE TITLE
I can't install the addon. Help please.

### ISSUE THREAD

**Issue by uaparac** [nielsfaber/scheduler-component#57]
Hello I need help please.
I installed this addon with HACS and the component does not appear in the integration. I restarted HA. Then I tried it manually and still I don't see the Scheduler integration In HA Configuration> Integrations

I can't understand what's going on.

My machine 

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.12
hassio | true
host_os | HassOS 5.5
installation_type | Home Assistant OS
os_name | Linux
os_version | 5.4.74-v8
python_version | 3.8.6
supervisor | 2020.11.0
timezone | Europe/Lisbon
version | 0.117.6
virtualenv | false

**Comment by KTibow** [comment]
Clear your cache.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by uaparac** [comment]
solved it.
It's already working. Thanks
