### ISSUE TITLE
The percentage of opening / closing windows cannot be seen, in the Hebrew language the times are reversed

### ISSUE THREAD

**Issue by itsikba** [nielsfaber/scheduler-component#58]
![error](https://user-images.githubusercontent.com/44056773/99442158-9d05e180-2921-11eb-8008-0741c73a711d.png)

**Comment by itsikba** [comment]
1. the position slide is not showing
2. the time in Hebrew language is reversed

**Comment by nielsfaber** [comment]
I'm sorry but RTL reading mode is not supported.

**Comment by nielsfaber** [comment]
Could you make a list of things that should be changed in this card for RTL support?
If it is only few changes I can check if i can do it.
Ofcourse hebrew translation is needed as well..

**Comment by nielsfaber** [comment]
Closing due to no response.
