### ISSUE TITLE
service not found

### ISSUE THREAD

**Issue by Jeroen45** [nielsfaber/scheduler-component#59]
Hi,
Have the component installed, but got the message can not call scheduler/add service, not found 
Get this after editing scheluler card.
What am i doing wring?

thanks

**Comment by nielsfaber** [comment]
Every one or two days someone opens an issue with this question.

Could you check the closed issues list and find your answer?

**Comment by KTibow** [comment]
Consider closing?

**Comment by Jeroen45** [comment]
Yes i will sorry
