### ISSUE TITLE
New entities do not appear to choose

### ISSUE THREAD

**Issue by JaVier-Lloret** [nielsfaber/scheduler-component#60]
Maybe it's a bit silly but I can't find how to update the newly installed components.
I explain.
I had 2 climate control units and three lights, I installed a heater and two more lamps and the new ones do not appear to me to be able to choose them.
I have integrated these new entities in the climate.yaml and ligth.yaml files, but after restarting HA they do not appear in scheduler-component integration.
What am I doing wrong?

**Comment by KTibow** [comment]
You mean the scheduler-card? You need to use the scheduler-card for this, and configure it to show the entities you want. Ask over there. And use HACS to update them.

**Comment by nielsfaber** [comment]
I'm not sure what you mean.
There is nothing to configure in the scheduler-component.

In the scheduler-card you need to choose which entities you want to show up (either via the UI editor or via YAML `include`).

**Comment by JaVier-Lloret** [comment]
OK. Thanks I will open a new issue in scheduler-card section.
