### ISSUE TITLE
Service does not show in HA

### ISSUE THREAD

**Issue by cdenfert** [nielsfaber/scheduler-component#61]
Install via Hacs on HA .118.1, no service appear. So schedular card can't add schedule because service is not found.

**Comment by nielsfaber** [comment]
Follow step 3: https://github.com/nielsfaber/scheduler-component#step-3-add-integration

**Comment by cdenfert** [comment]
do it already. Compnent appear in hacs, restart HA and no service scheduler.* available

**Comment by cdenfert** [comment]
![image](https://user-images.githubusercontent.com/72680798/99836075-d9c21a80-2b65-11eb-83eb-6334f406fba8.png)

**Comment by nielsfaber** [comment]
No, HACS is step 1.
Please read the instructions properly.

**Comment by cdenfert** [comment]
look at the screenshot, component is properly installed.

**Comment by KTibow** [comment]
No it isn’t. You need to go to the Integrations page in HA config in the sidebar.

**Comment by cdenfert** [comment]
oh sorry, i didn't understand that, thank you very much.
