### ISSUE TITLE
Items trigger twice

### ISSUE THREAD

**Issue by tribut** [nielsfaber/scheduler-component#69]
Scheduler actions seem to trigger twice: At the specified time and then again one minute later.

I have a simple scheduler item, which turns a bunch of christmas lights (a light group) on and off at specific times during the day.
When I decide that I don't want it to turn on/off yet and hit the light switch manually, the second action at [configured time+1minute] will undo that a few seconds later.

Example schedule:
~~~~
"entity_id": "switch.schedule_92739c",
"state": "waiting",
"attributes": {
    "entries": [
        "15DT0600T0830A0",
        "15DT0830T1600A1",
        "15DT1600T2200A0",
        "15DT2200T0000A1"
    ],
    "actions": [
        {   
            "service": "switch.turn_on",
            "entity": "group.weihnachtsbeleuchtung"
        },  
        {   
            "service": "switch.turn_off",
            "entity": "group.weihnachtsbeleuchtung"
        }
    ],
    "next_trigger": "2020-12-07T16:00:00+01:00",
    "friendly_name": "Weihnachtsbeleuchtung Wochentags",
    "icon": "mdi:calendar-clock"
},
"last_changed": "2020-12-07T07:31:00.009555+00:00",
"last_updated": "2020-12-07T07:31:00.009555+00:00",
~~~~

And this is how it looks "in action":
![Screenshot from 2020-12-07 08-46-20](https://user-images.githubusercontent.com/719105/101323319-c783f400-3868-11eb-8208-4c17606a5c83.png)

Version Information: HA 0.118.5, Scheduler component v2.1.1 (installed via HACS)

**Comment by KTibow** [comment]
Odd. Can you turn on debug logging and move this issue to scheduler-card?

**Comment by nielsfaber** [comment]
This behaviour makes sense to me if I look at the code.
I will see if I can fix it, thanks for reporting.

@KTibow this is actually a bug in the scheduler-component, so the issue belongs here.

**Comment by nielsfaber** [comment]
I tried to improve this behaviour.
Please try updating to v3.0.0, and test if the problem is solved now.

**Comment by tribut** [comment]
Couldn't reproduce the behavior today with scheduler v3.0.0, so I guess this is fixed. Thanks!
