### ISSUE TITLE
Brightness Light when "ON"

### ISSUE THREAD

**Issue by Balooforever** [nielsfaber/scheduler-component#70]
Hi,

I think it's not really an issues but more a new condition.

I want to move the brightness from a light when she is "ON" all day.

I don't know how I can do this, I can set Light "on" and brightness but I can't select the "Light ON" at condition.

Scheduled-component can do this ?

It's a really awesome good component !

And in French, the component for Light say "Alumer" but it's "Allumer" when ON

**Comment by KTibow** [comment]
As for the first part, try creating a template binary sensor. As for the last part, please create a new issue.

**Comment by nielsfaber** [comment]
See here: https://github.com/nielsfaber/scheduler-card#conditions
You should define the 'states' for a light entity (which are `on` and `off`), add them in `customize` (YAML-only / not in UI yet).
After configuring, the light entity should automatically show up in the conditions.

Note that I'm currently changing the conditions editor a bit. In the near future the customize will not be needed anymore.

Regarding translations: these are maintained by the community.
You can make changes to this file: https://github.com/nielsfaber/scheduler-card/blob/master/src/localize/languages/fr.json
Please don't create an issue for it, I will not process such requests.

**Comment by Balooforever** [comment]
Oups sorry for the on/off, I have read "scheduler-component" and not scheduler-card.

Thank a lot for your work !
