### ISSUE TITLE
24h options when picking time

### ISSUE THREAD

**Issue by infestdead** [nielsfaber/scheduler-component#71]
Not an issue, just a feature request or a suggestion. 

Currently if I want to set something at 00:30 I have to set it at 12:30am which is confusing to me. I know some people prefer am/pm, but also a lot of people prefer 24h notation.

**Comment by KTibow** [comment]
I believe this is determined by your browser/language.

**Comment by KTibow** [comment]
Also issues should be over at scheduler-card.

**Comment by nielsfaber** [comment]
I guess you have your HA account language at "English" instead of "English (GB)".
Changing it should fix the hour notation.

**Comment by infestdead** [comment]
That did the trick! Thanks!
