### ISSUE TITLE
Feature Request: "one-time" actions

### ISSUE THREAD

**Issue by martinhoess** [nielsfaber/scheduler-component#72]
The scheduler component and card works great! 

But what I miss which HA can't do (it's possible but not in an easy/nice way) are one-time actions, i.e. actions that are executed only once and don't repeat automatically (even Siri/Alexa can't do stuff like this).

e.g. there are situations in which I know that a room that is normally not heated should be heated but only once. So for example "do ... next Wednesday" or "do ... on 12.12.2020 at 13:15 clock"

It would be enough if the action deactivates itself afterwards, an option that the action deletes itself afterwards would be great but not necessary.

Is it possible to integrate such behavior in the scheduler component/card?

**Comment by KTibow** [comment]
Wrong place, post over here: https://github.com/nielsfaber/scheduler-card/issues
Which already has https://github.com/nielsfaber/scheduler-card/issues/161

**Comment by martinhoess** [comment]
> Wrong place, post over here: https://github.com/nielsfaber/scheduler-card/issues
> Which already has [nielsfaber/scheduler-card#161](https://github.com/nielsfaber/scheduler-card/issues/161)

yes and no ...  

I assumed that you have to make most of the changes in the integration ... the card doesn't have much logic of its own, right?

Also, https://github.com/nielsfaber/scheduler-card/issues/161 lacks the option to specify a fixed date and not a weekday (well, this could be seen as a feature request on it's own)

**Comment by nielsfaber** [comment]
I will add a feature for "self-destructive" schedules.
Such schedule will remove itself once the action has been triggered.

There is currently no option for creating a schedule that fires at a certain date.
The scheduler component is intended for weekly programs only.

**Comment by nielsfaber** [comment]
These are added in v3.0.0.
