### ISSUE TITLE
[feature] Show cause of state change in history

### ISSUE THREAD

**Issue by SamMousa** [nielsfaber/scheduler-component#74]
Since one of the more recent updates HA will show who or what changed the state of an element.

It would be great if this component added what schedule caused the state to change as well.

![image](https://user-images.githubusercontent.com/547021/101780358-c0721580-3af6-11eb-8fa0-0c30a90d8f50.png)

The most recent event in the screenshot was caused by schedule-component.

**Comment by KTibow** [comment]
Please post over at the scheduler-card. I've already made an issue there: https://github.com/nielsfaber/scheduler-card/issues/85

**Comment by SamMousa** [comment]
My bad, assumed this was for backend issues not related to the card.
