### ISSUE TITLE
Non working integration

### ISSUE THREAD

**Issue by dcharbonnier** [nielsfaber/scheduler-component#77]
I installed the scheduler with HACS, no error messages
I was able to add the integration still no issue, but it doesn't look like it's working properly, the card shows "Could not connect with the scheduler component." and on the logs, I can see "2020-12-19 22:23:23 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140506657820384] Received invalid command: scheduler" when I display the card.
I'm using `homeassistant/home-assistant:stable` (just updated) Home Assistant 2020.12.1
Can I activate some debug to give you more information?

**Comment by KTibow** [comment]
Try rebooting another time? Are you sure you went to integrations > add integration > scheduler?

**Comment by dcharbonnier** [comment]
rebooted many times (container restart), and yes I'm sure I added the integration after installing the extension, I got that it's two different steps. thanks

**Comment by KTibow** [comment]
Are you using beta for both of the card and component?

**Comment by iroQuai** [comment]
i recognize this, i have the same problem with both the master as the beta version!

**Comment by nielsfaber** [comment]
This error suggests that you are using v2.0.0(b) of the card:
 > "Could not connect with the scheduler component." 

It needs to be used in combination with v3.0.0(b) of the component.
Do you have this one installed?

**Comment by KTibow** [comment]
@iroQuai actually edited his comment 1 hour before you posted yours, @nielsfaber.
> Edit: sorry didn't read the docs well enough! Forgot to install the integration in main settings after installing the component in HACS. After restarting everything worked!

@iroQuai consider closing?

**Comment by iroQuai** [comment]
This isn't my issue.. just thought I had the same problem, but in my case everything worked after following the right instructions.

**Comment by KTibow** [comment]
🤦 
> This isn't my issue..

Oopsie, didn't notice that.

**Comment by KTibow** [comment]
@dcharbonnier what version are you using for the integration? What about the card's version?

**Comment by dcharbonnier** [comment]
version 3 release fixed my issue, thx

**Comment by patriciowallace** [comment]
I'll trying to use the schedule component 3.12 and the schedule card 2.12 and cant be connect

could not connect with the schedule component
Received invalid command: scheduler

any ideas how to resolve the issue ?

thx
Patricio

**Comment by nielsfaber** [comment]
@patriciowallace 
see here:
https://github.com/nielsfaber/scheduler-component#step-3-add-integration-to-ha-----this-is-a-step-that-a-lot-of-people-forget

I guess you did not set up the integration.
