### ISSUE TITLE
Bug: Enabling/Disabling schedule triggers underlying action

### ISSUE THREAD

**Issue by alex-tomin** [nielsfaber/scheduler-component#78]
Component version 3.0.0b
E.g. 
1. configure Climate Schedule via a card
2. Turn the thermostat off
3. Turn Schedule **off** (e.g. as a switch or using card)
4. => Thermostat **turns on**.!!!
Same behavior if I have thermostat off, but enable schedule -> thermostat turns on.
_Side effect:_
 If I reboot Home Assistant - all my climate thermostats are suddenly on.

_Expected behavior:_ 
   Thermostat should not be changed upon shedule enable/disable. 

Schedule example (from storage)
```
        "schedules": [
            {
                "schedule_id": "94c56e",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "07:30:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.kitchen_floor",
                                "service_data": {
                                    "hvac_mode": "off"
                                }
                            }
                        ]
                    },
                    {
                        "start": "07:30:00",
                        "stop": "21:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.kitchen_floor",
                                "service_data": {
                                    "hvac_mode": "heat"
                                }
                            }
                        ]
                    },
                    {
                        "start": "21:00:00",
                        "stop": "23:59:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_hvac_mode",
                                "entity_id": "climate.kitchen_floor",
                                "service_data": {
                                    "hvac_mode": "off"
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "Kitchen Schedule",
                "enabled": true
            },
```

**Comment by trusky77** [comment]
Same problem in my climate.

**Comment by nielsfaber** [comment]
In v3.0.0 (non-beta) I fixed a problem that caused the enabled/disabled state to be processed wrong in some circumstances.
Please update the component and test if it resolves the problem.

As for:
> Same behavior if I have thermostat off, but enable schedule -> thermostat turns on.
Side effect:
If I reboot Home Assistant - all my climate thermostats are suddenly on.

This is intended behaviour.
Please read the [documentation](https://github.com/nielsfaber/scheduler-card#timeslots) about this functionality.

**Comment by nielsfaber** [comment]
@alex-tomin Do you still experience undesired triggering of the scheduler actions?
Otherwise, please close this issue.

**Comment by alex-tomin** [comment]
I believe I do. But It may be related to interpretation of 
> This is intended behaviour.

Documentation says 

>If HA is restarted: the schedule will determine ***which timeslot is active***, and trigger this action immediately.

In the reported case it's triggered regardless of "active" timeslot. I tried after updated the component and card, and a climate which is behind _disabled_ schedule was triggered after reboot. Though seems not constantly reproducing. 

I can try to observe a bit more to see if there's a pattern

**Comment by alex-tomin** [comment]
I didn't notice the issue happening anymore. May I did something wrong after update - after reinstall and  a couple of reboots it works great. Closing it.
