### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by KTibow** [nielsfaber/scheduler-component#8]
Check out this checklist:
https://developers.home-assistant.io/docs/creating_component_code_review/
What's the next step based on it? Tests or another thing?

**Comment by nielsfaber** [comment]
the code is far from mature enough to be accepted by the HA dev team.
It needs some refactoring, and unit tests indeed.

**Comment by nielsfaber** [comment]
Time to clean up old issues.. Please re-open if the issue is not resolved.
