### ISSUE TITLE
After update no more Card

### ISSUE THREAD

**Issue by mupsje** [nielsfaber/scheduler-component#80]
Hello,

After updating to Home Assistant OS 5.9
And update the Hacs resp.

I also reinstalled both in Hacs already with no success

I get this failure.
Please advise ....

Thanks

![image](https://user-images.githubusercontent.com/46684538/103283512-0ecd5280-49d9-11eb-9eb8-c9995bf42a9a.png)

**Comment by nielsfaber** [comment]
Kun je eens naar Instellingen-> Logboek gaan en klikken op "Laad volledige logboek"
Staat er iets bij over de scheduler?
Kun je alle regels met custom_components.scheduler kopieren?

**Comment by mupsje** [comment]
Hallo Niels..

dit heb ik kunnen vinden.

File "/config/custom_components/scheduler/websockets.py", line 161, in
websocket_get_schedules
schedules = coordinator.async_get_schedules()
File "/config/custom_components/scheduler/__init__.py", line 136, in
async_get_schedules
config = item.async_get_entity_state()
File "/config/custom_components/scheduler/switch.py", line 270, in
async_get_entity_state
data.update(
AttributeError: 'NoneType' object has no attribute 'update'
2020-12-29 13:23:09 ERROR (MainThread)
[homeassistant.components.websocket_api.http.connection] [2917214120] Error
handling message: Unknown error
Traceback (most recent call last):
File
"/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py",
line 95, in async_handle
handler(self.hass, self, schema(msg))
File "/config/custom_components/scheduler/websockets.py", line 161, in
websocket_get_schedules
schedules = coordinator.async_get_schedules()
File "/config/custom_components/scheduler/__init__.py", line 136, in
async_get_schedules
config = item.async_get_entity_state()
File "/config/custom_components/scheduler/switch.py", line 270, in
async_get_entity_state
data.update(

[image:
https://drive.google.com/uc?id=1vP_m0Y6MJGalWJvxAk9yQUoQSePNlF6Y&export=download]


Totaal Installateur
Consult & Coaching HVAC/R/E

Advies Bureau installatie techniek



Maanstraat 17

6161TH, Geleen NL
Tel. +31615214643













Kvk: 80175023
BTW: NL003403186B22
ABN NR: NL57ABNA0625054342

*www.allreco.nl <http://www.allreco.nl>*


Op di 29 dec. 2020 om 13:34 schreef Niels Faber <notifications@github.com>:

**Comment by nielsfaber** [comment]
Lijkt erop dat er iets mis is in mijn code waardoor dit optreedt.
Heb je toevallig geüpgraded vanuit een oude versie van de scheduler? 
Of is het een nieuwe/schone installatie?

Ik heb zojuist een v3.0.1 uitgebracht, misschien dat het probleem weg is wanneer je update naar deze.
Probeer hem eens uit 🙂

**Comment by mupsje** [comment]
Hoi Niels

Ik heb inderdaad eerst de HACS update gedaan, daarna de core.
Daarna beide opnieuw herinstallatie gedaan.

Nu de update gedaan, herstart en teboor.
Helaas zelfde storing....

Sorry


Op di 29 dec. 2020 17:45 schreef Niels Faber <notifications@github.com>:

**Comment by nielsfaber** [comment]
Hmm jammer.
Zou je eens kunnen checken of de fout in de log hetzelfde is als eerst?
Kun je ook eens een uitdraai maken van de schedules die je hebt? 
Deze staan opgeslagen in .storage/scheduler.storage (.storage is een verborgen map in de HA config map).

**Comment by mupsje** [comment]
hoi Niels,

zoals gevraagd.
foutmelding in logboek zijn weg

{
    "version": 1,
    "key": "scheduler.storage",
    "data": {
        "schedules": [
            {
                "schedule_id": "6a6b7e",
                "timeslots": [
                    {
                        "start": "01:00:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "light.turn_off",
                                "entity_id": "light.keuken_verlichting",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "",
                "enabled": true
            },
            {
                "schedule_id": "13db28",
                "timeslots": [
                    {
                        "start": "02:00:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "light.turn_off",
                                "entity_id": "light.woonkamer_verlichting",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "",
                "enabled": true
            },
            {
                "schedule_id": "5b4521",
                "timeslots": [
                    {
                        "start": "01:00:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "switch.turn_off",
                                "entity_id": "switch.x10_cmd_a4",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "",
                "enabled": true
            },
            {
                "schedule_id": "767f15",
                "timeslots": [
                    {
                        "start": "18:30:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "light.turn_on",
                                "entity_id": "light.aqara_hub_0fe8",
                                "service_data": {
                                    "brightness": 15
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "",
                "enabled": true
            },
            {
                "schedule_id": "ff0ddc",
                "timeslots": [
                    {
                        "start": "08:00:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "light.turn_off",
                                "entity_id": "light.aqara_hub_0fe8",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "",
                "enabled": true
            },
            {
                "schedule_id": "71da33",
                "timeslots": [
                    {
                        "start": "06:15:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "light.turn_on",
                                "entity_id": "light.keuken_verlichting",
                                "service_data": {
                                    "brightness": 87
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "mon",
                    "tue",
                    "wed",
                    "thu",
                    "fri"
                ],
                "repeat_type": "repeat",
                "name": "",
                "enabled": true
            },
            {
                "schedule_id": "0575b1",
                "timeslots": [
                    {
                        "start": "06:15:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "light.turn_on",
                                "entity_id": "light.woonkamer_verlichting",
                                "service_data": {
                                    "brightness": 79
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": "",
                "enabled": true
            },
            {
                "schedule_id": "106a7d",
                "timeslots": [],
                "weekdays": [],
                "repeat_type": "repeat",
                "name": null,
                "enabled": false
            },
            {
                "schedule_id": "b7036c",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "06:19:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.woonkamer",
                                "service_data": {
                                    "temperature": 19.8
                                }
                            }
                        ]
                    },
                    {
                        "start": "06:19:00",
                        "stop": "09:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.woonkamer",
                                "service_data": {
                                    "temperature": 20.3
                                }
                            }
                        ]
                    },
                    {
                        "start": "09:00:00",
                        "stop": "16:01:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.woonkamer",
                                "service_data": {
                                    "temperature": 19.8
                                }
                            }
                        ]
                    },
                    {
                        "start": "16:01:00",
                        "stop": "23:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.woonkamer",
                                "service_data": {
                                    "temperature": 20.3
                                }
                            }
                        ]
                    },
                    {
                        "start": "23:00:00",
                        "stop": "00:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.woonkamer",
                                "service_data": {
                                    "temperature": 19.8
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "mon",
                    "tue",
                    "wed",
                    "thu",
                    "fri"
                ],
                "repeat_type": "repeat",
                "name": null,
                "enabled": true
            },
            {
                "schedule_id": "128d65",
                "timeslots": [
                    {
                        "start": "00:00:00",
                        "stop": "06:31:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.woonkamer",
                                "service_data": {
                                    "temperature": 19.8
                                }
                            }
                        ]
                    },
                    {
                        "start": "06:31:00",
                        "stop": "23:01:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.woonkamer",
                                "service_data": {
                                    "temperature": 20.3
                                }
                            }
                        ]
                    },
                    {
                        "start": "23:01:00",
                        "stop": "00:00:00",
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "climate.set_temperature",
                                "entity_id": "climate.woonkamer",
                                "service_data": {
                                    "temperature": 19.8
                                }
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "sat",
                    "sun"
                ],
                "repeat_type": "repeat",
                "name": null,
                "enabled": true
            },
            {
                "schedule_id": "43094d",
                "timeslots": [
                    {
                        "start": "06:14:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "switch.turn_on",
                                "entity_id": "switch.schakelaar",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": null,
                "enabled": true
            },
            {
                "schedule_id": "9dbfa7",
                "timeslots": [
                    {
                        "start": "00:58:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "switch.turn_off",
                                "entity_id": "switch.schakelaar",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": null,
                "enabled": true
            },
            {
                "schedule_id": "b4ecad",
                "timeslots": [
                    {
                        "start": "sunrise+01:30:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "light.turn_off",
                                "entity_id": "light.keuken_verlichting",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": null,
                "enabled": true
            },
            {
                "schedule_id": "318708",
                "timeslots": [
                    {
                        "start": "sunrise+01:30:00",
                        "stop": null,
                        "conditions": [],
                        "condition_type": null,
                        "actions": [
                            {
                                "service": "light.turn_off",
                                "entity_id": "light.woonkamer_verlichting",
                                "service_data": {}
                            }
                        ]
                    }
                ],
                "weekdays": [
                    "daily"
                ],
                "repeat_type": "repeat",
                "name": null,
                "enabled": true
            }
        ]
    }
}

[image:
https://drive.google.com/uc?id=1vP_m0Y6MJGalWJvxAk9yQUoQSePNlF6Y&export=download]


Totaal Installateur
Consult & Coaching HVAC/R/E

Advies Bureau installatie techniek



Maanstraat 17

6161TH, Geleen NL
Tel. +31615214643













Kvk: 80175023
BTW: NL003403186B22
ABN NR: NL57ABNA0625054342

*www.allreco.nl <http://www.allreco.nl>*


Op di 29 dec. 2020 om 20:44 schreef Niels Faber <notifications@github.com>:

**Comment by mupsje** [comment]
Hallo Niels,

Na een reset van een snaphot .
heb ik daarna alles geupdate
krijg ik nu dit te zien.

![image](https://user-images.githubusercontent.com/46684538/103401481-4529df80-4b49-11eb-9734-f0f9e39a0241.png)

**Comment by nielsfaber** [comment]
Dank voor de info!
Ik heb jouw storage file overgenomen (entity ID's aangepast naar bestaande) en zie hetzelfde gebeuren.
Dat is goed nieuws, want dat betekent dat ik eindelijk kan onderzoeken wat er nou mis gaat.
Ik hoop dat je nog even geduld kan opbrengen, ik hoop later deze week (wsl dit weekend) met een update te kunnen komen die het probleem verhelpt.
Ik hoop dat het leed te overzien is.

Bij voorkeur de configuratie even laten voor wat het is, dan kunnen we testen of de update alles verhelpt.

**Comment by nielsfaber** [comment]
Ik heb een nieuwe versie van de scheduler-component en scheduler-card gemaakt.
Als het goed is zul je na upgraden zien dat er nog 1 "defective entity" overblijft, de andere zouden weer moeten werken.
In jouw storage file staat een schedule die niet goed is overgeheveld van de oude naar nieuwe versie:
```
            {
                "schedule_id": "106a7d",
                "timeslots": [],
                "weekdays": [],
                "repeat_type": "repeat",
                "name": null,
                "enabled": false
            },
```
Deze heeft geen timeslots (maw, geen tijdstippen waarop iets moet gebeuren), dit hoort niet voor te komen en was de reden dat heel de integratie niet werkte.

Als je nog weet wat hier in het verleden stond, is dat nuttige info voor mij, want kennelijk zit er een fout in het upgrade script.

In elk geval kun je deze (na update) via de kaart weggooien en moet alles weer draaien.

Probeer het eens uit!

**Comment by mupsje** [comment]
Hoi Niels,

Bedankt voor al je werk.
Alles werkt weer naar behoren!

Die laatste met geen timeslots is geen enkele programma  (spook schedule dus)

groet
Remco

**Comment by nielsfaber** [comment]
Mooi dat het is opgelost, hoop dat de problemen nu uitblijven 👍
