### ISSUE TITLE
Hysteresis value

### ISSUE THREAD

**Issue by fiorentino77** [nielsfaber/scheduler-component#81]
Hi,
is there a possibility to set hysteresis value?
To prevent continuos on/off around the target temp set please consider an hysteresis value to get a bit margin (between 0.2 / 0.5) before the termo gives the heating consent.

Thanks in advance,

Alessandro

**Comment by KTibow** [comment]
Is this something you call in service calls?

**Comment by nielsfaber** [comment]
Scheduler only executes action(s) on the time(s) that you programmed. 
It does not take into account the current value.
If you want to have the schedule skipped when the target temperature is near the current temperature, you have the following options:
1. Use an automation to temporarily turn off the schedule when it shouldn't trigger
2. Add a condition to the schedule, with a template binary_sensor that is true/on when the schedule shouldn't trigger

**Comment by samnewman86** [comment]
This is already a feature of whatever climate integration is used. All the scheduler should do is set the setpoint like it already does.
