### ISSUE TITLE
Allow scheduling of entities with state "unknown"

### ISSUE THREAD

**Issue by dynobo** [nielsfaber/scheduler-component#87]
First: Thanks a lot for your scheduler stack, it's superb! :+1: 

I want to follow your invitation in [this Scheduler-Card issue](https://github.com/nielsfaber/scheduler-card/issues/288#issuecomment-773476021) and bring up the topic of handling `unknown` state entities.

As an owner of some thermostats, which also set the entity state to `unknown`, I'm also affected by being unable to schedule them with the scheduler-component/card. My current workaround is an automation, that regularly overwrites the state. This works, but is inconvenient and not very robust, because it can happen that the thermostat sets its state to `unknown` just before a scheduled action and before my automation can set it to a value that the scheduler-component accepts. The action then gets skipped.

It's a pity that i can't use this great scheduler properly just because the entities state string is not supported.

If I can support the work on this topic by e.g. testing stuff or providing more info, please tell me. :-)

**Comment by nielsfaber** [comment]
I added this to the v3.1.0b (beta) release.
Could you try it out and check whether the update resolves your issues?

**Comment by dynobo** [comment]
Just tested it by scheduling the temperature of my thermostat back and forth for the last 1.5 hours. Seems to work flawless! 
Thanks a lot!
