### ISSUE TITLE
Incorrect service called.

### ISSUE THREAD

**Issue by atr00** [nielsfaber/scheduler-component#97]
Using a Daikin unit with the Daikin integration, the scheduler set to activate `hvac_mode: cool` instead turns on the unit on the latest mode.
Replicating the expected behaviour in an Automation works as expected.

**Comment by KTibow** [comment]
> Replicating the expected behaviour in an Automation works as expected.

How? Screenshot?

**Comment by atrupo** [comment]
What I did is:

- Manually set the hvac to dry, then turned it off;
- Launched the automation to turn it in cool mode. It did turn on in cool mode;
- I manually switched it back to dry mode, then turned it off;
- I set the scheduler turn the hvac in cool mode and set the temperature to 24;
- It turned on in **dry** mode;
- I **manually** set it to cool mode and turned it off;
- I relaunched the scheduler using the **exact same** settings;
- It turned on in the expected cool mode.

So the scheduler does not call the correct hvac mode, but calls the latest one.

I attached all the screenshots, including the logbook that shows what I described above.

<img width="581" alt="logbook" src="https://user-images.githubusercontent.com/56029944/113403290-f7877200-93d8-11eb-9387-c66ee9408153.png">

<img width="1044" alt="automation" src="https://user-images.githubusercontent.com/56029944/113403306-feae8000-93d8-11eb-8f12-e245e4205358.png">

<img width="504" alt="scheduler" src="https://user-images.githubusercontent.com/56029944/113403321-04a46100-93d9-11eb-8a38-1d08a093b2e3.png">

**Comment by atrupo** [comment]
Do you need more info from me?

**Comment by nielsfaber** [comment]
Please update scheduler-component to v3.1.0b and try again.

**Comment by nielsfaber** [comment]
Closing due to no response from OP.
Please re-open if you still have issues.
