### ISSUE TITLE
Scheduler does not trigger anything - Thermostat

### ISSUE THREAD

**Issue by Baggerfahrer** [nielsfaber/scheduler-component#98]
Hi there!

I'm using this thermostat here via zigbee2mqtt: [clickme](https://www.zigbee2mqtt.io/devices/GS361A-H04.html).

Problem:
The scheduler does not trigger the thermostat according to the set-up. My set-up is as follows:
![grafik](https://user-images.githubusercontent.com/25987294/112733309-86ab0a80-8f3f-11eb-9345-ba6324b3d4c0.png)

I already checked the logbook after the trigger starts, but there is no change going on. The thermostat itsself is as well not triggered.
Manual changes via the developer tools do work! See here:
![grafik](https://user-images.githubusercontent.com/25987294/112733276-2ddb7200-8f3f-11eb-996e-4dabb38be234.png)

Already done steps from my side:
As stated in this thread here see here](https://github.com/nielsfaber/scheduler-card/issues/288) there was an assumption that the hvac_mode offered by the devices is not available, but the modes are clearly given and available:

![grafik](https://user-images.githubusercontent.com/25987294/112733290-5b282000-8f3f-11eb-9f52-d6e5cf220740.png)

Can anyone assist me what to do?

**Comment by nielsfaber** [comment]
I'm working on a new update of scheduler-component which implements a 1 sec delay between the actions.
I think it should solve the issue (we can always increase the delay if needed, but preferably not too much).
I'm hoping to release the version later this week.

**Comment by Baggerfahrer** [comment]
Hey Nils,

thanks for this answer! Im awaiting your update, as i really would like to use your scheduler :)
any news concerning the update?

**Comment by nielsfaber** [comment]
I just released it as v3.1.0b.
b is for beta, there might be some issues in this version still 😇

**Comment by Baggerfahrer** [comment]
@nielsfaber whatever you have done, i think this solved the issue for me :)
many thanks for that!

After updating to the newest version of you scheduler component, i tried it once again:
![grafik](https://user-images.githubusercontent.com/25987294/114603342-e7ed1080-9c97-11eb-9f2a-64cae681cc30.png)

And this is the result:
![grafik](https://user-images.githubusercontent.com/25987294/114603539-25519e00-9c98-11eb-916c-80430c05ea81.png)

And here is the relevant zigbee code for this (not relevant for you directly, but you can see the delay in the send messages...
`Zigbee2MQTT:debug 2021-04-13 **20:30:03**: Publishing 'set' 'system_mode' to 'Thermostat_Buero'
Zigbee2MQTT:info  2021-04-13 20:30:04: MQTT publish: topic 'zigbee2mqtt/Thermostat_Buero', payload '{"away_mode":"OFF","battery":87,"child_lock":"LOCK","current_heating_setpoint":20.5,"linkquality":2,"local_temperature":20.3,"preset":"manual","system_mode":"heat","valve_detection":"ON","window_detection":"OFF"}'
Zigbee2MQTT:debug 2021-04-13 **20:30:10**: Received MQTT message on 'zigbee2mqtt/Thermostat_Buero/set/current_heating_setpoint' with data **'18.0'**
Zigbee2MQTT:debug 2021-04-13 20:30:10: Publishing 'set' 'current_heating_setpoint' to 'Thermostat_Buero'
Zigbee2MQTT:debug 2021-04-13 20:30:12: Received Zigbee message from 'Thermostat_Buero', type 'commandSetDataResponse', cluster 'manuSpecificTuya', data '{"data":{"data":[0,0,0,180],"type":"Buffer"},"datatype":2,"dp":2,"fn":0,"status":0,"transid":18}' from endpoint 1 with groupID 0`

**Comment by Baggerfahrer** [comment]
i think this issue can be closed, many thanks!

**Comment by nielsfaber** [comment]
Good to hear!

**Comment by nielsfaber** [comment]
It looks like the timer part is doing fine, but the actions are somehow not executed properly.

Could you activate debug logging for scheduler for the coming days?
It can be done by adding this to configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.scheduler: debug
```

In the HA logs you should see more info when the schedule triggers.
Please post it here next time you notice the schedule failed to execute its task.

**Comment by WongGendheng** [comment]
Hey Niels, since a week my schedule for my roller shutters doesnt work anymore either, but it worked for at least a couple of weeks without failure. It might be an issue with my rollers but so far they are working fine manually. Will also activate debugging when I find the time and see where the issue lies. For me its the same, the timer part triggers but the action is not being triggered. I made no updates or anything. Just FYI.

**Comment by nielsfaber** [comment]
@Baggerfahrer Any updates on this?
I am unable to reproduce your issue, for me the repetition of schedules occurs without problems.
![image](https://user-images.githubusercontent.com/16861605/115981639-76656a00-a595-11eb-8a75-5be4eeda6d60.png)

@WongGendheng Please share debug logs next time you experience such issue, it should give us insight in whether its caused on the side of scheduler or elsewhere.

**Comment by Baggerfahrer** [comment]
@nielsfaber hey Nils, unfortunately, i had a corrupt sd card and im struggeling now to install a running version again on my pi.
i need to put this topic on hold as long as i can test it again. 
i would close it and reopen it if needed..... kind regards and thanks for your help!
